
const $RecipeIO = Java.loadClass('com.gregtechceu.gtceu.api.capability.recipe.IO');
const $ItemStackHashStrategy = Java.loadClass('com.gregtechceu.gtceu.utils.ItemStackHashStrategy');
const $ItemRecipeCapability = Java.loadClass('com.gregtechceu.gtceu.api.capability.recipe.ItemRecipeCapability');
const $GTHashMaps = Java.loadClass('com.gregtechceu.gtceu.utils.GTHashMaps');

const $Collections = Java.loadClass('java.util.Collections');
const $Object2IntOpenCustomHashMap = Java.loadClass('it.unimi.dsi.fastutil.objects.Object2IntOpenCustomHashMap');
const $Objects = Java.loadClass('java.util.Objects');
const $CosmicPartAbility = Java.loadClass('com.ghostipedia.cosmiccore.api.machine.part.CosmicPartAbility');


GTCEuStartupEvents.registry('gtceu:machine', event => {
    //Large Floral Propagator
    event.create('industrial_grade_floral_propagator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(["flora_nurturer", "nether_catalyzer"])
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('BBBBBBB', 'BQQQQQB', 'BQQQQQB', 'BQQQQQB', 'BBBBBBB')
            .aisle('BBBBBBB', 'QGGGGGQ', 'QRRRRRQ', 'Q#####Q', 'BLLLLLB')
            .aisle('BBBBBBB', 'QGPGPGQ', 'QR#R#RQ', 'Q#####Q', 'BPPPPPB')
            .aisle('BBBBBBB', 'QGGGGGQ', 'QRRRRRQ', 'Q#####Q', 'BLLLLLB')
            .aisle('BBBCBBB', 'BQQQQQB', 'BQQQQQB', 'BQQQQQB', 'BBBBBBB')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('B', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .where('P', Predicates.blocks('gtceu:steel_pipe_casing'))
            .where('G', Predicates.blocks('minecraft:moss_block'))
            .where('R', Predicates.blocks('minecraft:flowering_azalea'))
            .where('Q', Predicates.blocks('gtceu:tempered_glass'))
            .where('L', Predicates.blocks('gtceu:white_borderless_lamp'))
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/machines/flora_nurturer');





    event.create('mana_simulator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('mana_simulator')
        .appearanceBlock(GTBlocks.CASING_ALUMINIUM_FROSTPROOF)
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('##B##', '##G##', '##G##', '##G##', '##G##', '##G##', '##B##')
            .aisle('#BBB#', '#G#G#', '#G#G#', '#G#G#', '#G#G#', '#G#G#', '#BBB#')
            .aisle('BBBBB', 'G###G', 'G###G', 'G###G', 'G###G', 'G###G', 'BBBBB')
            .aisle('#BBB#', '#G#G#', '#G#G#', '#G#G#', '#G#G#', '#G#G#', '#BBB#')
            .aisle('##C##', '##G##', '##G##', '##G##', '##G##', '##G##', '##B##')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('B', Predicates.blocks(GTBlocks.CASING_ALUMINIUM_FROSTPROOF.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
            )
            .where('G', Predicates.blocks('botania:mana_glass'))
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_frost_proof', 'gtceu:block/machines/mana_fluidizer');



    event.create('essence_reactor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(['essence_reactor', 'mana_engraver'])
        .appearanceBlock(GTBlocks.CASING_TITANIUM_STABLE)
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(" AAA ", " BBB ", "  B  ", "     ", "  B  ", " BBB ", " AAA ")
            .aisle("AAAAA", "BCDCB", "     ", "     ", "     ", "BCDCB", "AAAAA")
            .aisle("AAAAA", "BDEDB", "B F B", "  E  ", "B F B", "BDEDB", "AAAAA")
            .aisle("AAAAA", "BCDCB", "     ", "     ", "     ", "BCDCB", "AAAAA")
            .aisle(" AHA ", " BBB ", "  B  ", "     ", "  B  ", " BBB ", " AAA ")
            .where('H', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.any())
            .where('D', Predicates.blocks('gtceu:terrasteel_frame'))
            .where('C', Predicates.any()
                .or(Predicates.blocks('botania:alchemy_catalyst'))
                .or(Predicates.blocks('cosmiccore:trinavine_block')))
            .where('F', Predicates.blocks('malum:wicked_spirited_glass'))
            .where('E', Predicates.blocks('malum:block_of_soul_stained_steel'))
            .where('B', Predicates.blocks(GTBlocks.CASING_ALUMINIUM_FROSTPROOF.get()))
            .where('A', Predicates.blocks(GTBlocks.CASING_TITANIUM_STABLE.get()).setMinGlobalLimited(30, 30)
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities($CosmicPartAbility.IMPORT_SOUL))
            )
            .where('G', Predicates.blocks('botania:mana_glass'))
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_stable_titanium', 'gtceu:block/machines/mana_fluidizer');

    event.create('lunar_tapestry', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(['lunar_tapestry'])
        .appearanceBlock(() => Block.getBlock('cosmiccore:high_tolerance_rhenium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("    AAA    ", "    AAA    ", "    AAA    ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .aisle("   BBBBB   ", "   CCCCC   ", "   BBBBB   ", "   CCCCC   ", "           ", "           ", "           ", "           ", "           ", "    DDD    ", "  DDDDDDD  ", "    DDD    ")
            .aisle("  ABBBBBA  ", "  ACBBBCA  ", "  ABBBBBA  ", "   CBBBC   ", "    BBB    ", "    BBB    ", "    BBB    ", "    DDD    ", "  DDDDDDD  ", " DDD   DDD ", "     D     ", "           ")
            .aisle("  ABBBBBA  ", "  ACBBBCA  ", "  ABBBBBA  ", "   CBBBC   ", "    BBB    ", "    BBB    ", "    DDD    ", "  DD C DD  ", "DD       DD", "           ", "     D     ", "           ")
            .aisle("  ABBBBBA  ", "  ACBBBCA  ", "  ABBBBBA  ", "   CBBBC   ", "    B B    ", "    DDD    ", "  DD C DD  ", "DD       DD", "           ", "           ", "    EEE    ", "           ")
            .aisle("   BBBBB   ", "   CCCCC   ", "   BBBBB   ", "   CCCCC   ", "           ", "  DDDDDDD  ", "DD       DD", "           ", "           ", "   EEEEE   ", "           ", "           ")
            .aisle("    AAA    ", "    AHA    ", "    AAA    ", "           ", "    DDD    ", " DDD   DDD ", "           ", "           ", "   EEEEE   ", "           ", "           ", "           ")
            .aisle("           ", "           ", "           ", "           ", "  DDDDDDD  ", "     D     ", "     D     ", "    EEE    ", "           ", "           ", "           ", "           ")
            .aisle("           ", "           ", "           ", "           ", "    DDD    ", "           ", "           ", "           ", "           ", "           ", "           ", "           ")
            .where('H', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.any())
            .where('E', Predicates.blocks('minecraft:tinted_glass'))
            .where('D', Predicates.blocks('cosmiccore:high_tolerance_rhenium_casing'))
            .where('C', Predicates.blocks('cosmiccore:highly_flexible_reinforced_trinavine_casing'))
            .where('B', Predicates.blocks('cosmiccore:reinforced_naquadria_casing'))
            .where('A', Predicates.blocks('cosmiccore:high_tolerance_rhenium_casing').setMinGlobalLimited(28, 30)
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
            )
            .build())
        .workableCasingModel('cosmiccore:block/casings/solid/high_tolerance_rhenium_casing', 'gtceu:block/machines/mana_fluidizer');



    // reference `.setPreviewCount(1)`
    event.create('molten_salt_reactor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('molten_salt_reactor')
        .appearanceBlock(() => Block.getBlock('cosmiccore:high_temperature_fission_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('#TTT#', '#TGT#', '#TGT#', '#TGT#', '#TGT#', '#TGT#', '#TTT#')
            .aisle('TTTTT', 'TQAQT', 'TQAQT', 'TQAQT', 'TQAQT', 'TQAQT', 'TTTTT')
            .aisle('TTTTT', 'TAQAT', 'TAQAT', 'TAQAT', 'TAQAT', 'TAQAT', 'TTTTT')
            .aisle('TTTTT', 'TQAQT', 'TQAQT', 'TQAQT', 'TQAQT', 'TQAQT', 'TTTTT')
            .aisle('#TCT#', '#TGT#', '#TGT#', '#TGT#', '#TGT#', '#TGT#', '#TTT#')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('Q', Predicates.blocks(GTBlocks.CASING_TITANIUM_PIPE.get()))
            .where('A', Predicates.blocks(GTBlocks.FIREBOX_TITANIUM.get()))
            .where('T', Predicates.blocks('cosmiccore:high_temperature_fission_casing')
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMinGlobalLimited(1, 1))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMinGlobalLimited(1, 1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMinGlobalLimited(1, 1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMinGlobalLimited(1, 1))
            )
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .build())
        .workableCasingModel('cosmiccore:block/casings/solid/high_temperature_fission_casing', 'gtceu:block/multiblock/fusion_reactor');
    //WHAT THE FUCK IS A FUNCTIONAL PLATLINE, PRESENT! LARGE! DRYER???? CUBOID??? HEAT! ! !  OWIE! ROASTED! ! ! ?????????
    // ????? ? ? ????? ?? ???? ? ? ??? ???? ? ? ???? ?? ?? ?  ?? ? ?? ? ?? ? ?? ? ?? ?? ? ??  ? ?? ? ?? ?? ?? ?? ??? ?????????
    // **FUCK**
    event.create('large_dryer', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('chemical_dehydrator')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('TTTTT', 'TGGGT', 'TTTTT')
            .aisle('TTTTT', 'GAAAG', 'TQQQT')
            .aisle('TTTTT', 'GAAAG', 'TQQQT')
            .aisle('TTTTT', 'GAAAG', 'TQQQT')
            .aisle('TTCTT', 'TGGGT', 'TTTTT')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('Q', Predicates.blocks(GTBlocks.COIL_CUPRONICKEL.get()))
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .where('A', Predicates.air())
            .where('T', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/machines/flora_nurturer');


    event.create('pulse_heat_exchanger', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(["pulse_exchange_steam_vent", "pulse_exchange_steam"])
        // ["recipeTypes(com.gregtechceu.gtceu.api.recipe.GTRecipeType[])"]('pulse_exchange_steam_vent','pulse_exchange_steam' )
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock('cosmiccore:highly_conductive_fission_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('TTT', 'TGT', 'TGT', 'TGT', 'TTT',)
            .aisle('TTT', 'GQG', 'GQG', 'GQG', 'TTT',)
            .aisle('TCT', 'TGT', 'TGT', 'TGT', 'TTT',)
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('Q', Predicates.blocks(GTBlocks.CASING_TITANIUM_PIPE.get()))
            .where('T', Predicates.blocks('cosmiccore:highly_conductive_fission_casing')
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
            )
            .where('G', Predicates.blocks(GTBlocks.CASING_TEMPERED_GLASS.get()))
            .build())
        .workableCasingModel('cosmiccore:block/casings/solid/highly_conductive_fission_casing', 'gtceu:block/multiblock/fusion_reactor');


    event.create('arboreal_growth_facility', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('arboreal_growth_facility')
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('##TTT##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##TTT##', '#######')
            .aisle('#TTTTT#', '#FTMTF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#TTTTT#', '##SSS##')
            .aisle('TTTTTTT', 'STMMMTS', 'ST###TS', 'ST###TS', 'ST###TS', 'ST###TS', 'ST###TS', 'ST###TS', 'TT###TT', '#SSSSS#')
            .aisle('TTTTTTT', 'GMMMMMG', 'G#####G', 'G#####G', 'G#####G', 'G#####G', 'G#####G', 'G#####G', 'T#####T', '#SSPSS#')
            .aisle('TTTTTTT', 'STMMMTS', 'ST###TS', 'ST###TS', 'ST###TS', 'ST###TS', 'ST###TS', 'ST###TS', 'TT###TT', '#SSSSS#')
            .aisle('#TTTTT#', '#FTMTF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#FT#TF#', '#TTTTT#', '##SSS##')
            .aisle('##TCT##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##SGS##', '##TTT##', '#######')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('G', Predicates.blocks(GTBlocks.CASING_TEMPERED_GLASS.get()))
            .where('M', Predicates.blocks('minecraft:moss_carpet'))
            .where('P', Predicates.blocks('cosmiccore:antiblock_white'))
            .where('F', Predicates.blocks('gtceu:terrasteel_frame'))
            .where('S', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get()))
            .where('T', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/machines/mana_fluidizer');

    event.create('industrial_stoneworks', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('industrial_stoneworks')
        .appearanceBlock(GTBlocks.CASING_TITANIUM_STABLE)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('#TTT#', '#TTT#', '#TTT#')
            .aisle('TTTTT', 'TWQLT', 'TGGGT')
            .aisle('TTTTT', 'GWQLG', 'TGGGT')
            .aisle('TTTTT', 'GWQLG', 'TGGGT')
            .aisle('TTTTT', 'GWQLG', 'TGGGT')
            .aisle('TTTTT', 'TWQLT', 'TGGGT')
            .aisle('#TTT#', '#TCT#', '#TTT#')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .where('W', Predicates.blocks('minecraft:water'))
            .where('L', Predicates.blocks('minecraft:lava'))
            .where('Q', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_GEARBOX.get()))
            .where('T', Predicates.blocks(GTBlocks.CASING_TITANIUM_STABLE.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_stable_titanium', 'gtceu:block/machines/rock_crusher');

    event.create('soul_forge', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('soul_forge')
        .appearanceBlock(GTBlocks.CASING_TITANIUM_STABLE)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('#TTT#', '#TTT#', '#TTT#')
            .aisle('TTTTT', 'TWQLT', 'TGGGT')
            .aisle('TTTTT', 'GWQLG', 'TGGGT')
            .aisle('TTTTT', 'GWQLG', 'TGGGT')
            .aisle('TTTTT', 'GWQLG', 'TGGGT')
            .aisle('TTTTT', 'TWQLT', 'TGGGT')
            .aisle('#TTT#', '#TCT#', '#TTT#')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .where('W', Predicates.blocks('minecraft:water'))
            .where('L', Predicates.blocks('minecraft:lava'))
            .where('Q', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_GEARBOX.get()))
            .where('T', Predicates.blocks(GTBlocks.CASING_TITANIUM_STABLE.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities($CosmicPartAbility.IMPORT_SOUL))
            )
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_stable_titanium', 'gtceu:block/machines/rock_crusher');
    event.create('leaching_plant', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('leaching_plant')
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('TTTTTTT', 'TTTTTTT', 'TTTT###',)
            .aisle('TTTTTTT', 'TPPTP#T', 'T##T###',)
            .aisle('TTTTTTT', 'TPPTP#T', 'T##T###',)
            .aisle('TTTTTTT', 'TPPTP#T', 'T##T###',)
            .aisle('TTTTTTT', 'TTTTTCT', 'TTTT###',)
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('P', Predicates.blocks(GTBlocks.CASING_STEEL_PIPE.get()))
            .where('T', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/machines/mana_fluidizer');

    event.create('grand_assembly_line', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('assembly_line')
        // .recipeTypes(["pulse_exchange_steam_vent", "pulse_exchange_steam"])
        // ["recipeTypes(com.gregtechceu.gtceu.api.recipe.GTRecipeType[])"]('pulse_exchange_steam_vent','pulse_exchange_steam' )
        .appearanceBlock(GTBlocks.COMPUTER_CASING)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC', 'CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC', 'VGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGV', 'CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC', '################################################',)
            .aisle('CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC', 'VZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZV', 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ', 'VZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZV', 'CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC',)
            .aisle('CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC', 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ', 'OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXH', 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ', 'CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC',)
            .aisle('CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC', 'VZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZV', 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ', 'VZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZVVZV', 'CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC',)
            .aisle('CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC', 'CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC', 'VGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVGVVQV', 'CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC', '################################################',)
            .where('Q', Predicates.controller(Predicates.blocks(definition.get())))
            .where('#', Predicates.any())
            .where('C', Predicates.blocks(GTBlocks.COMPUTER_CASING.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.INPUT_LASER))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.OPTICAL_DATA_RECEPTION))
                .or(Predicates.abilities(PartAbility.DATA_ACCESS))
                .or(Predicates.abilities(PartAbility.COMPUTATION_DATA_RECEPTION))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.INPUT_LASER))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.OPTICAL_DATA_RECEPTION))
                .or(Predicates.abilities(PartAbility.DATA_ACCESS))
                .or(Predicates.abilities(PartAbility.COMPUTATION_DATA_RECEPTION))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .where('H', Predicates.abilities(PartAbility.IMPORT_ITEMS))
            .where('Z', Predicates.blocks(GTBlocks.CASING_ASSEMBLY_LINE.get()))
            .where('X', Predicates.blocks(GTBlocks.CASING_ASSEMBLY_CONTROL.get()))
            .where('V', Predicates.blocks(GTBlocks.COMPUTER_HEAT_VENT.get()))
            .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
            .build())
        .workableCasingModel('gtceu:block/casings/hpca/computer_casing/side', 'gtceu:block/multiblock/network_switch');



    event.create('large_lithographic_processor', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('aio_lithography_processor')
        .appearanceBlock(GTBlocks.CASING_HSSE_STURDY)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('TTTTTTT', 'TGGGGGT', 'TTTTTTT', 'TGT####', 'TTT####')
            .aisle('TTTTTTT', 'GQQQQQG', 'TQTTTTT', 'GQG####', 'TTT####')
            .aisle('TTTTTTT', 'TGGGGGT', 'TCTTTTT', 'TGT####', 'TTT####')
            .where('#', Predicates.any())
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('Q', Predicates.blocks(GTBlocks.COIL_CUPRONICKEL.get()))
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .where('A', Predicates.air())
            .where('T', Predicates.blocks(GTBlocks.CASING_HSSE_STURDY.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
                .or(Predicates.abilities(PartAbility.MAINTENANCE))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH))
            )
            .where('G', Predicates.blocks(GTBlocks.CASING_LAMINATED_GLASS.get()))
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_sturdy_hsse', 'gtceu:block/machines/flora_nurturer');

    event.create('gravity_float_crucible', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(['gravity_float_crucible', 'sintering_extruder'])
        .appearanceBlock(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       A       ", "      ABA      ", "      ABA      ", "       A       ", "               ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       A       ", "      AAA      ", "      ACA      ", "       A       ", "               ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "     DDDDD     ", "               ", "               ", "     DDADD     ", "      AAA      ", "    AAACAAA    ", "       A       ", "   AAAAAAAAA   ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "    DD E DD    ", "               ", "               ", "    DD A DD    ", "     DAAAD     ", "   A  ACA  A   ", "    FFFAFFF    ", "  AA       AA  ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "   D   E   D   ", "               ", "               ", "   D   A   D   ", "     DAAAD     ", "  A   ACA   A  ", "   FF  A  FF   ", "  A         A  ")
            .aisle("               ", "               ", "               ", "       A       ", "      ABA      ", "      ABA      ", "      ABA      ", "  DD  ABA  DD  ", "      ABA      ", "      ABA      ", "  DD  ABA  DD  ", "   DDDAAADDD   ", "  A  AACAA  A  ", "   F   A   F   ", "  A         A  ")
            .aisle("       D       ", "       D       ", "      DDD      ", "      DDD      ", "     AC CA     ", "     AC CA     ", "     AC CA     ", "  D  AC CA  D  ", "     AC CA     ", "     AC CA     ", "  D  A   A  D  ", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "   F  AAA  F   ", "  A         A  ")
            .aisle("      DDD      ", "      DDD      ", "      D D      ", "     ADDDA     ", "     B G B     ", "     B G B     ", "     B G B     ", "  DEEB G BEED  ", "     B G B     ", "     B G B     ", "AAAAAB G BAAAAA", "BAAAAAAGAAAAAAB", "BCCCCCAGACCCCCB", "AAAAAAAQAAAAAAA", "  A         A  ")
            .aisle("       D       ", "       D       ", "      DDD      ", "      DDD      ", "     AC CA     ", "     AC CA     ", "     AC CA     ", "  D  AC CA  D  ", "     AC CA     ", "     AC CA     ", "  D  A   A  D  ", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA", "   F  AAA  F   ", "  A         A  ")
            .aisle("               ", "               ", "               ", "       A       ", "      ABA      ", "      ABA      ", "      ABA      ", "  DD  ABA  DD  ", "      ABA      ", "      ABA      ", "  DD  ABA  DD  ", "   DDDAAADDD   ", "  A  AACAA  A  ", "   F   A   F   ", "  A         A  ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "   D   E   D   ", "               ", "               ", "   D   A   D   ", "     DAAAD     ", "  A   ACA   A  ", "   FF  A  FF   ", "  A         A  ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "    DD E DD    ", "               ", "               ", "    DD A DD    ", "     DAAAD     ", "   A  ACA  A   ", "    FFFAFFF    ", "  AA       AA  ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "     DDDDD     ", "               ", "               ", "     DDADD     ", "      AAA      ", "    AAACAAA    ", "       A       ", "   AAAAAAAAA   ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       A       ", "      AAA      ", "      ACA      ", "       A       ", "               ")
            .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       A       ", "      ABA      ", "      ABA      ", "       A       ", "               ")

            .where('Q', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.any())
            .where('A', Predicates.blocks('gtceu:high_temperature_smelting_casing')
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setPreviewCount(1))
            )
            .where('B', Predicates.blocks('gtceu:heat_vent'))
            .where('C', Predicates.blocks('gtceu:molybdenum_disilicide_coil_block'))
            .where('D', Predicates.blocks('cosmiccore:high_tolerance_rhenium_casing'))
            .where('E', Predicates.blocks('gtceu:naquadah_alloy_frame'))
            .where('G', Predicates.blocks('cosmiccore:highly_flexible_reinforced_trinavine_casing'))
            .where('F', Predicates.blocks('cosmiccore:resonantly_tuned_virtue_meld_casing'))
            .build())
        .workableCasingModel('gtceu:block/casings/gcym/high_temperature_smelting_casing', 'gtceu:block/multiblock/cleanroom');



















})