CosmicFood.archetype('nibble', a => {
    a.nutrition(0, 1)
    a.hearts(1, 2)
    a.regen(0.1, 0.15)
    a.duration('3m', '4m')
})
CosmicFood.archetype('snack', a => {
    a.nutrition(2, 3)
    a.hearts(2, 3)
    a.regen(0.2, 0.3)
    a.duration('5m', '8m')
})
CosmicFood.archetype('cooked', a => {
    a.nutrition(4, 7)
    a.hearts(3, 5)
    a.regen(0.4, 0.65)
    a.duration('10m', '16m')
})
CosmicFood.archetype('meal', a => {
    a.nutrition(8, 11)
    a.hearts(5, 8)
    a.regen(0.8, 1.2)
    a.duration('20m', '32m')
})
CosmicFood.archetype('feast', a => {
    a.nutrition(12, 20)
    a.hearts(8, 12)
    a.regen(1.4, 2)
    a.duration('40m', '60m')
})
CosmicFood.archetype('juice', a => {
    a.brew()
    a.nutrition(0, 2)
    a.hearts(1, 2)
    a.regen(0.15, 0.25)
    a.duration('4m', '6m')
})
CosmicFood.archetype('draught', a => {
    a.brew()
    a.nutrition(3, 6)
    a.hearts(2, 4)
    a.regen(0.3, 0.5)
    a.duration('8m', '14m')
})
CosmicFood.archetype('elixir', a => {
    a.brew()
    a.nutrition(7, 20)
    a.hearts(4, 6)
    a.regen(0.6, 1)
    a.duration('16m', '30m')
})
CosmicFood.assign('legendarysurvivaloverhaul:*', 'juice')
