StartupEvents.registry('item', e => {

    e.create('t1_rocket_plating')
    e.create('welded_rocket_plating')
    e.create('hsse_nose_cone')
    e.create('hsse_fin')
    e.create('hsse_engine')
    e.create('osmiridium_nose_cone')
    e.create('osmiridium_fin')
    e.create('osmiridium_engine')
    e.create('americium_nose_cone')
    e.create('americium_fin')
    e.create('americium_engine')
    e.create('shredded_magebloom')
    e.create('washed_magebloom')
})
