StartupEvents.registry('item', e => {
    e.create('stainless_steel_nose_cone')
    e.create('stainless_steel_fin')
    e.create('stainless_steel_engine')
    e.create('hsse_nose_cone')
    e.create('hsse_fin')
    e.create('hsse_engine')
    e.create('osmiridium_nose_cone')
    e.create('osmiridium_fin')
    e.create('osmiridium_engine')
    e.create('americium_nose_cone')
    e.create('americium_fin')
    e.create('americium_engine')
})
