StartupEvents.registry('gtceu:material', event => {
    event.create('gtceu:sodium_hydroxide_bauxite')
        .liquid()
        .iconSet('fluid_a')
        .color(0x713800)
        .formula('(Al2O3)(SiO2)(NaOH)(H2O)')
    event.create('gtceu:heated_sodium_hydroxide_bauxite')
        .liquid()
        .iconSet('fluid_a')
        .color(0xff7e00)
        .formula('(Al2O3)(SiO2)(NaOH)(H2O)')
    event.create('gtceu:red_mud')
        .liquid()
        .iconSet('fluid_b')
        .color(0x7d3331)
        .formula('(Fe2O3)(TiO2)(Al2O3)(CaO)(V)(Ga)(H2O)')
    event.create('gtceu:neutralised_red_mud')
        .liquid()
        .iconSet('fluid_b')
        .color(0x5e4646).iconSet(GTMaterialIconSet.FLUID)
        .formula('(Fe2O3)(TiO2)(Al2O3)(CaO)(V)(Ga)(H2O)')
    event.create('gtceu:red_mud_slurry')
        .liquid()
        .iconSet('fluid_b')
        .color(0x696981)
        .formula('(Fe2O3)(TiO2)(Al2O3)(CaO)(V)(Ga)(H2O)')
    event.create('gtceu:sodium_aluminate_solution')
        .liquid()
        .iconSet('fluid_a')
        .color(0x136e5e)
        .formula('(NaAlO2)(Na2SiO3)(H2O)')
    event.create('gtceu:sodium_aluminate')
        .dust()
        .color(0x19c2a9)
        .components('1x gtceu:sodium', '1x gtceu:aluminium', '2x gtceu:oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('gtceu:sodium_silicate')
        .dust()
        .color(0x456661)
        .components('2x gtceu:sodium', '1x gtceu:silicon', '3x gtceu:oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('gtceu:aluminium_hydroxide')
        .dust()
        .color(0x64b8ed)
        .components('1x gtceu:aluminium', '3x gtceu:oxygen', '3x gtceu:hydrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('gtceu:sodium_hydroxide_solution')
        .liquid()
        .iconSet('fluid_a')
        .color(0x0944ab)
        .formula('NaOH(H2O)')

})
