StartupEvents.registry('gtceu:material', event => {

    event.create('gtceu:trinium_tetraoxide_dichloride')
        .dust()
        .formula("KeO4Cl2")
        .color(0x6b4b6e).iconSet(GTMaterialIconSet.DULL)

    event.create('gtceu:alumina')
        .dust()
        .ore()
        .color(0x09474a).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('alumina'))
    event.create('gtceu:chromium_iii_oxide')
        .dust()
        .color(0x3dc34d).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('chromium_iii_oxide'))
    event.create('gtceu:sodium_carbonate_solution')
        .liquid(new GTFluidBuilder().customStill())
        .color(0x636389)
    event.create('gtceu:sodium_chromate_solution')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xbbb310)
    event.create('gtceu:sodium_dichromate_solution')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xb55a10)
    event.create('gtceu:sodium_sulfate')
        .dust()
        .color(0xc6c6c6)
        .components('2x gtceu:sodium', '1x gtceu:sulfur', '4x gtceu:oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('gtceu:calcium_sulfide')
        .dust()
        .color(0xd8e09b)
        .components('1x gtceu:calcium', '1x gtceu:sulfur')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('gtceu:source_oils')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xe642f5)
    event.create('gtceu:source_enhanced_bio_fuel')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xe642f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:dirty_magebloom_slurry')
        .liquid()
        .color(0xe642f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:two_phase_source_benzene_mixture')
        .liquid()
        .color(0x922d98).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:source_waste_water')
        .liquid()
        .color(0x485b95).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:oxalic_acid')
        .liquid()
        .element(GTElements.get('oxalic_acid'))
        .color(0x747680).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:di_2_ethylhexyl_phosphoric_acid')
        .liquid()
        .element(GTElements.get('di_2_ethylhexyl_phosphoric_acid'))
        .color(0x4e466d).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:butanol')
        .liquid()
        .color(0xa8482d).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:2_ethyl_1_hexanol')
        .liquid()
        .color(0xd62026).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:phosphorus_trichloride')
        .liquid()
        .color(0xb38a2d).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:di_2_ethylhexyl_phosphite')
        .formula('C16H35O4P')
        .liquid()
        .color(0xd4c23d).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:di_2_ethylhexyl_phosphorochloridate')
        .liquid()
        .color(0xc5d43d).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:isodecanol')
        .liquid()
        .color(0xbf26d4).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:kerosene')
        .liquid()
        .color(0x3eccd6).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:hydroxyapatite')
        .dust()
        .color(0x2694d4).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:cyanex_272')
        .formula('C16H35O2P')
        .liquid()
        .color(0x346eeb).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:tert_butanol')
        .liquid()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:isobutene')
        .gas()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:ammonium_fluoride')
        .dust()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:sodium_hypophosphite')
        .dust()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:tert_butylhydroperoxide')
        .liquid()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:244_trimethyl_1_pentene')
        .liquid()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:244_trimethyl_2_pentene')
        .liquid()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:ferric_alumina')
        .dust()
        .color(0xf5f5f5).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:crude_source_oils')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xe642f5)

    event.create('gtceu:smoldering_steam')
        .liquid(new GTFluidBuilder().customStill().temperature(680))
    event.create('gtceu:ashdew_steam')
        .liquid(new GTFluidBuilder().customStill().temperature(1355))
    event.create('gtceu:nether_bioslurry')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xe642f5)

})

StartupEvents.postInit(event => {
    GTMaterials.get('gtceu:ammonium_fluoride').setFormula('NH₄F', true)
    GTMaterials.get('gtceu:sodium_hypophosphite').setFormula('NaPO₂H₂', true)
    GTMaterials.get('gtceu:ferric_alumina').setFormula('FeAl₂O₃', true)
})
