StartupEvents.registry('gtceu:material', event => {
    event.create('gtceu:trichlorosilane')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xfc037b).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('trichlorosilane'))
    event.create('gtceu:hydrogensilesquioxane')
        .liquid(new GTFluidBuilder().customStill())
        .color(0xc7003f).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('hydrogensilesquioxane'))
})