StartupEvents.registry('gtceu:material', event => {
    event.create('gtceu:polystyrene')
        .liquid()
        .color(0xBA968A)
    event.create('gtceu:polystyrene_sulfonate')
        .liquid()
        .color(0xDF9E88)
    event.create('gtceu:three_four_ethylenedioxythiophene')
        .liquid()
        .color(0x72A684)
    event.create('gtceu:sulfur_dichloride')
        .gas()
        .color(0x4A0500)
    event.create('gtceu:ethylene_glycol')
        .liquid()
        .color(0x006223)
    event.create('gtceu:diacetyl')
        .liquid()
        .color(0xF2E989)
    event.create('gtceu:butanediol')
        .liquid()
        .color(0x80CDFB)
    event.create('gtceu:ethylene_oxide')
        .liquid()
        .color(0xC67EAB)
    event.create('gtceu:pedot_pss')
        .liquid()
        .color(0xFF18A8)
})

StartupEvents.postInit(event => {
    GTMaterials.get('gtceu:polystyrene').setFormula('C8H8', true)
    GTMaterials.get('gtceu:polystyrene_sulfonate').setFormula('C8H8SO3', true)
    GTMaterials.get('gtceu:three_four_ethylenedioxythiophene').setFormula('C6H6O2S', true)
    GTMaterials.get('gtceu:sulfur_dichloride').setFormula('SCl2', true)
    GTMaterials.get('gtceu:ethylene_glycol').setFormula('C2H4(OH)2', true)
    GTMaterials.get('gtceu:diacetyl').setFormula('C4H6O2', true)
    GTMaterials.get('gtceu:butanediol').setFormula('C2H8(OH)2', true)
    GTMaterials.get('gtceu:ethylene_oxide').setFormula('C2H4O', true)
    GTMaterials.get('gtceu:pedot_pss').setFormula('(C6H6O2S)(C8H8SO3)', true)
})
