StartupEvents.registry('gtceu:material', event => {
    event.create('gtceu:roasted_cooperite')
        .dust()
        .element(GTElements.get('roasted_cooperite'))
        .color(0x99a37a).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:nickel_depleted_cooperite')
        .dust()
        .element(GTElements.get('nickel_depleted_cooperite'))
        .color(0x988B88).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:nickel_carbonyl')
        .liquid()
        .element(GTElements.get('nickel_carbonyl'))
        .color(0x666A72).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:cooperite_solution')
        .liquid()
        .element(GTElements.get('cooperite_solution'))
        .color(0xe9ffa7).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:plat_depleted_cooperite_solution')
        .liquid()
        .element(GTElements.get('plat_depleted_cooperite_solution'))
        .color(0x766D6B).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:ammonium_hexachloroplatinate')
        .dust()
        .element(GTElements.get('ammonium_hexachloroplatinate'))
        .color(0xCDC8A6).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(NH4)2PtCl6')
    event.create('gtceu:ammonium_hexachloropalladate')
        .dust()
        .element(GTElements.get('ammonium_hexachloropalladate'))
        .color(0x8E9190).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(NH4)2PdCl6')
    event.create('gtceu:tetraammine_palladium_chloride')
        .dust()
        .element(GTElements.get('tetraammine_palladium_chloride'))
        .color(0x81948d).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('Pd(NH3)4Cl2')
    event.create('gtceu:diamine_dichloropalladium')
        .dust()
        .element(GTElements.get('diamine_dichloropalladium'))
        .color(0x81948d).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('Pd(NH3)2Cl2')
    event.create('gtceu:insoluble_plat_group_residue')
        .dust()
        .element(GTElements.get('insoluble_plat_group_residue'))
        .color(0x634a2d).iconSet(GTMaterialIconSet.SHINY)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )

    event.create('gtceu:rhodium_depleted_plat_group_residue')
        .dust()
        .color(0x7a644b).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:iridium_rich_plat_group_residue')
        .dust()
        .color(0x8c8b6b).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:rhodium_sulfate_solution')
        .liquid()
        .color(0x85775d).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('Rh2(SO4)3')
    event.create('gtceu:zinc_sulfate')
        .dust()
        .color(0x878072).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('ZnSO4')
    event.create('gtceu:crude_rhodium')
        .dust()
        .color(0x7a4b72).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('Rh?')
    event.create('gtceu:sodium_hexachlororhodate')
        .dust()
        .color(0x824965).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('Na3RhCl6')
    event.create('gtceu:sodium_ruthenate_perosomate')
        .liquid()
        .color(0x414d54).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(RuO4)(OsO4)(NaOH)(NaCl)(H2O)')
    event.create('gtceu:ruthenium_osmium_tetroxides')
        .liquid()
        .color(0x364a5c).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(RuO4)(OsO4)(NaOH)(NaCl)(H2O)')
    event.create('gtceu:chlororuthenic_acid_osmium_tetroxide_solution')
        .liquid()
        .color(0x436c91).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(3RuO4)(4OsO4)(2NaOH)(2NaCl)(14H2O)')
    event.create('gtceu:impure_osmium_tetroxide')
        .dust()
        .color(0x496287).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(OsO4)(NaCl)')
    event.create('gtceu:chlororuthenic_acid')
        .liquid()
        .color(0x415953).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:ammonium_hexachlororuthenate')
        .dust()
        .color(0x444159).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(NH4)2RuCl6')
    event.create('gtceu:sodium_osmate')
        .dust()
        .color(0x464d9e).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('Na2OsO2(OH)4')
    event.create('gtceu:tetraammine_osmyl_chloride')
        .dust()
        .color(0xE9FFA7).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('(NH3)4(OsO2)Cl2')
    event.create('gtceu:chloroiridic_acid')
        .liquid()
        .color(0xE9FFA7).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:ammonium_hexachloroiridate')
        .dust()
        .color(0x46729e).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:cerium_oxide')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:cerium_sulfate')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:potassiunm_hydroxide')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )

    event.create('gtceu:sodium_dioxide')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:sodium_oxide')
        .dust()
        .color(0x3474eb).iconSet(GTMaterialIconSet.DULL)
        .components('2x gtceu:sodium', '1x gtceu:oxygen')
    event.create('gtceu:sodium_peroxide')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .components('2x gtceu:sodium', '2x gtceu:oxygen')
    event.create('gtceu:barium_peroxide')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:barium_oxide')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
    event.create('gtceu:carbon_tetrachloride')
        .gas()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('CCl4')
    event.create('gtceu:sodium_acetate')
        .dust()
        .color(0x6b90b5).iconSet(GTMaterialIconSet.DULL)
        .flags(
            GTMaterialFlags.DISABLE_DECOMPOSITION,
            GTMaterialFlags.NO_UNIFICATION
        )
        .formula('CH3COONa')

})
