StartupEvents.registry('gtceu:material', event => {
    event.create('gtceu:mre_chlorides')
        .liquid()
        .color(0x108277).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mre_oxides')
        .dust()
        .color(0x108277).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:monasite_slag')
        .liquid()
        .color(0xf22f11).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:xenotime_slag')
        .liquid()
        .color(0x149f2).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:undergarden_virulent_cloggrum_mixture')
        .liquid()
        .color(0x4f462b).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:lre_slag')
        .liquid()
        .color(0x158c9e).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mre_slag')
        .liquid()
        .color(0x657d43).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:hre_slag')
        .liquid()
        .color(0x836234).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:monasite_concentrate')
        .liquid()
        .color(0x9e1500).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:xenotime_concentrate')
        .liquid()
        .color(0x000F75).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mixed_lre_leachate')
        .liquid()
        .color(0x304c70).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:leached_lre_residue')
        .dust()
        .color(0x4d79b3).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:leached_lre_liquor')
        .liquid()
        .color(0x1e4442).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:wet_lre_precipitate')
        .liquid()
        .color(0x2c6360).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:chromate_waste_water')
        .liquid()
        .color(0x4d8a86).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:dried_mixed_lre_precipitate')
        .dust()
        .color(0x357a76).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:calcium_carbide')
        .dust()
        .color(0x357a76).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mre_hydroxides')
        .dust()
        .color(0x657d43).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mre_extraction_mix')
        .liquid()
        .color(0x357a76).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mre_leachate')
        .liquid()
        .color(0x357a76).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mre_organic_leachate')
        .liquid()
        .color(0x357a76).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:mre_mixed')
        .dust()
        .color(0x357a76).iconSet(GTMaterialIconSet.DULL)
    event.create('gtceu:sodium_phosphate')
        .dust()
        .color(0x357a76).iconSet(GTMaterialIconSet.DULL)
})


StartupEvents.postInit(event => {
    GTMaterials.get('gtceu:oxalic_acid').setFormula('C2H2O4', true)
    GTMaterials.get('gtceu:di_2_ethylhexyl_phosphoric_acid').setFormula('(C8H17O)2PO2H', true)
    GTMaterials.get('gtceu:sodium_phosphate').setFormula('Na3PO4', true)
})