let yeet = (itemName) => {
  ServerEvents.recipes(event => {
    event.remove({ output: itemName })
  })
  ServerEvents.tags('item', event => {
    console.log('[3] - [1] - TAG-WATCHER') //not sure if i should change the log numbers? copied from the ae2_mods.js
    event.add('c:hidden_from_recipe_viewers', itemName)
    event.add('c:viewers/hidden_from_recipe', itemName)
  })
}
yeet('cognition:molecular_metamorpher')
yeet('cognition:primordial_assembly')
yeet('cognition:flask_of_poseidon')
yeet('cognition:flask_of_hades')
yeet('cognition:flask_of_chaos')
yeet('cognition:transforming_focus')
yeet('cognition:mending_neurogel_blob')
yeet('cognition:mending_neurogel')
yeet('cognition:fluorescent_agar')
yeet('cognition:nutrient_agar')
yeet('cognition:insightful_agar')
yeet('cognition:extravagant_agar')
yeet('cognition:bibliophage')
yeet('cognition:experience_jelly')
yeet('cognition:forgotten_dust')
yeet('cognition:forgotten_dust_block')
yeet('cognition:infected_bookshelf')
yeet('cognition:infected_enchanted_bookshelf')
yeet('cognition:infected_archivers_bookshelf')

ServerEvents.recipes(event => {
    event.remove({ id: 'cognition:bibliophage' })
    event.remove({ id: 'cognition:metamorpher/primordial_assembly' })
    event.remove({ id: 'cognition:metamorpher/cognitive_alloy_metamorphosis' })
    event.remove({ id: 'cognition:metamorpher/cognitive_crystal_metamorphosis' })
    event.remove({ id: 'cognition:cognitive_alloy' })
    event.remove({ id: 'cognition:cognitive_flux' })
    event.remove({ id: 'cognition:whisperglass' })
    event.remove({ id: /cognition:metamorpher(.*)/})
    event.remove({ id: /cognition:infecting(.*)/})
    event.remove({ id: 'cognition:filling/golden_apple_filling' })
         
    event.recipes.gtceu.mixer('cognitive_flux_mixer')
        .itemInputs(['4x gtceu:nether_quartz_dust', '4x gtceu:lapis_dust', '4x minecraft:soul_sand'])
        .itemOutputs('4x cognition:cognitive_flux')
        .duration(100)
        .EUt(12)
    event.recipes.gtceu.alloy_smelter('cognitive_alloy')
        .itemInputs(['2x cognition:cognitive_flux', 'occultism:iesnium_ingot'])
        .itemOutputs('cognition:cognitive_alloy')
        .duration(240)
        .EUt(12)
    event.recipes.gtceu.alloy_smelter('whisper_glass')
        .itemInputs(['4x cognition:cognitive_flux', 'minecraft:glass'])
        .itemOutputs('cognition:whisperglass')
        .duration(160)
        .EUt(12)
    event.recipes.gtceu.alloy_smelter('calcarine_matrix')
        .itemInputs(['2x cognition:astute_assembly', '2x cognition:nightmare_bottle'])
        .itemOutputs('cognition:calcarine_matrix')
        .duration(500)
        .EUt(24)
})