//none of the materials that have ores generate atm because i still don't understand kubejs gt ore generation, i (would)/(will) (if i could)/(when i can)
GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('alumina')
        .dust()
        .ore()
        .color(0x09474a).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('alumina'))
    event.create('chromium_iii_oxide')
        .dust()
        .color(0x3dc34d).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('chromium_iii_oxide'))
    event.create('sodium_carbonate_solution')
        .fluid()
        .color(0x636389)
    event.create('sodium_chromate_solution')
        .fluid()
        .color(0xbbb310)
    event.create('sodium_dichromate_solution')
        .fluid()
        .color(0xb55a10)
    event.create('sodium_sulfate')
        .dust()
        .color(0xc6c6c6)
        .components('2x sodium', '1x sulfur', '4x oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('calcium_sulfide')
        .dust()
        .color(0xd8e09b)
        .components('1x calcium', '1x sulfur')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('source_oils')
        .fluid()
        .color(0xe642f5).iconSet(GTMaterialIconSet.DULL)
    event.create('source_enhanced_bio_fuel')
        .fluid()
        .color(0xe642f5).iconSet(GTMaterialIconSet.DULL)
    
})
