//none of the materials that have ores generate atm because i still don't understand kubejs gt ore generation, i (would)/(will) (if i could)/(when i can)
GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('alumina')
        .dust()
        .ore()
        .color(0x09474a).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('alumina'))
    event.create('chromium_iii_oxide')
        .dust()
        .color(0x3dc34d).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('chromium_iii_oxide'))
    event.create('banded_iron')
        .ingot()
        .ore()
        .color(0x513232).iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR)
    event.create('sodium_carbonate_solution')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0x636389)
    event.create('sodium_chromate_solution')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xbbb310)
    event.create('sodium_dichromate_solution')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xb55a10)
    event.create('sodium_sulfate')
        .dust()
        .color(0xc6c6c6)
        .components('2x sodium', '1x sulfur', '4x oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('calcium_sulfide')
        .dust()
        .color(0xd8e09b)
        .components('1x calcium', '1x sulfur')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    //Source line
    event.create('source_oils')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xe642f5)
    event.create('source_enhanced_bio_fuel')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xe642f5).iconSet(GTMaterialIconSet.DULL)
    event.create('dirty_magebloom_slurry')
        .fluid()
        .color(0xe642f5).iconSet(GTMaterialIconSet.DULL)
    event.create('two_phase_source_benzene_mixture')
        .fluid()
        .color(0x922d98).iconSet(GTMaterialIconSet.DULL)
    event.create('source_waste_water')
        .fluid()
        .color(0x485b95).iconSet(GTMaterialIconSet.DULL)
    //LRE line
    event.create('oxalic_acid')
        .fluid()
        .color(0x747680).iconSet(GTMaterialIconSet.DULL)
    event.create('di_2_ethylhexyl_phosphoric_acid')
        .fluid()
        .color(0x4e466d).iconSet(GTMaterialIconSet.DULL)
    event.create('chromium_hydroxide')
        .dust()
        .color(0x169EAB).iconSet(GTMaterialIconSet.DULL)
    //D2EHPA synthesis
    event.create('butanol')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    event.create('2_ethyl_1_hexanol')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    event.create('phosphorus_trichloride')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    event.create('di(2_ethylhexyl)_phosphite')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    event.create('di(2_ethylhexyl)_phosphorochloridate')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    event.create('di(2_ethylhexyl)_phosphoric_acid')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    //MRE tier 2
    event.create('isodecanol')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    event.create('kerosene')
        .fluid()
        .color().iconSet(GTMaterialIconSet.DULL)
    event.create('hydroxyapatite')
        .dust()
        .color().iconSet(GTMaterialIconSet.DULL)
})
