StartupEvents.registry('gtceu:element', event => {
    event.create('ether_steel').protons(27).neutrons(177).symbol('Ma₂FeMnNi(Si(Fe₂S₂)₅(Cr₂ZiAbAl)Hg₃)')
    event.create('manasteel').protons(20).neutrons(80).symbol('Ma*(Si(FeS₂)₅(CrAl₂O₃)Hg₃)(AuAg)')
    event.create('runesteel').protons(20).neutrons(80).symbol('FeC*?')
    event.create('zanite').protons(134).neutrons(335).symbol('Zi')
    event.create('ambrosium').protons(135).neutrons(338).symbol('Ab')
    event.create('prism_tungstensteel').protons(69).neutrons(157).symbol('PiFeW')
    event.create('virtue').protons(0).neutrons(450).symbol('ERROR₉₉₉')
    event.create('trichlorosilane').protons(135).neutrons(135).symbol('HCl3Si')
    event.create('hydrogensilesquioxane').protons(135).neutrons(135).symbol('[HSiO3/2]₈')
    event.create('desh').protons(135).neutrons(135).symbol('De')

    event.create('roasted_cooperite').protons(78).neutrons(78).symbol('Pt₃PdNi')
    event.create('nickel_depleted_cooperite').protons(78).neutrons(78).symbol('Pt₃Pd')
    event.create('nickel_carbonyl').protons(78).neutrons(78).symbol('Ni(CO)₄')
    event.create('cooperite_solution').protons(78).neutrons(78).symbol('(3H₂PtCl₆)(H₂PdCl₄)(14H₂O)')
    event.create('plat_depleted_cooperite_solution').protons(78).neutrons(78).symbol('(H₂PdCl₄)(H₂O)')
    event.create('ammonium_hexachloroplatinate').protons(78).neutrons(78).symbol('(NH₄)₂PtCl₆')
    event.create('ammonium_hexachloropalladate').protons(78).neutrons(78).symbol('(NH₄)₂PdCl₆')
    event.create('tetraammine_palladium_chloride').protons(78).neutrons(78).symbol('Pd(NH₃)₄Cl₂')
    event.create('diamine_dichloropalladium').protons(78).neutrons(78).symbol('Pd(NH₃)2Cl₂')
    event.create('insoluble_plat_group_residue').protons(78).neutrons(78).symbol('(RhRuOsIr)')
})
