GTCEuStartupEvents.registry('gtceu:material_icon_set', event => {
    event.create('mana')
        .parent('shiny')
    event.create('fluid_a')
        .parent('shiny')
    event.create('fluid_b')
        .parent('shiny')
    event.create('fluid_c')
        .parent('shiny')
    event.create('utherium')
        .parent('diamond')
    event.create('rune_steel')
        .parent('bright')
    event.create('prisma')
        .parent('diamond')
    event.create('starry')
        .parent('dull')
})