GTCEuStartupEvents.registry('gtceu:material_icon_set', event => {
    event.create('mana')
        .parent('shiny')
    event.create('fluid_a')
        .parent('shiny')
    event.create('fluid_b')
        .parent('shiny')
    event.create('fluid_c')
        .parent('shiny')
    event.create('starry')
    .parent('dull')
})