GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('polystyrene')
        .liquid()
        .color(0xBA968A)
    event.create('polystyrene_sulfonate')
        .liquid()
        .color(0xDF9E88)
    event.create('three_four_ethylenedioxythiophene')
        .liquid()
        .color(0x72A684)
    event.create('sulfur_dichloride')
        .gas()
        .color(0x4A0500)
    event.create('ethylene_glycol')
        .liquid()
        .color(0x006223)
    event.create('diacetyl')
        .liquid()
        .color(0xF2E989)
    event.create('butanediol')
        .liquid()
        .color(0x80CDFB)
    event.create('ethylene_oxide')
        .liquid()
        .color(0xC67EAB)
    event.create('pedot_pss')
        .liquid()
        .color(0xFF18A8)
})

GTCEuStartupEvents.materialModification(event => {
    GTMaterials.get('polystyrene').setFormula('C8H8', true)
    GTMaterials.get('polystyrene_sulfonate').setFormula('C8H8SO3', true)
    GTMaterials.get('three_four_ethylenedioxythiophene').setFormula('C6H6O2S', true)
    GTMaterials.get('sulfur_dichloride').setFormula('SCl2', true)
    GTMaterials.get('ethylene_glycol').setFormula('C2H4(OH)2', true)
    GTMaterials.get('diacetyl').setFormula('C4H6O2', true)
    GTMaterials.get('butanediol').setFormula('C2H8(OH)2', true)
    GTMaterials.get('ethylene_oxide').setFormula('C2H4O', true)
    GTMaterials.get('pedot_pss').setFormula('(C6H6O2S)(C8H8SO3)', true)
})