StartupEvents.registry('gtceu:dimension_marker', event => {
    event.create('ad_astra:earth_orbit')
        .iconSupplier(() => Item.of('ad_astra:earth_globe').getItem())
        .tier(0)
        .overrideName('Earth Orbit')
    event.create('undergarden:undergarden')
        .iconSupplier(() => Item.of('cosmiccore:undergarden_dim').getItem())
        .tier(0)
        .overrideName('The Undergarden')
    event.create('frontiers:sun_orbit')
        .iconSupplier(() => Item.of('cosmiccore:auric_asteroid').getItem())
        .tier(4)
        .overrideName('Sun Orbit')
    event.create('ad_astra:moon')
        .iconSupplier(() => Item.of('ad_astra:moon_globe').getItem())
        .tier(1)
        .overrideName('§bThe Moon')
    event.create('frontiers:firmament')
        .iconSupplier(() => Item.of('cosmiccore:firmament_permit').getItem())
        .tier(0)
        .overrideName('§bThe Firmament')
    event.create('ad_astra:mars')
        .iconSupplier(() => Item.of('ad_astra:mars_globe').getItem())
        .tier(2)
        .overrideName('§bMars')
    event.create('ad_astra:venus')
        .iconSupplier(() => Item.of('ad_astra:venus_globe').getItem())
        .tier(3)
        .overrideName('§bVenus')
    event.create('ad_astra:mercury')
        .iconSupplier(() => Item.of('ad_astra:mercury_globe').getItem())
        .tier(3)
        .overrideName('§bMercury')
})