# Default base value for any item, that doesn't have any valuable tags.
defaultBaseItemValue: 0.33
# Difficulty threshold for spawning locks. Locks with difficulty below this value will not spawn.
difficultyThreshold: 0.05
# Disables rendering of locks for players.
disableLockRendering: false
# Multiplies every difficulty by this value before clamping, simple as that.
globalDifficultyMultiplier: 1.0
# Linearly maps calculated item values within this range to a 0% – 100% difficulty scale.
itemValueRange:
    max: 224.0
    min: 0.0
# Multiplies the difficulty for the loot table by the value provided below (before clamping).
lootTableMultiplier:
    minecraft:chests/example: 1.5
# Minigame type by dimension.
minigameType:
    minecraft:overworld: clavis:gear
    minecraft:the_end: clavis:mirror
# Additional value multipliers. Added on top of item value
modifiers:
    # Added to the total multiplier if the item is equippable in curios or trinkets.
    isCuriosOrTrinkets: 8.0
    # Added to the total multiplier if the item's max stack size is less than 16.
    lowStackSize: 1.25
    # Added to the total multiplier per an enchantment level.
    perEnchantmentLevel: 0.25
    # Added to the total multiplier if the item is of one of specified rarities.
    rarity:
        UNCOMMON: 1.25
        EPIC: 2.0
        RARE: 1.5
# Penalty for losing HP.
qualityPenaltyPerHit: 0.2
# Starting quality of a minigame.
startingQuality: # 0.0 - 10.0
    2.0
# Determines whether losing the minigame unlocks the lock.
unlocksAfterLosing: true
# Clamps the difficulty to this value.
upperDifficultyClamp: 1.5
# A collection of valuable items and tags and its values. If an item isn't in the list and doesn't have any of these tags, it will use the base item value above. Item IDs are prioritized over tags.
valuableItems:
    minecraft:saddle: 1.25
    minecraft:name_tag: 1.0
    '#c:ingots': 5.0
    '#c:gems': 8.0
    '#c:storage_blocks': 16.0
    '#c:ores': 4.0
    '#c:raw_materials': 4.0
    '#c:rods': 6.0
    '#c:alloys': 6.0
    '#c:circuits': 8.0
    '#c:dusts': 1.0
    '#c:foods/golden': 16.0
    '#c:tools': 2.0
    '#c:armors': 2.0
    '#c:music_discs': 8.0
