
##Basic Burner Requirements
[basic_burner]
	#When set to true, an active Basic Burner produces the same heat as a Kindled Blaze Burner and an empowered Basic Burner produces the same heat as a Seething Blaze Burner. Inactive state is unaffected.
	hotBurners = false
	#When set to false, it disables Basic Burner role in the steam engine heating system, only leaving it for recipes. This will also re-enable all passive heaters as a consequence. The Basic Burner Block tooltip must be altered via changing the lang file, if you use this and the inaccuracy bothers you.
	basicBurnerBoiler = true
	#When set to true, ignores Basic Burner Fuel Item Tag Whitelist, instead accepts anything with a valid BurnTime.
	ignoresFuelTagWhitelist = true
	#How much more fuel a non-empowered Basic Burner consumes. Use fanMultiplier for fan-empowered burners. Intended for use with the hotBurners option, the default value of 1 is recommended otherwise.
	#Range: > 1
	baseMultiplier = 1
	#How much more fuel a Basic Burner consumes when empowered by an encased fan.
	#Range: > 1
	fanMultiplier = 32
	#How much fan speed is needed for the Basic Burner to be empowered.
	#Range: > 1
	fanSpeedRequired = 256

