#A list of class:method strings (render methods) that the dark shader will not be applied to.
#Each string consists of the class and the method (or any substring) to block the dark shader.
#For example, 'renderHunger' is sufficient to block 'net.minecraftforge.client.gui.overlay.ForgeGui:renderFood' (either will work).
METHOD_SHADER_BLACKLIST = ["mezz.jei.common.render.FluidTankRenderer:drawTextureWithMasking", "mezz.jei.library.render.FluidTankRenderer:drawTextureWithMasking", "renderCrosshair", "m_93080_", "renderSky", "m_202423_", "renderHotbar", "m_93009_", "m_193837_", "setupOverlayRenderState", "net.minecraftforge.client.gui.overlay.ForgeGui", "renderFood", "renderExperienceBar", "m_93071_", "renderLogo", "m_280037_", "m_280118_", "net.minecraft.client.gui.Gui", "net.minecraft.src.C_3431_", "renderDirtBackground", "m_280039_", "m_280039_", "configured.client.screen.ListMenuScreen", "OnlineServerEntry:drawIcon", "OnlineServerEntry:m_99889_", "WorldSelectionList$WorldListEntry:render", "WorldSelectionList$WorldListEntry:m_6311_", "CubeMap:render", "CubeMap:m_108849_", "squeek.appleskin.client.HUDOverlayHandler", "shadows.packmenu.ExtendedMenuScreen", "net.minecraftforge.client.gui.widget.ModListWidget$ModEntry:m_6311__", "fuzs.forgeconfigscreens.client.gui.widget.MutableIconButton:m_87963_", "fuzs.forgeconfigscreens.client.gui.widget.MutableIconButton:m_280322_", "fuzs.overflowingbars.client.handler.ArmorBarRenderer:renderArmorBar", "fuzs.overflowingbars.client.handler.HealthBarRenderer:renderHeart", "fuzs.overflowingbars.client.handler.RowCountRenderer:drawBorderedSprite", "com.momosoftworks.coldsweat.client.gui.Overlays:lambda$static$4", "journeymap.client.render.RenderWrapper:setShader", "com.momosoftworks.coldsweat.client.gui.Overlays:lambda$static$5", "tictim.paraglider.client.render.StaminaWheelRenderer:draw", "squeek.appleskin.client.HUDOverlayHandler:drawExhaustionOverlay", "squeek.appleskin.client.HUDOverlayHandler:drawSaturationOverlay", "dev.shadowsoffire.apotheosis.adventure.client.SocketTooltipRenderer:m_183452_", "tfar.overpoweredarmorbar.overlay.OverlayEventHandler:drawTexturedModalRect", "daripher.skilltree.client.screen.SkillTreeScreen:m_280273_", "daripher.skilltree.client.widget.TextField:m_87963", "daripher.skilltree.client.widget.Label:m_87963_", "daripher.skilltree.client.screen.SkillTreeScreen:renderOverlay", "daripher.skilltree.client.widget.Button:renderBackground", "daripher.skilltree.client.screen.ScreenHelper:renderConnection", "daripher.skilltree.client.widget.SkillButton:renderBackground"]
#Enabling this config will (every 5 seconds) dump which methods were used to render GUIs that the dark shader was applied to
#The dump will consist of a list of class:method strings, e.g. 'net.minecraftforge.client.gui.overlay.ForgeGui:renderFood'
#Use this feature to help find the render method strings of GUIs you would like to blacklist.
METHOD_SHADER_DUMP = true

["Inventory Button"]
	#Pixels away from the left of the GUI in the x axis
	#Range: > 0
	X = 2
	#Pixels away from the bottom of the GUI in the y axis
	#Range: > 0
	Y = 20

["Main Menu Button"]
	#Enabled
	SHOW = true
	#Pixels away from the left of the GUI in the x axis
	#Range: > 0
	MAIN_X = 4
	#Pixels away from the bottom of the GUI in the y axis
	#Range: > 0
	MAIN_Y = 40

