
[Gameplay]
	#Skyjade tools will be enchantable
	"Skyjade Enchant" = false
	#Always Enable halloween content, excluding the halloween slider
	"Always Enable Halloween Content" = false
	#Enabling this removes Deep Aether's creative mode tab, and adds Deep Aether's items to Aether's tabs
	"Use Aether's Creative Mode Tabs" = false

[Biomes]
	#Disables Roseroot Forest biomes from generating. Might make some content unobtainable
	"Disable Roseroot Forest Biomes" = false
	#Disables Yagroot Swamp biomes from generating. Might make some content unobtainable
	"Disable Yagroot Swamp Biomes" = false
	#Disables Golden Heights biomes from generating. Might make some content unobtainable
	"Disable Golden Heights Biomes" = false
	#Disables Aerlavender Fields biomes from generating. Might make some content unobtainable
	"Disable Aerlavender Fields Biomes" = false
	#The weighting of Deep Aether regions in the aether
	"Deep Aether Biome Weight" = 20

