#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jul 19 23:35:19 EDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableTextureMaterialFallback=true
enableDebugOptions=false
blockUnknownShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1 + EuphoriaPatches_1.6.5
enableShaders=true
