#Specifies if the landing phase should have a much higher chance to be skipped. Makes the fight quicker by avoiding long dull periods where the Ender Dragon is flying for a long time, before it perches.
#Default: true
skipLandingPhase = true
#Specifies if the crash phase should cause blocks to be flung.
#Default: true
crashPhaseDestroysBlocks = true
#Specifies the max amount of baby ender dragons the Ender Dragon can spawn during its hatching (dive bomb) phase.
#Default: 4
#Range: 1 ~ 16
maxBabyEnderDragons = 4
#Specifies the amount of special attacks, plus the amount of remaining end crystals, the dragon must do until it can potentially perch.
#Default: 4
#Range: 1 ~ 16
attacksUntilPerch = 4

#Enaled Custom Phases
[enabled_custom_phases]
	#Specifies if this custom dragon phase should be enabled or not
	#Requires restart.
	#Default: true
	enableSnatchPlayer = true
	#Specifies if this custom dragon phase should be enabled or not
	#Requires restart.
	#Default: true
	enableCrashPlayer = true
	#Specifies if this custom dragon phase should be enabled or not
	#Requires restart.
	#Default: true
	enableDiveBombPlayer = true

