
["Allowed Experience Fluids"]
	#Add IDs of fluids you want the obelisk to support here in the form mod_id:fluid_name. Fluids have to be tagged forge:experience.
	AllowedFluids = ["mob_grinding_utils:fluid_xp", "cofh_core:experience", "industrialforegoing:essence", "sophisticatedcore:xp_still", "enderio:xp_juice"]

["Experience Obelisk Capacity"]
	#The fluid capacity of the obelisk in mB. Default = 100000000, which is ~1072 levels' worth. Ensure that the new value is divisible by 20.
	#Warning: setting this value above the default may lead to unintended loss or gain of XP.
	#Range: 1000 ~ 2147483640
	Capacity = 100000000

["Enlightened Amulet Range"]
	#The range of the enlightened amulet in blocks. Accepts decimals. Default = 8.0.
	#Range: 1.0 ~ 16.0
	Range = 8.0

["Staff of Attunement Range"]
	#The binding range of the Staff of Attunement in blocks. Accepts decimals. Default = 48.0.
	#Lower this if you experience issues with bound blocks not working correctly.
	#Range: 4.0 ~ 100.0
	Range = 48.0

["Enable Name Formatting Anvil Recipes"]
	#Whether custom recipes that allow for the changing of item name color & formatting are enabled
	Formatting = true

