# This is the early configuration file for GregTech CEu Modern.
# The following options can be enabled or disabled if there is a compatibility issue.
# Add a line with your option name and =true or =false at the bottom of the file to enable
# or disable a rule. For example:
#   client.bloom.safe_mode=true
# Do not include the #. You may reset to defaults by deleting this file.
#
# Available options:
#
#  # Whether to use a 'safe mode' for bloom rendering
#  # NOTE: considerably slower than the normal logic, but likely fixes compatibility issues with other mods.
#  # Requires restarting the client to take effect.
#  client.bloom.safe_mode=false # (default)
#
#
# User overrides go here.
