#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 27 19:49:17 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
