#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Dec 13 07:42:24 EST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=
