#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 19 17:46:20 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
