ServerEvents.recipes(event => {
    const canonicalControllerRecipes = ['gtceu:large_macerator', 'gtceu:large_arc_smelter', 'gtceu:large_ore_washer', 'gtceu:large_sifter', 'gtceu:large_engraver', 'gtceu:large_packer', 'gtceu:large_mixer', 'gtceu:large_centrifuge', 'gtceu:large_assembler', 'gtceu:large_electrolyzer', 'gtceu:large_electromagnet', 'gtceu:large_autoclave', 'gtceu:large_material_press', 'gtceu:large_brewer', 'gtceu:large_cutter', 'gtceu:large_distillery', 'gtceu:large_extractor', 'gtceu:large_extruder']
    canonicalControllerRecipes.forEach(recipe => event.remove({ id: recipe }))

    event.shaped('gtceu:large_maceration_tower', ['PCP', 'BXB', 'MKM'], { C: '#gtceu:circuits/ev', P: 'gtceu:tungsten_carbide_plate', B: 'gtceu:ev_electric_piston', M: 'gtceu:ev_electric_motor', X: 'gtceu:ev_macerator', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_maceration_tower_ev')
    event.shaped('gtceu:large_arc_smelter', ['KDK', 'CXC', 'PPP'], { C: '#gtceu:circuits/ev', P: 'gtceu:tantalum_carbide_plate', X: 'gtceu:ev_arc_furnace', D: 'gtceu:graphite_dust', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_arc_smelter_ev')
    event.shaped('gtceu:large_chemical_bath', ['PGP', 'CXC', 'MKM'], { C: '#gtceu:circuits/ev', G: 'gtceu:tempered_glass', P: 'gtceu:ev_electric_pump', M: 'gtceu:ev_conveyor_module', X: 'gtceu:ev_ore_washer', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_chemical_bath_ev')
    event.shaped('gtceu:large_sifting_funnel', ['PCP', 'EXE', 'PKP'], { C: '#gtceu:circuits/ev', P: 'gtceu:hsla_steel_plate', E: 'gtceu:ev_electric_piston', X: 'gtceu:ev_sifter', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_sifting_funnel_ev')
    event.shaped('gtceu:large_engraving_laser', ['ICI', 'EXE', 'PKP'], { C: '#gtceu:circuits/ev', P: 'gtceu:double_tantalum_carbide_plate', I: 'gtceu:ev_emitter', E: 'gtceu:ev_electric_piston', X: 'gtceu:ev_laser_engraver', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_engraving_laser_ev')
    event.shaped('gtceu:large_packer', ['RCR', 'PXP', 'KPK'], { C: '#gtceu:circuits/ev', P: 'gtceu:hsla_steel_plate', R: 'gtceu:ev_robot_arm', K: 'gtceu:ev_conveyor_module', X: 'gtceu:ev_packer' }).id('frontiers:large_packer_ev')
    event.shaped('gtceu:large_mixer', ['FCF', 'RXR', 'MKM'], { C: '#gtceu:circuits/ev', F: 'gtceu:polybenzimidazole_normal_fluid_pipe', R: 'gtceu:osmiridium_rotor', M: 'gtceu:ev_electric_motor', X: 'gtceu:ev_mixer', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_mixer_ev')
    event.shaped('gtceu:large_centrifuge', ['SFS', 'CXC', 'MKM'], { C: '#gtceu:circuits/ev', F: 'gtceu:stainless_steel_huge_fluid_pipe', S: 'gtceu:molybdenum_disilicide_spring', M: 'gtceu:ev_electric_motor', X: 'gtceu:ev_centrifuge', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_centrifuge_ev')
    event.shaped('gtceu:large_assembler', ['RKR', 'CXC', 'MKM'], { C: '#gtceu:circuits/ev', R: 'gtceu:ev_robot_arm', M: 'gtceu:ev_conveyor_module', X: 'gtceu:ev_assembler', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_assembler_ev')
    event.shaped('gtceu:large_electrolyzer', ['PCP', 'WXW', 'PKP'], { C: '#gtceu:circuits/ev', P: 'gtceu:black_steel_plate', W: 'gtceu:aluminium_single_cable', X: 'gtceu:ev_electrolyzer', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_electrolyzer_ev')
    event.shaped('gtceu:large_electromagnet', ['PWP', 'CXC', 'PKP'], { C: '#gtceu:circuits/ev', P: 'gtceu:blue_steel_plate', W: 'gtceu:osmium_quadruple_wire', X: 'gtceu:ev_electromagnetic_separator', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_electromagnet_ev')
    event.shaped('gtceu:large_autoclave', ['PCP', 'PAP', 'BKB'], { C: '#gtceu:circuits/ev', A: 'gtceu:ev_autoclave', P: 'gtceu:double_hsla_steel_plate', B: 'gtceu:ev_electric_pump', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_autoclave_ev')
    event.shaped('gtceu:large_material_press', ['PKP', 'BZG', 'FKH'], { Z: '#gtceu:circuits/ev', B: 'gtceu:ev_bender', P: 'gtceu:ev_electric_piston', G: 'gtceu:ev_compressor', F: 'gtceu:ev_forming_press', H: 'gtceu:ev_forge_hammer', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_material_press_ev')
    event.shaped('gtceu:large_brewer', ['SZS', 'FBH', 'EKE'], { Z: '#gtceu:circuits/ev', S: 'gtceu:molybdenum_disilicide_spring', F: 'gtceu:ev_fermenter', E: 'gtceu:ev_electric_pump', B: 'gtceu:ev_brewery', H: 'gtceu:ev_fluid_heater', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_brewer_ev')
    event.shaped('gtceu:large_cutter', ['SMS', 'CZL', 'EKE'], { Z: '#gtceu:circuits/ev', L: 'gtceu:ev_lathe', E: 'gtceu:ev_electric_motor', C: 'gtceu:ev_cutter', M: 'gtceu:ev_conveyor_module', S: 'gtceu:tungsten_carbide_buzz_saw_blade', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_cutter_ev')
    event.shaped('gtceu:large_distillery', ['PZP', 'EDE', 'PZP'], { Z: '#gtceu:circuits/ev', D: 'gtceu:distillation_tower', E: 'gtceu:ev_electric_pump', P: 'gtceu:iridium_large_fluid_pipe' }).id('frontiers:large_distillery_ev')
    event.shaped('gtceu:large_extractor', ['PTP', 'EZC', 'BKB'], { Z: '#gtceu:circuits/ev', B: 'gtceu:ev_electric_piston', P: 'gtceu:ev_electric_pump', E: 'gtceu:ev_extractor', C: 'gtceu:ev_canner', T: 'gtceu:tempered_glass', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_extractor_ev')
    event.shaped('gtceu:large_extruder', ['PZP', 'SES', 'PKP'], { Z: '#gtceu:circuits/ev', E: 'gtceu:ev_extruder', P: 'gtceu:ev_electric_piston', S: 'gtceu:molybdenum_disilicide_spring', K: 'gtceu:aluminium_single_cable' }).id('frontiers:large_extruder_ev')
    event.shaped('gtceu:ev_machine_casing', ['ABA', 'CDC', 'ACA'], { A: 'cosmiccore:carbon_ethersteel_lattice', B: 'cosmiccore:ev_cogwork_magicapacitor', C: 'cosmiccore:ev_cladding', D: 'cosmiccore:ev_modular_frameworks' })
    event.shaped('cosmiccore:ev_modular_frameworks', ['ABA', 'BCB', 'ABA'], { A: 'cosmiccore:starstruck_halite_bolt', B: 'gtceu:luminized_titanium_rod', C: 'gtceu:small_luminized_titanium_gear' })
    event.shaped('2x cosmiccore:ev_cladding', ['ABA', 'BCB', 'ABA'], { A: 'gtceu:luminized_titanium_bolt', B: 'gtceu:polytetrafluoroethylene_foil', C: 'gtceu:double_tempered_iesnium_plate' })
    event.shaped('gtceu:ev_machine_hull', ['ABA', 'CDC', 'AEA'], { A: 'gtceu:platinum_foil', B: 'gtceu:stainless_steel_plate', C: 'gtceu:nichrome_single_cable', D: 'gtceu:ev_machine_casing', E: 'cosmiccore:small_pale_steel_spring' })


    event.recipes.gtceu.assembler('frontiers:ev_machine_casing/assembler_efficient')
        .itemInputs('gtceu:ev_machine_casing', '2x gtceu:platinum_foil', '2x gtceu:nichrome_single_cable')
        .itemOutputs('gtceu:ev_machine_hull')
        .inputFluids('288x gtceu:polytetrafluoroethylene')
        .EUt(GTValues.VA[GTValues.EV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:ev_cogwork_magicapacitor')
        .itemInputs('4x gtceu:luminized_titanium_plate', '2x cosmiccore:starstruck_halite_foil', '#gtceu:circuits/hv', '2x cosmiccore:gravglass_shards')
        .itemOutputs('4x cosmiccore:ev_cogwork_magicapacitor')
        .EUt(GTValues.V[GTValues.MV], 4)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:ev_machine_casing')
        .itemInputs('cosmiccore:ev_cogwork_magicapacitor', 'cosmiccore:ev_modular_frameworks', '3x cosmiccore:ev_cladding', 'cosmiccore:carbon_ethersteel_lattice')
        .itemOutputs('gtceu:ev_machine_casing')
        .inputFluids('144x gtceu:silicone_rubber')
        .EUt(GTValues.V[GTValues.LV], 1)
        .duration(100)

})
