ServerEvents.recipes(event => {
    const hvComponents = ['electric_motor', 'electric_pump', 'conveyor_module', 'electric_piston', 'robot_arm', 'sensor', 'emitter', 'field_generator', 'fluid_regulator', 'voltage_coil']
    const hvMaterialSwaps = [
        ['gtceu:stainless_steel_rod', 'cosmiccore:galvanized_ethersteel_rod'],
        ['gtceu:stainless_steel_plate', 'cosmiccore:galvanized_ethersteel_plate'],
        ['gtceu:small_stainless_steel_gear', 'cosmiccore:small_galvanized_ethersteel_gear'],
        ['gtceu:electrum_double_wire', 'gtceu:kanthal_quadruple_wire'],
        ['gtceu:gold_single_cable', 'gtceu:terrasteel_double_cable']
    ]
    hvComponents.forEach(component => {
        hvMaterialSwaps.forEach(([original, replacement]) => {
            event.replaceInput({ output: `gtceu:hv_${component}` }, original, replacement)
        })
    })
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:molten_luminized_titanium')
        .itemInputs('gtceu:titanium_dust', '3x cosmiccore:pale_steel_dust', '5x cosmiccore:lumium_dust')
        .outputFluids('1296x gtceu:molten_luminized_titanium')
        .circuit(4)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(400)
    event.recipes.gtceu.assembler('frontiers:hv_machine_hull')
        .itemInputs('gtceu:hv_machine_casing', '2x cosmiccore:tenbrium_foil', '2x gtceu:dark_steel_single_cable')
        .itemOutputs('gtceu:hv_machine_hull')
        .inputFluids('288x gtceu:polyvinyl_chloride')
        .EUt(GTValues.V[GTValues.HV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:hv_machine_casing')
        .itemInputs('cosmiccore:hv_cogwork_magicapacitor', 'cosmiccore:hv_modular_frameworks', '3x cosmiccore:hv_cladding', '2x cosmiccore:terraweave_cloth')
        .itemOutputs('gtceu:hv_machine_casing')
        .inputFluids('144x gtceu:rubber')
        .circuit(6)
        .EUt(GTValues.V[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.electrolyzer('frontiers:carbon_dust_fluorine_source')
        .itemInputs('cognition:fluorescent_jelly')
        .itemOutputs('gtceu:carbon_dust')
        .outputFluids('2000x gtceu:fluorine')
        .outputFluids('1000x gtceu:oxygen')
        .outputFluids('4000x gtceu:hydrogen')
        .EUt(GTValues.VA[GTValues.HV], 4)
        .duration(850)
    event.recipes.cosmiccore.bio_lab('frontiers:fluorescent_jelly')
        .itemInputs('2x cosmiccore:red_algae', '2x undergarden:glitterkelp', '2x minecraft:kelp')
        .itemOutputs('8x cognition:fluorescent_jelly')
        .EUt(GTValues.VA[GTValues.MV], 2)
        .duration(320)
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:molten_luminized_titanium')
        .itemInputs('gtceu:titanium_dust', '3x cosmiccore:pale_steel_dust', '5x cosmiccore:lumium_dust')
        .inputFluids('1000x gtceu:nitrogen')
        .outputFluids('1296x gtceu:molten_luminized_titanium')
        .circuit(14)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(400)
    event.recipes.gtceu.distillation_tower('frontiers:potent_mana')
        .inputFluids('1000x cosmiccore:biomana_slurry')
        .outputFluids('1000x gtceu:potent_mana')
        .outputFluids('1000x gtceu:somatic_mana')
        .outputFluids('1000x cosmiccore:prisma')
        .EUt(GTValues.VA[GTValues.HV], 4)
        .duration(600)
    //This recipe might be too strong, it does remove the uh, need for alumina so that's fine ig, living flesh imitation flesh automation go brrt ig.
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:kuvite')
        .itemInputs('malum:imitation_flesh', '4x cosmiccore:bloomwyrm_algae', 'malum:living_flesh', '4x cosmiccore:nostium_dust')
        .inputFluids('4000x neovitae:essentia_vitae_source')
        .outputFluids('576x cosmiccore:kuvite')
        .circuit(24)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(600)
    event.recipes.gtceu.mixer('frontiers:lumium_dust')
        .itemInputs('4x minecraft:glowstone_dust', 'gtceu:blue_alloy_dust')
        .itemOutputs('4x cosmiccore:lumium_dust')
        .circuit(4)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .duration(550)
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:chrysanthium/abk')
        .itemInputs('16x cosmiccore:bloomwyrm_algae', '8x gtceu:nether_quartz_dust', '4x gtceu:gold_dust', '4x cosmiccore:utherium_dust', '8x malum:sacred_spirit', '4x malum:arcane_spirit')
        .outputFluids('2304x gtceu:chrysanthium')
        .circuit(24)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(900)
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:galvanized_ethersteel/abk')
        .itemInputs('16x cosmiccore:kuvite_dust', '8x gtceu:terrasteel_dust', '20x gtceu:sterling_silver_dust')
        .outputFluids('4608x cosmiccore:galvanized_ethersteel')
        .EUt(GTValues.VA[GTValues.HV], 4)
        .circuit(24)
        .blastFurnaceTemp(3600)
        .duration(900)
    event.replaceInput({ output: 'gtceu:hv_electric_motor' }, 'gtceu:silver_double_cable', 'gtceu:cupronickel_double_cable')

    event.recipes.gtceu.mixer('frontiers:inert_cinder_gas/from_light_naphtha')
        .itemInputs('embers:ember_grit')
        .inputFluids('750x gtceu:light_naphtha')
        .inputFluids('250x gtceu:steam')
        .outputFluids('1000x gtceu:inert_cinder_gas')
        .duration(40)
        .EUt(GTValues.V[GTValues.LV], 1)

    event.recipes.gtceu.assembler('frontiers:lv_modular_frameworks')
        .itemInputs('4x gtceu:steel_rod', '2x gtceu:tempered_iesnium_bolt', 'gtceu:small_steel_gear')
        .itemOutputs('4x cosmiccore:lv_modular_frameworks')
        .inputFluids('250x gtceu:concrete')
        .EUt(GTValues.V[GTValues.HV], 4)
        .duration(350)

    event.recipes.gtceu.assembler('frontiers:lv_cogwork_magicapacitor')
        .itemInputs('4x gtceu:steel_plate', '2x gtceu:tempered_iesnium_foil', 'cosmiccore:overloaded_pearls')
        .itemOutputs('5x cosmiccore:lv_cogwork_magicapacitor')
        .inputFluids('250x gtceu:dark_steel')
        .EUt(GTValues.V[GTValues.HV], 4)
        .duration(250)
    event.recipes.gtceu.cutter('frontiers:otherworldy_silicon_wafer')
        .itemInputs('cosmiccore:otherworldy_silicon_boule')
        .itemOutputs('16x cosmiccore:otherworldy_silicon_wafer')
        .EUt(GTValues.VA[GTValues.MV], 4)
        .duration(200)
    event.recipes.gtceu.forming_press('frontiers:lv_cladding')
        .itemInputs('gtceu:treated_wood_dust', 'gtceu:rubber_ingot', 'gtceu:lead_bolt')
        .itemOutputs('3x cosmiccore:lv_cladding')
        .EUt(GTValues.V[GTValues.HV], 2)
        .duration(200)
    event.shaped('merequester:requester', ['ABA', 'BCB', 'DAD'], { A: 'cosmiccore:hv_capacitor_battery', B: 'gtceu:hv_assembler', C: 'gtceu:hv_hermetic_casing', D: '#gtceu:circuits/ev' })
    event.recipes.gtceu.assembler('frontiers:plascrete')
        .itemInputs('cosmiccore:energetic_aluminium_frame', '2x gtceu:polyethylene_plate', '2x gtceu:polyvinyl_chloride_plate', '2x gtceu:polytetrafluoroethylene_plate')
        .itemOutputs('gtceu:plascrete')
        .inputFluids('144x gtceu:concrete')
        .EUt(GTValues.VA[GTValues.MV], 2)
        .duration(100)
    event.recipes.gtceu.electric_blast_furnace('frontiers:otherworldy_silicon_boule')
        .itemInputs('16x occultism:burnt_otherstone', '64x gtceu:silicon_dust')
        .itemOutputs('cosmiccore:otherworldy_silicon_boule')
        .circuit(4)
        .EUt(GTValues.VA[GTValues.MV], 2)
        .blastFurnaceTemp(2700)
        .duration(5000)
    event.recipes.cosmiccore.laminator('frontiers:cleanroom_glass')
        .itemInputs('gtceu:plascrete', '4x gtceu:steel_bolt')
        .itemOutputs('gtceu:cleanroom_glass')
        .inputFluids('144x gtceu:glass')
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:pattern_provider')
        .itemInputs('gtceu:hv_machine_hull', '4x gtceu:polytetrafluoroethylene_plate', '2x gtceu:platinum_foil', '2x gtceu:mv_robot_arm', '#gtceu:circuits/mv')
        .itemOutputs('4x ae2:pattern_provider')
        .EUt(GTValues.V[GTValues.HV], 4)
        .duration(300)
    event.recipes.gtceu.assembler('frontiers:me_pattern_buffer').itemInputs('gtceu:hv_machine_hull', '2x ae2:pattern_provider', '2x ae2:interface', 'gtceu:hv_robot_arm', 'gtceu:hv_electric_pump', '4x ae2:speed_card', '2x ae2:capacity_card', '#gtceu:circuits/hv').inputFluids('288x gtceu:soldering_alloy').itemOutputs('gtceu:me_pattern_buffer').duration(400).EUt(GTValues.V[GTValues.HV], 4)
    event.recipes.gtceu.assembler('frontiers:me_pattern_buffer_proxy').itemInputs('gtceu:hv_machine_hull', 'gtceu:hv_sensor', 'gtceu:hv_emitter', '2x ae2:fluix_pearl', '4x ae2:fluix_smart_cable', '#gtceu:circuits/hv').inputFluids('144x gtceu:soldering_alloy').itemOutputs('gtceu:me_pattern_buffer_proxy').duration(200).EUt(GTValues.V[GTValues.HV], 2)
    event.recipes.gtceu.assembler('frontiers:me_output_bus').itemInputs('gtceu:hv_output_bus', 'ae2:interface', '2x ae2:speed_card').itemOutputs('gtceu:me_output_bus').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.assembler('frontiers:me_output_hatch').itemInputs('gtceu:hv_output_hatch', 'ae2:interface', '2x ae2:speed_card').itemOutputs('gtceu:me_output_hatch').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.assembler('frontiers:me_stocking_input_bus').itemInputs('gtceu:hv_input_bus', 'ae2:interface', 'gtceu:hv_conveyor_module', 'gtceu:hv_sensor', '4x ae2:speed_card').itemOutputs('gtceu:me_stocking_input_bus').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.assembler('frontiers:me_stocking_input_hatch').itemInputs('gtceu:hv_input_hatch', 'ae2:interface', 'gtceu:hv_electric_pump', 'gtceu:hv_sensor', '4x ae2:speed_card').itemOutputs('gtceu:me_stocking_input_hatch').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.chemical_reactor('frontiers:vanadium_pentoxide_dust')
        .itemInputs('2x gtceu:vanadium_dust')
        .inputFluids('5000x gtceu:oxygen')
        .itemOutputs('7x gtceu:vanadium_pentoxide_dust')
        .duration(120)
        .EUt(GTValues.V[GTValues.HV], 2)
    event.recipes.cosmiccore.spooling_machine('frontiers:high_voltage_stator_housing')
        .itemInputs('4x gtceu:hv_voltage_coil', '16x gtceu:kanthal_double_wire')
        .itemOutputs('cosmiccore:high_voltage_stator_housing')
        .EUt(GTValues.V[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:pyroltic_contact_catalyst')
        .itemInputs('cosmiccore:utherium_ceramic_membrane', '7x gtceu:vanadium_pentoxide_dust')
        .itemOutputs('cosmiccore:pyroltic_contact_catalyst')
        .circuit(7)
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 4)
    event.recipes.gtceu.assembler('frontiers:lightweight_stainless_steel_casing')
        .itemInputs('gtceu:stainless_steel_frame', '6x gtceu:stainless_steel_foil', '2x gtceu:long_stainless_steel_rod')
        .itemOutputs('4x cosmiccore:lightweight_stainless_steel_casing')
        .circuit(6)
        .EUt(GTValues.V[GTValues.LV], 1)
        .duration(100)
    event.shaped('4x cosmiccore:lightweight_stainless_steel_casing', ['ABA', 'ACA', 'ABA'], { A: 'gtceu:stainless_steel_foil', B: 'gtceu:long_stainless_steel_rod', C: 'gtceu:stainless_steel_frame' })
    event.recipes.gtceu.assembler('frontiers:pyroltic_contact_catalyst/recovery')
        .itemInputs('cosmiccore:spent_pyroltic_contact_catalyst', 'gtceu:vanadium_pentoxide_dust')
        .itemOutputs('cosmiccore:pyroltic_contact_catalyst')
        .circuit(7)
        .duration(100)
        .EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.forming_press('frontiers:chalk_blue_impure')
        .itemInputs('occultism:chalk_white_impure', 'occultism:marid_essence', '4x gtceu:stainless_steel_dust', '4x cosmiccore:gloomarcine_dust')
        .itemOutputs('occultism:chalk_blue_impure')
        .EUt(GTValues.V[GTValues.MV], 2)
        .duration(100)
    event.recipes.gtceu.macerator('frontiers:pepper_powder')
        .itemInputs('mynethersdelight:bullet_pepper')
        .itemOutputs('4x mynethersdelight:pepper_powder')
        .EUt(GTValues.VA[GTValues.LV], 2)
        .duration(50)
    event.shaped('gtceu:hv_machine_hull', ['ABA', 'CDC', 'AEA'], { A: 'cosmiccore:tenbrium_foil', B: 'gtceu:sterling_silver_plate', C: 'gtceu:dark_steel_single_cable', D: 'gtceu:hv_machine_casing', E: 'gtceu:small_terrasteel_spring' })
    event.shaped('gtceu:hv_machine_casing', ['ABA', 'CDC', 'ACA'], { A: 'cosmiccore:terraweave_cloth', B: 'cosmiccore:hv_cogwork_magicapacitor', C: 'cosmiccore:hv_cladding', D: 'cosmiccore:hv_modular_frameworks' })
    event.shaped('cosmiccore:large_roaster', ['ABA', 'CDC', 'EFE'], { A: 'gtceu:heatproof_machine_casing', B: 'gtceu:hv_electric_pump', C: 'gtceu:black_steel_frame', D: 'gtceu:hv_machine_hull', E: '#gtceu:circuits/hv', F: 'gtceu:hv_electric_motor' })
    event.shaped('2x cosmiccore:hv_cladding', ['ABA', 'BCB', 'ABA'], { A: 'cosmiccore:galvanized_ethersteel_bolt', B: 'gtceu:polyvinyl_chloride_foil', C: 'gtceu:double_andesite_alloy_plate' })
    event.shaped('cosmiccore:hv_modular_frameworks', ['ABA', 'BCB', 'ABA'], { A: 'gtceu:sterling_silver_bolt', B: 'cosmiccore:galvanized_ethersteel_rod', C: 'cosmiccore:small_galvanized_ethersteel_gear' })
    event.shaped('cosmiccore:bloodsteel_kuvite_plating', ['ABA', 'ACA', 'ADA'], { A: 'cosmiccore:kuvite_plate', B: '#gtceu:crafting_tools/hammer', C: 'cosmiccore:kuvite_frame', D: '#gtceu:crafting_tools/wrench' })
    event.recipes.gtceu.assembler('frontiers:bloodsteel_kuvite_plating')
        .itemInputs('6x cosmiccore:kuvite_plate', 'cosmiccore:kuvite_frame')
        .itemOutputs('cosmiccore:bloodsteel_kuvite_plating')
        .circuit(6)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:biomana_reflective_tenbrium_casing')
        .itemInputs('gtceu:titanium_frame', '3x cosmiccore:nostium_plate', '3x cosmiccore:tenbrium_plate')
        .itemOutputs('cosmiccore:biomana_reflective_tenbrium_casing')
        .circuit(6)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:pale_rose_structural_casing')
        .itemInputs('gtceu:stainless_steel_frame', '3x cosmiccore:pale_steel_plate', '3x gtceu:rose_gold_plate')
        .itemOutputs('cosmiccore:pale_rose_structural_casing')
        .circuit(6)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:verdigris_nostium_casing')
        .itemInputs('cosmiccore:nostium_frame', '6x cosmiccore:nostium_plate')
        .itemOutputs('cosmiccore:verdigris_nostium_casing')
        .circuit(6)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_utherite')
        .itemInputs('16x cosmiccore:green_algae', '16x cosmiccore:bloomwyrm_algae')
        .notConsumableItem('gtceu:platinum_plate')
        .itemOutputs('16x cosmiccore:raw_utherite')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(1)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)

    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_vanachrome')
        .itemInputs('16x cosmiccore:blue_algae', '16x cosmiccore:bloomwyrm_algae', '4x malum:blighted_gunk')
        .notConsumableItem('gtceu:platinum_plate')
        .itemOutputs('16x cosmiccore:raw_vanachrome')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(2)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)

    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_phycolite')
        .itemInputs('8x cosmiccore:red_algae', '16x cosmiccore:bloomwyrm_algae', '4x malum:blighted_gunk')
        .notConsumableItem('gtceu:titanium_plate')
        .itemOutputs('16x cosmiccore:raw_phycolite')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(1)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)

    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_agarlite')
        .itemInputs('8x cosmiccore:red_algae', '16x cosmiccore:bloomwyrm_algae', '4x malum:blighted_gunk')
        .notConsumableItem('gtceu:titanium_plate')
        .itemOutputs('16x cosmiccore:raw_agarlite')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(2)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)

    event.recipes.gtceu.assembler('frontiers:drone_frame_1')
        .itemInputs('gtceu:lv_electric_motor', '4x gtceu:long_steel_rod', '4x gtceu:steel_plate')
        .itemOutputs('8x cosmiccore:drone_frame_1')
        .EUt(GTValues.VA[GTValues.LV], 2)
        .duration(100)

    event.recipes.gtceu.assembler('frontiers:drone_frame_2')
        .itemInputs('gtceu:mv_electric_motor', '4x cosmiccore:long_energetic_aluminium_rod', '4x cosmiccore:energetic_aluminium_plate')
        .itemOutputs('8x cosmiccore:drone_frame_2')
        .EUt(GTValues.VA[GTValues.MV], 2)
        .duration(100)

    event.recipes.gtceu.assembler('frontiers:drone_frame_3')
        .itemInputs('gtceu:hv_electric_motor', '4x cosmiccore:long_galvanized_ethersteel_rod', '4x cosmiccore:galvanized_ethersteel_plate')
        .itemOutputs('8x cosmiccore:drone_frame_3')
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(100)

    event.recipes.gtceu.assembler('frontiers:rusty_drone')
        .itemInputs('cosmiccore:drone_frame_1', 'simulated:gyroscopic_mechanism', '2x gtceu:duct_tape', 'gtceu:power_thruster')
        .itemOutputs('8x cosmiccore:rusty_drone')
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)

    event.recipes.gtceu.assembler('frontiers:robust_drone')
        .itemInputs('cosmiccore:drone_frame_2', 'simulated:gyroscopic_mechanism', '4x gtceu:duct_tape', 'gtceu:power_thruster')
        .itemOutputs('8x cosmiccore:robust_drone')
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)

    event.recipes.gtceu.assembler('frontiers:industrial_drone')
        .itemInputs('cosmiccore:drone_frame_2', 'simulated:gyroscopic_mechanism', '8x gtceu:duct_tape', 'gtceu:advanced_power_thruster')
        .itemOutputs('8x cosmiccore:industrial_drone')
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:hv_me_computation_core')
        .itemInputs('cosmiccore:me_computation_bay_casing', '16x #gtceu:circuits/hv')
        .itemOutputs('cosmiccore:hv_me_computation_core')
        .EUt(GTValues.VA[GTValues.HV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:high_temperature_smelting_casing')
        .itemInputs('gtceu:hsla_steel_frame', '4x gtceu:long_hsla_steel_rod', '4x gtceu:double_hsla_steel_plate')
        .itemOutputs('gtceu:high_temperature_smelting_casing')
        .circuit(6)
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.shaped('cosmiccore:alloy_blasting_kiln', ['ABA', 'BCB', 'DDD'], { A: '#gtceu:circuits/ev', B: 'cosmiccore:double_pale_steel_plate', C: 'gtceu:primitive_blast_furnace', D: 'cosmiccore:refractory_structural_casing' })
    event.shaped('cosmiccore:conversion_complex', ['ABA', 'CDE', 'FGF'], { A: '#gtceu:circuits/ev', B: 'gtceu:hv_electric_piston', C: 'gtceu:hv_robot_arm', D: 'cosmiccore:lightweight_stainless_steel_casing', E: 'gtceu:hv_fluid_regulator', F: 'gtceu:kanthal_single_cable', G: 'cosmiccore:refractory_structural_casing' })
    event.shaped('cosmiccore:fractional_condenser', ['ABA', 'BCB', 'DDD'], { A: 'gtceu:micro_processor_assembly', B: 'cosmiccore:lightweight_stainless_steel_casing', C: 'gtceu:hv_fluid_regulator', D: 'cosmiccore:refractory_structural_casing' })
    event.shaped('cosmiccore:steam_cracking_furnace', ['ABA', 'ACA', 'DDD'], { A: 'gtceu:cupronickel_coil_block', B: '#gtceu:circuits/ev', C: 'cosmiccore:lightweight_stainless_steel_casing', D: 'cosmiccore:refractory_structural_casing' })
    event.shaped('cosmiccore:desalter', ['ABA', 'BCB', 'DDD'], { A: 'cosmiccore:lightweight_stainless_steel_casing', B: '#gtceu:circuits/hv', C: 'gtceu:hsla_steel_frame', D: 'cosmiccore:refractory_structural_casing' })
    event.shaped('cosmiccore:phase_separator', ['ABA', 'BCB', 'BDB'], { A: 'cosmiccore:lightweight_stainless_steel_casing', B: 'cosmiccore:refractory_structural_casing', C: 'gtceu:hsla_steel_frame', D: '#gtceu:circuits/hv' })


    event.shaped('cosmiccore:hephaestus_cauldron', ['ABA', 'ACA', 'DDD'], { A: 'cosmiccore:double_pale_steel_plate', B: '#gtceu:circuits/ev', C: 'cosmiccore:alloy_blasting_kiln', D: 'gtceu:high_temperature_smelting_casing' })
    event.shapeless('cosmiccore:crafting_parallel_core', ['ae2:crafting_unit', '#gtceu:circuits/hv'])
    event.shapeless('cosmiccore:crafting_acceleration_core', ['ae2:crafting_unit', '#gtceu:circuits/hv'])
    event.shaped('cosmiccore:firmament_permit', ['ABA', 'BCB', 'ABA'], { A: 'gtceu:mv_sensor', B: '#gtceu:circuits/hv', C: 'cosmiccore:nether_permit' })
    event.shapeless('cosmiccore:hv_me_power_relay', ['cosmiccore:me_computation_bay_casing', 'gtceu:hv_diode'])
    event.shapeless('cosmiccore:leyline_me_hatch', ['ae2:pattern_provider', 'cosmiccore:lv_wildfire_core', 'gtceu:hv_machine_hull'])
    event.shaped('cosmiccore:leyline_compressor', ['ABA', 'CDC', 'AEA'], { A: '#gtceu:circuits/ev', B: 'occultism:research_fragment_dust', C: 'occultism:witherite_dust', D: 'gtceu:hv_compressor', E: 'ars_nouveau:arcane_core' })
    event.shaped('cosmiccore:superheavy_steel_casing', ['ABA', 'BCB', 'ABA'], { A: 'gtceu:long_steel_rod', B: 'gtceu:dense_steel_plate', C: 'gtceu:solid_machine_casing' })
    event.recipes.ars_nouveau.enchanting_apparatus(['#gtceu:circuits/ev', '#gtceu:circuits/ev', '#gtceu:circuits/ev', '#gtceu:circuits/ev', 'occultism:research_fragment_dust', 'occultism:spirit_attuned_gem', 'occultism:otherstone_tablet', 'occultism:otherstone_tablet'], ['ars_nouveau:enchanters_gauntlet'], 'cosmiccore:leyline_orrery', 0, true)
    event.shaped('cosmiccore:mechanical_mineshaft', ['ABA', 'CDC', 'EFE'], { A: 'neovitae:tabula_robur', B: 'occultism:magic_lamp_empty', C: 'occultism:otherrock_frame', D: 'cosmiccore:ore_extraction_drill_lv', E: 'cosmiccore:omnia_circuit_ev', F: 'gtceu:titanium_drill_head' })
    event.shaped('cosmiccore:mechanical_mineshaft', ['ABA', 'BCB', 'DED'], { A: 'gtceu:hv_sensor', B: 'minecraft:beehive', C: 'gtceu:stainless_steel_frame', D: '#gtceu:circuits/ev', E: 'gtceu:hv_machine_hull' })
    event.shaped('cosmiccore:essence_reactor', ['ABA', 'CDE', 'FGF'], { A: 'cosmiccore:lv_wildfire_core', B: 'neovitae:melee_anointment', C: 'neovitae:hidden_knowledge_anointment', D: 'neovitae:tabula_vitae', E: 'neovitae:voiding_anointment', F: 'cosmiccore:omnia_circuit_hv', G: 'gtceu:hv_machine_hull' })
    event.shaped('cosmiccore:drone_maintenance_interface', ['ABA', 'CDC', 'AEA'], { A: 'gtceu:stainless_steel_plate', B: 'gtceu:maintenance_hatch', C: 'gtceu:shutter_module_cover', D: 'gtceu:hv_machine_hull', E: 'cosmiccore:omnia_circuit_hv' })
    event.shapeless('cosmiccore:power_tower_me_output', ['#gtceu:crafting_tools/screwdriver', 'cosmiccore:power_tower_me_input'])
    event.shapeless('cosmiccore:power_tower_me_input', ['#gtceu:crafting_tools/screwdriver', 'cosmiccore:power_tower_me_output'])
    event.shaped('cosmiccore:power_tower_me_input', ['A', 'B'], { A: 'ae2:me_p2p_tunnel', B: 'gtceu:hv_machine_hull' })
    event.shaped('cosmiccore:power_tower_me_output', ['A', 'B'], { A: 'gtceu:hv_machine_hull', B: 'ae2:me_p2p_tunnel' })
    event.shaped('cosmiccore:bolted_heavy_frame_casing', ['ABA', 'ACA', 'ABA'], { A: 'gtceu:steel_bolt', B: 'gtceu:dark_steel_foil', C: 'gtceu:solid_machine_casing' })
    event.shaped('cosmiccore:manawomb_leeching_pond', ['ABA', 'CDC', 'ACA'], { A: '#gtceu:circuits/ev', B: 'cosmiccore:large_arcanite_cluster', C: 'gtceu:double_titanium_plate', D: 'cosmiccore:superheavy_steel_casing' })















})
