ServerEvents.recipes(event => {
    const hvComponents = ['electric_motor', 'electric_pump', 'conveyor_module', 'electric_piston', 'robot_arm', 'sensor', 'emitter', 'field_generator', 'fluid_regulator', 'voltage_coil']
    const hvMaterialSwaps = [
        ['gtceu:stainless_steel_rod', 'cosmiccore:galvanized_ethersteel_rod'],
        ['gtceu:stainless_steel_plate', 'cosmiccore:galvanized_ethersteel_plate'],
        ['gtceu:small_stainless_steel_gear', 'cosmiccore:small_galvanized_ethersteel_gear'],
        ['gtceu:electrum_double_wire', 'gtceu:kanthal_quadruple_wire'],
        ['gtceu:gold_single_cable', 'gtceu:terrasteel_double_cable']
    ]
    hvComponents.forEach(component => {
        hvMaterialSwaps.forEach(([original, replacement]) => {
            event.replaceInput({ output: `gtceu:hv_${component}` }, original, replacement)
        })
    })
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:molten_luminized_titanium')
        .itemInputs('gtceu:titanium_dust', '3x cosmiccore:pale_steel_dust', '5x cosmiccore:lumium_dust')
        .outputFluids('1296x gtceu:molten_luminized_titanium')
        .circuit(4)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(400)
    event.recipes.gtceu.assembler('frontiers:hv_machine_hull')
        .itemInputs('gtceu:hv_machine_casing', '2x cosmiccore:tenbrium_foil', '2x gtceu:dark_steel_single_cable')
        .itemOutputs('gtceu:hv_machine_hull')
        .inputFluids('288x gtceu:polyvinyl_chloride')
        .EUt(GTValues.V[GTValues.HV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:hv_machine_casing')
        .itemInputs('cosmiccore:hv_cogwork_magicapacitor', 'cosmiccore:hv_modular_frameworks', '3x cosmiccore:hv_cladding', '2x cosmiccore:terraweave_cloth')
        .itemOutputs('gtceu:hv_machine_casing')
        .inputFluids('144x gtceu:rubber')
        .circuit(6)
        .EUt(GTValues.V[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.electrolyzer('frontiers:carbon_dust_fluorine_source')
        .itemInputs('cognition:fluorescent_jelly')
        .itemOutputs('gtceu:carbon_dust')
        .outputFluids('2000x gtceu:fluorine')
        .outputFluids('1000x gtceu:oxygen')
        .outputFluids('4000x gtceu:hydrogen')
        .EUt(GTValues.VA[GTValues.HV], 4)
        .duration(850)
    event.recipes.cosmiccore.bio_lab('frontiers:fluorescent_jelly')
        .itemInputs('2x cosmiccore:red_algae', '2x undergarden:glitterkelp', '2x minecraft:kelp')
        .itemOutputs('8x cognition:fluorescent_jelly')
        .EUt(GTValues.VA[GTValues.MV], 2)
        .duration(320)
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:molten_luminized_titanium')
        .itemInputs('gtceu:titanium_dust', '3x cosmiccore:pale_steel_dust', '5x cosmiccore:lumium_dust')
        .inputFluids('1000x gtceu:nitrogen')
        .outputFluids('1296x gtceu:molten_luminized_titanium')
        .circuit(14)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(400)
    event.recipes.gtceu.distillation_tower('frontiers:potent_mana')
        .inputFluids('1000x cosmiccore:biomana_slurry')
        .outputFluids('1000x gtceu:potent_mana')
        .outputFluids('1000x gtceu:somatic_mana')
        .outputFluids('1000x cosmiccore:prisma')
        .EUt(GTValues.VA[GTValues.HV], 4)
        .duration(600)
    //This recipe might be too strong, it does remove the uh, need for alumina so that's fine ig, living flesh imitation flesh automation go brrt ig.
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:kuvite')
        .itemInputs('malum:imitation_flesh', '4x cosmiccore:bloomwyrm_algae', 'malum:living_flesh', '4x cosmiccore:nostium_dust')
        .inputFluids('4000x neovitae:essentia_vitae_source')
        .outputFluids('576x cosmiccore:kuvite')
        .circuit(24)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(600)
    event.recipes.gtceu.mixer('frontiers:lumium_dust')
        .itemInputs('4x minecraft:glowstone_dust', 'gtceu:blue_alloy_dust')
        .itemOutputs('4x cosmiccore:lumium_dust')
        .circuit(4)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .duration(550)
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:chrysanthium/abk')
        .itemInputs('16x cosmiccore:bloomwyrm_algae', '8x gtceu:nether_quartz_dust', '4x gtceu:gold_dust', '4x cosmiccore:utherium_dust', '8x malum:sacred_spirit', '4x malum:arcane_spirit')
        .outputFluids('2304x gtceu:chrysanthium')
        .circuit(24)
        .EUt(GTValues.VA[GTValues.HV], 4)
        .blastFurnaceTemp(3600)
        .duration(900)
    event.recipes.cosmiccore.alloy_blasting_kiln('frontiers:galvanized_ethersteel/abk')
        .itemInputs('16x cosmiccore:kuvite_dust', '8x gtceu:terrasteel_dust', '20x gtceu:sterling_silver_dust')
        .outputFluids('4608x cosmiccore:galvanized_ethersteel')
        .EUt(GTValues.VA[GTValues.HV], 4)
        .circuit(24)
        .blastFurnaceTemp(3600)
        .duration(900)
    event.replaceInput({ output: 'gtceu:hv_electric_motor' }, 'gtceu:silver_double_cable', 'gtceu:cupronickel_double_cable')

    event.recipes.gtceu.mixer('frontiers:inert_cinder_gas/from_light_naphtha')
        .itemInputs('embers:ember_grit')
        .inputFluids('750x gtceu:light_naphtha')
        .inputFluids('250x gtceu:steam')
        .outputFluids('1000x gtceu:inert_cinder_gas')
        .duration(40)
        .EUt(GTValues.V[GTValues.LV], 1)

    event.recipes.gtceu.assembler('frontiers:lv_modular_frameworks')
        .itemInputs('4x gtceu:steel_rod', '2x gtceu:tempered_iesnium_bolt', 'gtceu:small_steel_gear')
        .itemOutputs('4x cosmiccore:lv_modular_frameworks')
        .inputFluids('250x gtceu:concrete')
        .EUt(GTValues.V[GTValues.HV], 4)
        .duration(350)

    event.recipes.gtceu.assembler('frontiers:lv_cogwork_magicapacitor')
        .itemInputs('4x gtceu:steel_plate', '2x gtceu:tempered_iesnium_foil', 'cosmiccore:overloaded_pearls')
        .itemOutputs('5x cosmiccore:lv_cogwork_magicapacitor')
        .inputFluids('250x gtceu:dark_steel')
        .EUt(GTValues.V[GTValues.HV], 4)
        .duration(250)
    event.recipes.gtceu.cutter('frontiers:otherworldy_silicon_wafer')
        .itemInputs('cosmiccore:otherworldy_silicon_boule')
        .itemOutputs('16x cosmiccore:otherworldy_silicon_wafer')
        .EUt(GTValues.VA[GTValues.MV], 4)
        .duration(200)
    event.recipes.gtceu.forming_press('frontiers:lv_cladding')
        .itemInputs('gtceu:treated_wood_dust', 'gtceu:rubber_ingot', 'gtceu:lead_bolt')
        .itemOutputs('3x cosmiccore:lv_cladding')
        .EUt(GTValues.V[GTValues.HV], 2)
        .duration(200)
    event.shaped('merequester:requester', ['ABA', 'BCB', 'DAD'], { A: 'cosmiccore:hv_capacitor_battery', B: 'gtceu:hv_assembler', C: 'gtceu:hv_hermetic_casing', D: '#gtceu:circuits/ev' })
    event.recipes.gtceu.assembler('frontiers:plascrete')
        .itemInputs('cosmiccore:energetic_aluminium_frame', '2x gtceu:polyethylene_plate', '2x gtceu:polyvinyl_chloride_plate', '2x gtceu:polytetrafluoroethylene_plate')
        .itemOutputs('gtceu:plascrete')
        .inputFluids('144x gtceu:concrete')
        .EUt(GTValues.VA[GTValues.MV], 2)
        .duration(100)
    event.recipes.gtceu.electric_blast_furnace('frontiers:otherworldy_silicon_boule')
        .itemInputs('16x occultism:burnt_otherstone', '64x gtceu:silicon_dust')
        .itemOutputs('cosmiccore:otherworldy_silicon_boule')
        .circuit(4)
        .EUt(GTValues.VA[GTValues.MV], 2)
        .blastFurnaceTemp(2700)
        .duration(5000)
    event.recipes.cosmiccore.laminator('frontiers:cleanroom_glass')
        .itemInputs('gtceu:plascrete', '4x gtceu:steel_bolt')
        .itemOutputs('gtceu:cleanroom_glass')
        .inputFluids('144x gtceu:glass')
        .EUt(GTValues.VA[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:pattern_provider')
        .itemInputs('gtceu:hv_machine_hull', '4x gtceu:polytetrafluoroethylene_plate', '2x gtceu:platinum_foil', '2x gtceu:mv_robot_arm', '#gtceu:circuits/mv')
        .itemOutputs('4x ae2:pattern_provider')
        .EUt(GTValues.V[GTValues.HV], 4)
        .duration(300)
    event.recipes.gtceu.assembler('frontiers:me_pattern_buffer').itemInputs('gtceu:hv_machine_hull', '2x ae2:pattern_provider', '2x ae2:interface', 'gtceu:hv_robot_arm', 'gtceu:hv_electric_pump', '4x ae2:speed_card', '2x ae2:capacity_card', '#gtceu:circuits/hv').inputFluids('288x gtceu:soldering_alloy').itemOutputs('gtceu:me_pattern_buffer').duration(400).EUt(GTValues.V[GTValues.HV], 4)
    event.recipes.gtceu.assembler('frontiers:me_pattern_buffer_proxy').itemInputs('gtceu:hv_machine_hull', 'gtceu:hv_sensor', 'gtceu:hv_emitter', '2x ae2:fluix_pearl', '4x ae2:fluix_smart_cable', '#gtceu:circuits/hv').inputFluids('144x gtceu:soldering_alloy').itemOutputs('gtceu:me_pattern_buffer_proxy').duration(200).EUt(GTValues.V[GTValues.HV], 2)
    event.recipes.gtceu.assembler('frontiers:me_output_bus').itemInputs('gtceu:hv_output_bus', 'ae2:interface', '2x ae2:speed_card').itemOutputs('gtceu:me_output_bus').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.assembler('frontiers:me_output_hatch').itemInputs('gtceu:hv_output_hatch', 'ae2:interface', '2x ae2:speed_card').itemOutputs('gtceu:me_output_hatch').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.assembler('frontiers:me_stocking_input_bus').itemInputs('gtceu:hv_input_bus', 'ae2:interface', 'gtceu:hv_conveyor_module', 'gtceu:hv_sensor', '4x ae2:speed_card').itemOutputs('gtceu:me_stocking_input_bus').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.assembler('frontiers:me_stocking_input_hatch').itemInputs('gtceu:hv_input_hatch', 'ae2:interface', 'gtceu:hv_electric_pump', 'gtceu:hv_sensor', '4x ae2:speed_card').itemOutputs('gtceu:me_stocking_input_hatch').duration(300).EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.chemical_reactor('frontiers:vanadium_pentoxide_dust')
        .itemInputs('2x gtceu:vanadium_dust')
        .inputFluids('5000x gtceu:oxygen')
        .itemOutputs('7x gtceu:vanadium_pentoxide_dust')
        .duration(120)
        .EUt(GTValues.V[GTValues.HV], 2)
    event.recipes.cosmiccore.spooling_machine('frontiers:high_voltage_stator_housing')
        .itemInputs('4x gtceu:hv_voltage_coil', '16x gtceu:kanthal_double_wire')
        .itemOutputs('cosmiccore:high_voltage_stator_housing')
        .EUt(GTValues.V[GTValues.LV], 1)
        .duration(100)
    event.recipes.gtceu.assembler('frontiers:pyroltic_contact_catalyst')
        .itemInputs('cosmiccore:utherium_ceramic_membrane', '7x gtceu:vanadium_pentoxide_dust')
        .itemOutputs('cosmiccore:pyroltic_contact_catalyst')
        .circuit(7)
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 4)
    event.recipes.gtceu.assembler('frontiers:lightweight_stainless_steel_casing')
        .itemInputs('gtceu:stainless_steel_frame', '6x gtceu:stainless_steel_foil', '2x gtceu:long_stainless_steel_rod')
        .itemOutputs('4x cosmiccore:lightweight_stainless_steel_casing')
        .circuit(6)
        .EUt(GTValues.V[GTValues.LV], 1)
        .duration(100)
    event.shaped('4x cosmiccore:lightweight_stainless_steel_casing', ['ABA', 'ACA', 'ABA'], { A: 'gtceu:stainless_steel_foil', B: 'gtceu:long_stainless_steel_rod', C: 'gtceu:stainless_steel_frame' })
    event.recipes.gtceu.assembler('frontiers:pyroltic_contact_catalyst/recovery')
        .itemInputs('cosmiccore:spent_pyroltic_contact_catalyst', 'gtceu:vanadium_pentoxide_dust')
        .itemOutputs('cosmiccore:pyroltic_contact_catalyst')
        .circuit(7)
        .duration(100)
        .EUt(GTValues.V[GTValues.HV], 1)
    event.recipes.gtceu.forming_press('frontiers:chalk_blue_impure')
        .itemInputs('occultism:chalk_white_impure', 'occultism:marid_essence', '4x gtceu:stainless_steel_dust', '4x cosmiccore:gloomarcine_dust')
        .itemOutputs('occultism:chalk_blue_impure')
        .EUt(GTValues.V[GTValues.MV], 2)
        .duration(100)
    event.recipes.gtceu.macerator('frontiers:pepper_powder')
        .itemInputs('mynethersdelight:bullet_pepper')
        .itemOutputs('4x mynethersdelight:pepper_powder')
        .EUt(GTValues.VA[GTValues.LV], 2)
        .duration(50)
    event.shaped('gtceu:hv_machine_hull', ['ABA', 'CDC', 'AEA'], { A: 'cosmiccore:tenbrium_foil', B: 'gtceu:sterling_silver_plate', C: 'gtceu:dark_steel_single_cable', D: 'gtceu:hv_machine_casing', E: 'gtceu:small_terrasteel_spring' })
    event.shaped('gtceu:hv_machine_casing', ['ABA', 'CDC', 'ACA'], { A: 'cosmiccore:terraweave_cloth', B: 'cosmiccore:hv_cogwork_magicapacitor', C: 'cosmiccore:hv_cladding', D: 'cosmiccore:hv_modular_frameworks' })
    event.shaped('cosmiccore:large_roaster', ['ABA', 'CDC', 'EFE'], { A: 'gtceu:heatproof_machine_casing', B: 'gtceu:hv_electric_pump', C: 'gtceu:black_steel_frame', D: 'gtceu:hv_machine_hull', E: '#gtceu:circuits/hv', F: 'gtceu:hv_electric_motor' })
    event.shaped('2x cosmiccore:hv_cladding', ['ABA', 'BCB', 'ABA'], { A: 'cosmiccore:galvanized_ethersteel_bolt', B: 'gtceu:polyvinyl_chloride_foil', C: 'gtceu:double_andesite_alloy_plate' })
    event.shaped('cosmiccore:hv_modular_frameworks', ['ABA', 'BCB', 'ABA'], { A: 'gtceu:sterling_silver_bolt', B: 'cosmiccore:galvanized_ethersteel_rod', C: 'cosmiccore:small_galvanized_ethersteel_gear' })

    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_utherite')
        .itemInputs('16x cosmiccore:green_algae', '16x cosmiccore:bloomwyrm_algae')
        .notConsumableItem('gtceu:platinum_plate')
        .itemOutputs('16x cosmiccore:raw_utherite')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(1)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)

    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_vanachrome')
        .itemInputs('16x cosmiccore:blue_algae', '16x cosmiccore:bloomwyrm_algae','4x malum:blighted_gunk')
        .notConsumableItem('gtceu:platinum_plate')
        .itemOutputs('16x cosmiccore:raw_vanachrome')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(2)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)

    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_phycolite')
        .itemInputs('8x cosmiccore:red_algae', '16x cosmiccore:bloomwyrm_algae','4x malum:blighted_gunk')
        .notConsumableItem('gtceu:titanium_plate')
        .itemOutputs('16x cosmiccore:raw_phycolite')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(1)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)

    event.recipes.cosmiccore.manawomb_leeching_pond('frontiers:raw_agarlite')
        .itemInputs('8x cosmiccore:red_algae', '16x cosmiccore:bloomwyrm_algae','4x malum:blighted_gunk')
        .notConsumableItem('gtceu:titanium_plate')
        .itemOutputs('16x cosmiccore:raw_agarlite')
        .inputFluids('8000x cosmiccore:biomeld_nutrient')
        .circuit(2)
        .biopowerInput(4)
        .EUt(GTValues.VA[GTValues.HV], 2)
        .duration(400)





})
