GTCEuStartupEvents.registry('gtceu:element', event => {

    event.create('roasted_cooperite')
    .protons(78)
    .neutrons(78)
    .symbol('Pt₃PdNi')

    event.create('nickel_depleted_cooperite')
    .protons(78)
    .neutrons(78)
    .symbol('Pt₃Pd') 

    event.create('nickel_carbonyl')
    .protons(78)
    .neutrons(78)
    .symbol('Ni(CO)₄') 

    event.create('cooperite_solution')
    .protons(78)
    .neutrons(78)
    .symbol('(3H₂PtCl₆)(H₂PdCl₄)(14H₂O)') 

    event.create('plat_depleted_cooperite_solution')
    .protons(78)
    .neutrons(78)
    .symbol('(H₂PdCl₄)(H₂O)') 

    event.create('ammonium_hexachloroplatinate')
    .protons(78)
    .neutrons(78)
    .symbol('(NH₄)₂PtCl₆') 

    event.create('ammonium_hexachloropalladate')
    .protons(78)
    .neutrons(78)
    .symbol('(NH₄)₂PdCl₆')
    event.create('tetraammine_palladium_chloride')
    .protons(78)
    .neutrons(78)
    .symbol('Pd(NH₃)₄Cl₂') 
    event.create('diamine_dichloropalladium')
    .protons(78)
    .neutrons(78)
    .symbol('Pd(NH₃)2Cl₂') 
    event.create('insoluble_plat_group_residue')
    .protons(78)
    .neutrons(78)
    .symbol('(RhRuOsIr)') 
    //subsript (copy and paste) ₂₃₄₅₆₇₈₉₀
 })