

ServerEvents.recipes(event => {
    event.recipes.gtceu.void_miner(`voidmap_earth`)
        .circuit(1)
        .perTick(true)
        .inputFluids('gtceu:pyroflux 100')
        .inputFluids('gtceu:drilling_fluid 150')
        .perTick(false)
        .dimension('minecraft:overworld')
        .itemOutputsRanged('gtceu:raw_nickel', 1, 3)
        .itemOutputsRanged('gtceu:raw_graphite', 1, 3)
        .itemOutputsRanged('gtceu:raw_diamond', 1, 3)
        .itemOutputsRanged('gtceu:raw_coal', 1, 3)
        .itemOutputsRanged('gtceu:raw_redstone', 1, 3)
        .itemOutputsRanged('gtceu:raw_lapis', 1, 3)
        .itemOutputsRanged('minecraft:raw_gold', 1, 3)
        .itemOutputsRanged('minecraft:raw_copper', 1, 3)
        .itemOutputsRanged('minecraft:raw_iron', 1, 3)
        .itemOutputsRanged('gtceu:raw_cassiterite', 1, 3)
        .itemOutputsRanged('gtceu:raw_gypsum', 1, 3)
        .itemOutputsRanged('gtceu:raw_green_sapphire', 1, 3)
        .itemOutputsRanged('gtceu:raw_realgar', 1, 3)
        .itemOutputsRanged('gtceu:raw_chromite', 1, 3)
        .itemOutputsRanged('gtceu:raw_cobaltite', 1, 3)
        .itemOutputsRanged('gtceu:raw_rock_salt', 1, 3)
        .itemOutputsRanged('gtceu:raw_salt', 1, 3)
        .itemOutputsRanged('gtceu:raw_lepidolite', 1, 3)
        .itemOutputsRanged('gtceu:raw_spodumene', 1, 3)
        .itemOutputsRanged('gtceu:raw_cinnabar', 1, 3)
        .itemOutputsRanged('gtceu:raw_sulfur', 1, 3)
        .itemOutputsRanged('gtceu:raw_apatite', 1, 3)
        .itemOutputsRanged('gtceu:raw_sapphire', 1, 3)
        .duration(80)
        .EUt(GTValues.VA[GTValues.ZPM], 4);
})
ServerEvents.recipes(event => {
    event.recipes.gtceu.void_miner(`voidmap_nether`)
        .circuit(2)
        .perTick(true)
        .inputFluids('gtceu:pyroflux 100')
        .inputFluids('gtceu:drilling_fluid 150')
        .perTick(false)
        .dimension('minecraft:the_nether')
        .itemOutputsRanged('gtceu:raw_saltpeter', 1, 3)
        .itemOutputsRanged('gtceu:raw_diatomite', 1, 3)
        .itemOutputsRanged('gtceu:raw_electrotine', 1, 3)
        .itemOutputsRanged('gtceu:raw_alunite', 1, 3)
        .itemOutputsRanged('gtceu:raw_beryllium', 1, 3)
        .itemOutputsRanged('gtceu:raw_emerald', 1, 3)
        .itemOutputsRanged('gtceu:raw_thorium', 1, 3)
        .itemOutputsRanged('gtceu:raw_grossular', 1, 3)
        .itemOutputsRanged('gtceu:raw_pyrolusite', 1, 3)
        .itemOutputsRanged('gtceu:raw_tantalite', 1, 3)
        .itemOutputsRanged('gtceu:raw_quartzite', 1, 3)
        .itemOutputsRanged('gtceu:raw_certus_quartz', 1, 3)
        .itemOutputsRanged('gtceu:raw_barite', 1, 3)
        .itemOutputsRanged('gtceu:raw_tetrahedrite', 1, 3)
        .itemOutputsRanged('gtceu:raw_stibnite', 1, 3)
        .itemOutputsRanged('gtceu:raw_goethite', 1, 3)
        .itemOutputsRanged('gtceu:raw_yellow_limonite', 1, 3)
        .itemOutputsRanged('gtceu:raw_hematite', 1, 3)
        .itemOutputsRanged('gtceu:raw_blue_topaz', 1, 3)
        .itemOutputsRanged('gtceu:raw_topaz', 1, 3)
        .itemOutputsRanged('gtceu:raw_chalcocite', 1, 3)
        .itemOutputsRanged('gtceu:raw_bornite', 1, 3)
        .itemOutputsRanged('gtceu:raw_nether_quartz', 1, 3)
        .itemOutputsRanged('gtceu:raw_pyrite', 1, 3)
        .itemOutputsRanged('gtceu:raw_sphalerite', 1, 3)
        .duration(80)
        .EUt(GTValues.VA[GTValues.ZPM], 4);
})
ServerEvents.recipes(event => {
    event.recipes.gtceu.void_miner(`voidmap_aether`)
        .circuit(3)
        .perTick(true)
        .inputFluids('gtceu:pyroflux 100')
        .inputFluids('gtceu:drilling_fluid 150')
        .perTick(false)
        .dimension('aether:the_aether')
        .itemOutputsRanged('gtceu:raw_ambrosium', 1, 3)
        .itemOutputsRanged('gtceu:raw_trona', 1, 3)
        .itemOutputsRanged('gtceu:raw_zanite', 1, 3)
        .itemOutputsRanged('gtceu:raw_bauxite', 1, 3)
        .itemOutputsRanged('gtceu:raw_alumina', 1, 3)
        .itemOutputsRanged('gtceu:raw_barite', 1, 3)
        .itemOutputsRanged('gtceu:raw_tetrahedrite', 1, 3)
        .itemOutputsRanged('apotheosis:common_material', 3, 6)
        .itemOutputsRanged('apotheosis:uncommon_material', 1, 3)
        .duration(80)
        .EUt(GTValues.VA[GTValues.ZPM], 4);


    event.recipes.gtceu.void_miner(`voidmap_undergarden`)
        .circuit(4)
        .perTick(true)
        .inputFluids('gtceu:pyroflux 100')
        .inputFluids('gtceu:drilling_fluid 150')
        .perTick(false)
        .dimension('undergarden:undergarden')
        .itemOutputsRanged('gtceu:raw_quartzite', 1, 3)
        .itemOutputsRanged('gtceu:raw_certus_quartz', 1, 3)
        .itemOutputsRanged('gtceu:raw_utherium', 1, 3)
        .itemOutputsRanged('gtceu:raw_almandine', 1, 3)
        .itemOutputsRanged('gtceu:raw_ruby', 1, 3)
        .itemOutputsRanged('gtceu:raw_chromite', 1, 3)
        .itemOutputsRanged('gtceu:raw_yellow_limonite', 1, 3)
        .itemOutputsRanged('minecraft:raw_gold', 1, 3)
        .itemOutputsRanged('gtceu:raw_alumina', 1, 3)
        .itemOutputsRanged('gtceu:raw_aluminium', 1, 3)
        .itemOutputsRanged('gtceu:raw_cooperite', 1, 3)
        .itemOutputsRanged('gtceu:raw_barite', 1, 3)
        .itemOutputsRanged('gtceu:raw_bornite', 1, 3)
        .itemOutputsRanged('gtceu:raw_tantalite', 1, 3)
        .itemOutputsRanged('gtceu:raw_hematite', 1, 3)
        .duration(80)
        .EUt(GTValues.VA[GTValues.ZPM], 4);

    event.recipes.gtceu.void_miner(`voidmap_moon`)
        .circuit(5)
        .perTick(true)
        .inputFluids('gtceu:pyroflux 100')
        .inputFluids('gtceu:drilling_fluid 150')
        .perTick(false)
        .dimension('ad_astra:moon')
        .itemOutputsRanged('minecraft:raw_copper', 1, 3)
        .itemOutputsRanged('gtceu:raw_stibnite', 1, 3)
        .itemOutputsRanged('gtceu:raw_tricalcium_phosphate', 1, 3)
        .itemOutputsRanged('gtceu:raw_malachite', 1, 3)
        .itemOutputsRanged('gtceu:raw_chromite', 1, 3)
        .itemOutputsRanged('gtceu:raw_hematite', 1, 3)
        .itemOutputsRanged('gtceu:raw_ilmenite', 1, 3)
        .itemOutputsRanged('gtceu:raw_bauxite', 1, 3)
        .itemOutputsRanged('gtceu:raw_uraninite', 1, 3)
        .itemOutputsRanged('gtceu:raw_cobaltite', 1, 3)
        .itemOutputsRanged('gtceu:raw_pitchblende', 1, 3)
        .itemOutputsRanged('gtceu:raw_desh', 1, 3)
        .itemOutputsRanged('gtceu:raw_apatite', 1, 3)
        .itemOutputsRanged('gtceu:raw_pyrochlore', 1, 3)
        .itemOutputsRanged('gtceu:raw_calcite', 1, 3)
        .itemOutputsRanged('gtceu:raw_grossular', 1, 3)
        .itemOutputsRanged('gtceu:raw_pyrolusite', 1, 3)
        .itemOutputsRanged('gtceu:raw_tantalite', 1, 3)
        .itemOutputsRanged('gtceu:raw_luminite', 1, 3)
        .itemOutputsRanged('gtceu:raw_wolframite', 1, 3)
        .itemOutputsRanged('gtceu:raw_scheelite', 1, 3)
        .itemOutputsRanged('gtceu:raw_tungstate', 1, 3)
        .itemOutputsRanged('gtceu:raw_lithium', 1, 3)
        .itemOutputsRanged('gtceu:raw_tetrahedrite', 1, 3)
        .duration(80)
        .EUt(GTValues.VA[GTValues.ZPM], 4);



    event.recipes.gtceu.void_miner(`voidmap_mars`)
        .circuit(6)
        .perTick(true)
        .inputFluids('gtceu:pyroflux 100')
        .inputFluids('gtceu:drilling_fluid 150')
        .perTick(false)
        .dimension('ad_astra:mars')
        .itemOutputsRanged('gtceu:raw_ilmenite', 1, 3)
        .itemOutputsRanged('gtceu:raw_bauxite', 1, 3)
        .itemOutputsRanged('gtceu:raw_naquadric_metallic_powder', 1, 3)
        .itemOutputsRanged('gtceu:raw_plutonium', 1, 3)
        .itemOutputsRanged('gtceu:raw_beryllium', 1, 3)
        .itemOutputsRanged('gtceu:raw_uranium', 1, 3)
        .itemOutputsRanged('gtceu:raw_uraninite', 1, 3)
        .itemOutputsRanged('gtceu:raw_electrotine', 1, 3)
        .itemOutputsRanged('gtceu:raw_cobaltite', 1, 3)
        .itemOutputsRanged('gtceu:raw_uranium', 1, 3)
        .duration(80)
        .EUt(GTValues.VA[GTValues.ZPM], 4);


    event.recipes.gtceu.void_miner(`voidmap_venus`)
        .circuit(7)
        .perTick(true)
        .inputFluids('gtceu:pyroflux 100')
        .inputFluids('gtceu:drilling_fluid 150')
        .perTick(false)
        .dimension('ad_astra:venus')
        .itemOutputsRanged('gtceu:raw_naumannite', 1, 3)
        .itemOutputsRanged('gtceu:raw_wulfenite', 1, 3)
        .itemOutputsRanged('gtceu:raw_lepidolite', 1, 3)
        .itemOutputsRanged('gtceu:raw_spodumene', 1, 3)
        .itemOutputsRanged('gtceu:raw_bismuthinite', 1, 3)
        .itemOutputsRanged('gtceu:raw_cassiterite_sand', 1, 3)
        .itemOutputsRanged('gtceu:raw_cinnabar', 1, 3)
        .itemOutputsRanged('gtceu:raw_luminite', 1, 3)
        .itemOutputsRanged('gtceu:raw_desh', 1, 3)
        .itemOutputsRanged('gtceu:raw_basaltic_mineral_sand', 1, 3)
        .itemOutputsRanged('gtceu:raw_apatite', 1, 3)
        .itemOutputsRanged('gtceu:raw_wolframite', 1, 3)
        .itemOutputsRanged('gtceu:raw_hadalite', 1, 3)
        .itemOutputsRanged('gtceu:raw_scheelite', 1, 3)
        .itemOutputsRanged('gtceu:raw_calcite', 1, 3)
        .itemOutputsRanged('gtceu:raw_uranium', 1, 3)
        .duration(80)
        .EUt(GTValues.VA[GTValues.ZPM], 4);



    //ATMO SIPHONS
      event.recipes.gtceu.atmo_siphon('atmo_overworld')
        .circuit(1)
        .outputFluids('gtceu:helium 100000')
        .outputFluids('gtceu:argon 50000')
        .outputFluids('gtceu:nitrogen 3500000')
        .outputFluids('gtceu:oxygen 1000000')
        .outputFluids('gtceu:carbon_dioxide 250000')
        .outputFluids('gtceu:radon 10000')
        .outputFluids('gtceu:xenon 2500')
        .outputFluids('gtceu:neon 5000')
        .duration(1230)
        .EUt(GTValues.VA[GTValues.ZPM])

})
