GTCEuStartupEvents.registry('gtceu:dimension_marker', event => {
    event.create('ad_astra:earth_orbit')
        .iconSupplier(() => Item.of('ad_astra:earth_globe').getItem())
        .tier(0)
        .overrideName('Earth Orbit')
    event.create('undergarden:undergarden')
        .iconSupplier(() => Item.of('kubejs:undergarden_dim').getItem())
        .tier(0)
        .overrideName('The Undergarden')
    event.create('frontiers:sun_orbit')
        .iconSupplier(() => Item.of('ad_astra:sun_globe').getItem())
        .tier(3)
        .overrideName('Sun Orbit')
    event.create('ad_astra:moon')
        .iconSupplier(() => Item.of('ad_astra:moon_globe').getItem())
        .tier(3)
        .overrideName('§bThe Moon')
})