GTCEuServerEvents.oreVeins(event => {

    // Venus Bismuth Vein - Stringer (tendrils of bismuth)
    event.add('kubejs:venus_bismuth_vein', vein => {
        vein.weight(20).clusterSize(30).density(0.3)
        vein.layer('venus_stone')
        vein.heightRangeUniform(20, 45)
        let gen = new StringerVeinGenerator()
            .oreBlock(GTMaterials.get('bismuthinite'), 2)
            .oreBlock(GTMaterials.CassiteriteSand, 1)
            .oreBlock(GTMaterials.Cinnabar, 1)
            .tendrilCount(14)
            .coreRadius(0.25)
            .tendrilRadius(0.05)
            .coreDensity(0.55)
            .tendrilCurvature(0.5)
        vein.generator(gen)
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.Tetrahedrite)
            .density(0.2)
            .radius(4))
    })

    // Venus Hadalite Vein - Shell (deep tungsten layers)
    event.add('kubejs:venus_hadalite_vein', vein => {
        vein.weight(15).clusterSize(40).density(0.45)
        vein.layer('venus_stone')
        vein.heightRangeUniform(10, 30)
        let gen = new ShellVeinGenerator()
            .coreBlock(GTMaterials.get('hadalite'), 1)
            .innerBlock(GTMaterials.get('wolframite'), 2)
            .innerBlock(GTMaterials.get('scheelite'), 1)
            .outerBlock(GTMaterials.get('calcite'), 1)
            .innerRadiusRatio(0.25)
            .outerRadiusRatio(0.55)
        vein.generator(gen)
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.get('hadalite'))
            .density(0.2)
            .radius(4))
    })

    // Purest Luminite - Cluster (dense luminite pockets)
    event.add('kubejs:purest_luminite', vein => {
        vein.weight(15).clusterSize(40).density(0.45)
        vein.layer('venus_stone')
        vein.heightRangeUniform(10, 30)
        let gen = new ClusterVeinGenerator()
            .oreBlock(GTMaterials.get('luminite'), 4)
            .oreBlock(GTMaterials.get('desh'), 1)
            .oreBlock(GTMaterials.get('basaltic_mineral_sand'), 2)
            .rareBlock(GTMaterials.get('apatite'), 1)
            .pocketCount(10)
            .pocketRadius(0.07)
            .channelRadius(0.03)
            .pocketDensity(0.85)
            .rareBlockChance(0.06)
        vein.generator(gen)
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.get('apatite'))
            .density(0.2)
            .radius(4))
    })

    // Naumannite - Branching (selenium silver branches)
    event.add('kubejs:naumannite', vein => {
        vein.weight(15).clusterSize(40).density(0.45)
        vein.layer('venus_stone')
        vein.heightRangeUniform(10, 30)
        let gen = new BranchingVeinGenerator()
            .oreBlock(GTMaterials.get('naumannite'), 2)
            .oreBlock(GTMaterials.get('wulfenite'), 1)
            .oreBlock(GTMaterials.get('lepidolite'), 2)
            .rareBlock(GTMaterials.get('spodumene'), 1)
            .branchCount(5)
            .branchAngleVariance(0.14)
            .branchSplitChance(0.18)
            .widthDecay(0.4)
            .lengthMultiplier(0.55)
            .rareBlockChance(0.08)
        vein.generator(gen)
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.get('naumannite'))
            .density(0.2)
            .radius(4))
    })
})
