ServerEvents.recipes((event) => {

    // HRE - Cyanex-272 Infused Virtue Meld Beads
    event.recipes.gtceu.mixer('bead_mix')
        .inputFluids('gtceu:molten_virtue_meld 1000')
        .inputFluids('gtceu:bisphenol_a 2000')
        .itemInputs('12x gtceu:ammonium_bicarbonate')
        .outputFluids('gtceu:bead_mix 3000')
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.chemical_reactor('dirty_beads')
        .inputFluids('gtceu:bead_mix 1000')
        .notConsumable('placeholder oil')
        .itemOutputs('2x gtceu:dirty_bead')
        .duration(100)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.chemical_reactor('clean_beads')
        .itemInputs('gtceu:dirty_bead')
        .inputFluids('cosmiccore:prisma 1000')
        .itemOutputs('gtceu:wet_clean_bead')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.chemical_dehydrator('bead_drying')
        .itemInputs('gtceu:wet_clean_bead')
        .itemOutputs('gtceu:clean_bead')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.mixer('cyanex_kero_mix')
        .inputFluids('gtceu:cyanex_272 1000')
        .inputFluids('gtceu:kerosene 4000')
        .outputFluids('gtceu:cyanex_in_kerosene 5000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.mixer('beadpreggers')
        .inputFluids('gtceu:cyanex_in_kerosene 2000')
        .itemInputs('4x gtceu:clean_bead')
        .itemOutputs('4x gtceu:impregnated_beads')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])

    // HRE - Tier 3
    event.recipes.gtceu.chemical_reactor('hre_hydroxide')
        .inputFluids('gtceu:hre_slag 100')
        .itemInputs('3x gtceu:sodium_hydroxide_dust')
        .itemOutputs('gtceu:hre_hydroxides_dust')
        .itemOutputs('gtceu:sodium_phosphate_dust')
        .duration(200)
        .EUt(GTValues.VA[GTValues.IV]);
    event.recipes.gtceu.chemical_dehydrator('hre_oxide')
        .itemInputs('gtceu:hre_hydroxides_dust')
        .itemOutputs('gtceu:hre_oxides_dust')
        .duration(400)
        .EUt(GTValues.VA[GTValues.HV]);
    event.recipes.gtceu.chemical_reactor('hre_nitrate')
        .itemInputs('gtceu:hre_oxides_dust')
        .inputFluids('gtceu:nitric_acid 3000')
        .itemOutputs('gtceu:hre_nitrates')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])
    
})