StartupEvents.registry('gtceu:material', event => {
    event.create('gtceu:naquadric_metallic_powder')
        .ore()
        .color(0x242625).iconSet(GTMaterialIconSet.SHINY)
    event.create('gtceu:naquadric_solution')
        .liquid()
        .color(0x292929)
    event.create('gtceu:fluoronaquadric_acid')
        .liquid()
        .color(0x3A494B)
    event.create('gtceu:naquadah_difluoride')
        .liquid()
        .color(0x29393B)
    event.create('gtceu:naquadah_concentrate')
        .dust()
        .color(0x242625)
    event.create('gtceu:potassium_peroxymonosulfate')
        .dust()
        .color(0x661b1b)
    event.create('gtceu:indium_trifluoride')
        .dust()
        .color(0x2c0a59)
    event.create('gtceu:naquadah_sulfate')
        .liquid()
        .color(0x2E2A10)
    event.create('gtceu:prismaline_thermal_catalyst')
        .liquid()
        .color(0xa61654)
    event.create('gtceu:diluted_nitric_acid')
        .liquid()
        .color(0x949479)
    event.create('gtceu:potassium_fluoride')
        .dust()
        .color(0x709483)
})


// GTCEuStartupEvents.materialModification(event => {
//     GTMaterials.get('naquadric_metallic_powder').setFormula('Nq-', true)
//     GTMaterials.get('naquadric_solution').setFormula('NqNO2', true)
//     GTMaterials.get('fluoronaquadric_acid').setFormula('H2NqF4', true)
//     GTMaterials.get('naquadah_difluoride').setFormula('NqF2', true)
//     GTMaterials.get('naquadah_concentrate').setFormula('Nq?', true)
//     GTMaterials.get('potassium_peroxymonosulfate').setFormula('KHSO5', true)
//     GTMaterials.get('indium_trifluoride').setFormula('InF3', true)
//     GTMaterials.get('prismaline_thermal_catalyst').setFormula('Piꬿ', true)
//     GTMaterials.get('diluted_nitric_acid').setFormula('(H2O)HNO3', true)
//     GTMaterials.get('potassium_fluoride').setFormula('KF', true)
// })