
StartupEvents.registry('gtceu:material', event => {
    //Molten Salt Nuclear
    // Oxide -> Hexafluoride -> Split into depleted and enriched -> turned into fuel
    //Reprocessing T1
    // Superheated X waste fuel -> Cooled -> Centrifuged
    //Reproc T2
    //Cool Superheated Waste Fuel -> Splitting Agent of some kind -> break away the nuclear products from the flinak and fluoride
    event.create('gtceu:flinak')
        .liquid()
        .color(0x2b2b2b)
    //Hexafluorides and Oxides
    event.create('gtceu:americium_oxide')
        .dust()
        .color(0x02402d)
    event.create('gtceu:americium_hexafluoride')
        .gas()
        .color(0x02402d)
    event.create('gtceu:enriched_americium_hexafluoride')
        .gas()
        .color(0x02402d)
    event.create('gtceu:depleted_americium_hexafluoride')
        .gas()
        .color(0x02402d)


    //Normal Fuel Salts
    event.create('gtceu:uranium_fuel_salt')
        .liquid()
        .color(0x224224)
    event.create('gtceu:americium_fuel_salt')
        .liquid()
        .color(0x02402d)
    event.create('gtceu:californium_fuel_salt')
        .liquid()
        .color(0x4a2201)
    event.create('gtceu:einsteinium_fuel_salt')
        .liquid()
        .color(0x5c5306)
    event.create('gtceu:medelevium_fuel_salt')
        .liquid()
        .color(0x181957)
    event.create('gtceu:lawrencium_fuel_salt')
        .liquid()
        .color(0x1d2623)
    //SuperHeated Fuel Salts
    event.create('gtceu:superheated_uranium_fuel_salt')
        .liquid()
        .color(0x53a158)
    event.create('gtceu:superheated_americium_fuel_salt')
        .liquid()
        .color(0x07d797)
    event.create('gtceu:superheated_californium_fuel_salt')
        .liquid()
        .color(0xa20cca)
    event.create('gtceu:superheated_medelevium_fuel_salt')
        .liquid()
        .color(0x3638c4)
    event.create('gtceu:superheated_lawrencium_fuel_salt')
        .liquid()
        .color(0x607e74)
    //Superheated Waste Fuel Salts
    event.create('gtceu:superheated_waste_uranium_fuel_salt')
        .liquid()
        .color(0x3e7842)
    event.create('gtceu:superheated_waste_americium_fuel_salt')
        .liquid()
        .color(0x05966a)
    event.create('gtceu:superheated_waste_californium_fuel_salt')
        .liquid()
        .color(0xa04902)
    event.create('gtceu:superheated_waste_medelevium_fuel_salt')
        .liquid()
        .color(0x292b96)
    event.create('gtceu:superheated_waste_lawrencium_fuel_salt')
        .liquid()
        .color(0x435851)
    //Waste Fuel Salts
    event.create('gtceu:waste_uranium_fuel_salt')
        .liquid()
        .color(0x3e7842)
    event.create('gtceu:waste_americium_fuel_salt')
        .liquid()
        .color(0x05966a)
    event.create('gtceu:waste_californium_fuel_salt')
        .liquid()
        .color(0xa04902)
    event.create('gtceu:waste_medelevium_fuel_salt')
        .liquid()
        .color(0x292b96)
    event.create('gtceu:waste_lawrencium_fuel_salt')
        .liquid()
        .color(0x435851)
})