ServerEvents.recipes(event => {
    event.remove({ id: 'gtceu:thermal_centrifuge/centrifuge_bauxite_purified_ore_to_refined_ore' })
    event.remove({ id: 'gtceu:thermal_centrifuge/centrifuge_bauxite_crushed_ore_to_refined_ore' })
    event.remove({ id: 'gtceu:macerator/macerate_bauxite_crushed_ore_to_dust' })
    event.remove({ id: 'gtceu:centrifuge/centrifuge_bauxite_pure_dust_to_dust' })
    event.remove({ id: 'gtceu:extractor/extract_cryolite_dust' })
    event.remove({ id: 'gtceu:mixer/bauxite_slurry_from_washed_bauxite' })
    event.remove({ id: 'gtceu:mixer/bauxite_slurry_from_crushed_bauxite' })
    event.remove({ id: 'gtceu:cracker/cracked_bauxite_slurry' })
    event.remove({ id: 'gtceu:large_chemical_reactor/bauxite_sludge_from_slurry' })
    event.remove({ id: 'cosmiccore:industrial_chemvat/bauxite_sludge_from_slurry' })
    event.remove({ id: 'gtceu:distillery/bauxite_sludge_decalcification' })
    event.remove({ id: 'gtceu:centrifuge/bauxite_sludge_centrifuge' })
    event.remove({ id: 'gtceu:electromagnetic_separator/bauxite_slag_separation' })
    event.remove({ id: 'gtceu:electrolyzer/bauxite_electrolysis' })

    // NaOH(s) + H2O(l) -> NaOH.H2O(aq)
    event.recipes.gtceu.mixer('frontiers:chains/bauxite/sodium_hydroxide_solution')
        .itemInputs('3x gtceu:sodium_hydroxide_dust')
        .inputFluids('1000x minecraft:water')
        .outputFluids('1000x gtceu:sodium_hydroxide_solution')
        .duration(20)
        .EUt(GTValues.V[GTValues.LV], 4)
    event.recipes.gtceu.mixer('frontiers:chains/bauxite/sodium_hydroxide_bauxite')
        .itemInputs('5x gtceu:bauxite_dust', '3x gtceu:silicon_dioxide_dust')
        .inputFluids('4000x gtceu:sodium_hydroxide_solution')
        .outputFluids('4000x gtceu:sodium_hydroxide_bauxite')
        .duration(60)
        .EUt(GTValues.V[GTValues.LV], 4)
    event.recipes.gtceu.fluid_heater('frontiers:chains/bauxite/heated_sodium_hydroxide_bauxite')
        .inputFluids('4000x gtceu:sodium_hydroxide_bauxite')
        .outputFluids('4000x gtceu:heated_sodium_hydroxide_bauxite')
        .duration(30)
        .EUt(GTValues.V[GTValues.LV], 4)
    event.recipes.gtceu.centrifuge('frontiers:chains/bauxite/bauxite_separation')
        .inputFluids('4000x gtceu:heated_sodium_hydroxide_bauxite')
        .outputFluids('4000x gtceu:sodium_aluminate_solution', '500x gtceu:red_mud')
        .duration(230)
        .EUt(GTValues.V[GTValues.MV], 2)
    // 2 NaAlO2(aq) + Na2SiO3(aq) + 6 H2O(l) -> 2 NaAlO2(s) + Na2SiO3(s) + 6 H2O(l)
    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/bauxite/sodium_aluminate_straining')
        .circuit(1)
        .inputFluids('4000x gtceu:sodium_aluminate_solution')
        .itemOutputs('8x gtceu:sodium_aluminate_dust', '6x gtceu:sodium_silicate_dust')
        .chancedOutput('gtceu:gallium_dust', 1500)
        .outputFluids('6000x minecraft:water')
        .duration(120)
        .EUt(GTValues.V[GTValues.HV], 2)
    // 2 NaAlO2(s) + CO2(g) + 3 H2O(l) -> 2 Al(OH)3(s) + Na2CO3(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/bauxite/aluminium_hydroxide_carbonation')
        .itemInputs('8x gtceu:sodium_aluminate_dust')
        .inputFluids('3000x minecraft:water', '1000x gtceu:carbon_dioxide')
        .itemOutputs('14x gtceu:aluminium_hydroxide_dust', '6x gtceu:soda_ash_dust')
        .duration(7200)
        .EUt(GTValues.V[GTValues.MV], 4)
    // NaAlO2(s) + 2 H2O(l) -> Al(OH)3(s) + NaOH(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/bauxite/aluminium_hydroxide_precipitation')
        .itemInputs('4x gtceu:sodium_aluminate_dust')
        .inputFluids('2000x minecraft:water')
        .notConsumableItem('gtceu:aluminium_hydroxide_dust')
        .itemOutputs('7x gtceu:aluminium_hydroxide_dust', '3x gtceu:sodium_hydroxide_dust')
        .duration(180)
        .EUt(GTValues.V[GTValues.MV], 2)
    // 2 Al(OH)3(s) -> Al2O3(s) + 3 H2O(l)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/bauxite/alumina_from_hydroxide')
        .itemInputs('14x gtceu:aluminium_hydroxide_dust')
        .itemOutputs('5x gtceu:alumina_dust')
        .outputFluids('3000x minecraft:water')
        .blastFurnaceTemp(1100)
        .duration(200)
        .EUt(GTValues.V[GTValues.MV], 2)
    // Na2SiO3(s) + H2O(l) -> 2 NaOH(s) + SiO2(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/bauxite/sodium_silicate_recovery')
        .itemInputs('6x gtceu:sodium_silicate_dust')
        .inputFluids('1000x minecraft:water')
        .itemOutputs('6x gtceu:sodium_hydroxide_dust', '3x gtceu:silicon_dioxide_dust')
        .duration(200)
        .EUt(GTValues.V[GTValues.MV], 2)
    event.recipes.gtceu.mixer('frontiers:chains/bauxite/neutralised_red_mud')
        .inputFluids('500x gtceu:red_mud', '1000x gtceu:hydrochloric_acid', '1500x minecraft:water')
        .outputFluids('500x gtceu:neutralised_red_mud')
        .duration(100)
        .EUt(GTValues.V[GTValues.MV], 4)
    event.recipes.gtceu.centrifuge('frontiers:chains/bauxite/red_mud_slurry')
        .inputFluids('500x gtceu:neutralised_red_mud')
        .outputFluids('250x gtceu:red_mud_slurry', '2000x gtceu:diluted_hydrochloric_acid')
        .duration(100)
        .EUt(GTValues.V[GTValues.MV], 1)
    event.recipes.gtceu.centrifuge('frontiers:chains/bauxite/red_mud_byproducts')
        .inputFluids('250x gtceu:red_mud_slurry')
        .chancedOutput('3x gtceu:rutile_dust', 8800)
        .chancedOutput('2x gtceu:vanadium_dust', 900)
        .chancedOutput('5x gtceu:hematite_dust', 3500)
        .chancedOutput('2x gtceu:quicklime_dust', 950)
        .chancedOutput('5x gtceu:alumina_dust', 1900)
        .outputFluids('500x minecraft:water')
        .duration(640)
        .EUt(GTValues.V[GTValues.MV], 4)
})
