ServerEvents.recipes(event => {
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_chromite' })
    event.remove({ id: 'gtceu:centrifuge/ruby_slurry_centrifuging' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_ruby' })

    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/chromite/alumina_reduction')
        .itemInputs(['10x gtceu:alumina_dust', '3x gtceu:carbon_dust'])
        .itemOutputs('4x gtceu:aluminium_ingot')
        .outputFluids('3000x gtceu:carbon_dioxide')
        .blastFurnaceTemp(1200)
        .duration(1200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.mixer('frontiers:chains/chromite/sodium_carbonate_solution')
        .itemInputs('6x gtceu:soda_ash_dust')
        .inputFluids('1000x minecraft:water')
        .outputFluids('1000x gtceu:sodium_carbonate_solution')
        .duration(60)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor('frontiers:chains/chromite/sodium_chromate_solution')
        .itemInputs('14x gtceu:chromite_dust')
        .inputFluids(['7000x gtceu:oxygen', '4000x gtceu:sodium_carbonate_solution'])
        .itemOutputs('5x gtceu:hematite_dust')
        .outputFluids(['4000x gtceu:carbon_dioxide', '4000x gtceu:sodium_chromate_solution'])
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/chromite/sodium_dichromate_solution')
        .inputFluids(['1000x gtceu:sulfuric_acid', '2000x gtceu:sodium_chromate_solution'])
        .itemOutputs('7x gtceu:sodium_sulfate_dust')
        .outputFluids('1000x gtceu:sodium_dichromate_solution')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/chromite/chromium_iii_oxide')
        .itemInputs('2x gtceu:carbon_dust')
        .inputFluids('1000x gtceu:sodium_dichromate_solution')
        .itemOutputs(['6x gtceu:soda_ash_dust', '5x gtceu:chromium_iii_oxide_dust'])
        .outputFluids('1000x gtceu:carbon_monoxide')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/chromite/chromium_reduction')
        .itemInputs(['5x gtceu:chromium_iii_oxide_dust', '2x gtceu:aluminium_dust'])
        .itemOutputs(['2x gtceu:chromium_dust', '5x gtceu:alumina_dust'])
        .blastFurnaceTemp(1200)
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('frontiers:chains/chromite/soda_ash_recovery')
        .itemInputs('7x gtceu:sodium_sulfate_dust')
        .inputFluids('1000x gtceu:carbon_monoxide')
        .itemOutputs('6x gtceu:soda_ash_dust')
        .outputFluids('1000x gtceu:sulfur_dioxide')
        .duration(40)
        .EUt(GTValues.VA[GTValues.MV])
})
