ServerEvents.recipes(event => {

    // Naphtha -> C8H10 (catalytic reforming separation)
    event.recipes.gtceu.distillery('para_xylene')
        .inputFluids('gtceu:naphtha 1000')
        .circuit(4)
        .outputFluids('gtceu:para_xylene 500')
        .duration(160)
        .EUt(GTValues.VA[GTValues.HV])

    // C8H10 + 3O2 -> C8H6O4 + C8H6O3 + 2H2O (Amoco oxidation, Co/Mn catalyst — crude product contains 4-CBA impurity)
    event.recipes.gtceu.large_chemical_reactor('crude_terephthalic_acid')
        .inputFluids('gtceu:para_xylene 1000')
        .inputFluids('gtceu:oxygen 3000')
        .notConsumable('gtceu:cobalt_dust')
        .notConsumable('gtceu:manganese_dust')
        .itemOutputs('16x gtceu:crude_terephthalic_acid_dust')
        .chancedOutput('2x gtceu:carboxybenzaldehyde_dust', 7500, 500)
        .outputFluids('minecraft:water 2000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.EV])

    // C8H6O4(crude) + H2 -> C8H6O4(pure) (PTA hydrogenation purification — Pd/C catalyst)
    event.recipes.gtceu.chemical_reactor('purified_terephthalic_acid')
        .itemInputs('16x gtceu:crude_terephthalic_acid_dust')
        .inputFluids('gtceu:hydrogen 1000')
        .notConsumable('gtceu:carbon_dust')
        .notConsumable('gtceu:palladium_dust')
        .itemOutputs('18x gtceu:terephthalic_acid_dust')
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])

    // C8H6O3 + H2 -> C8H6O4 (4-CBA reduction back to terephthalic acid — recycling impurity)
    event.recipes.gtceu.chemical_reactor('carboxybenzaldehyde_reduction')
        .itemInputs('16x gtceu:carboxybenzaldehyde_dust')
        .inputFluids('gtceu:hydrogen 1000')
        .itemOutputs('18x gtceu:terephthalic_acid_dust')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    // C8H6O4 + 2H2 -> C8H6O2 + 2H2O (partial reduction)
    event.recipes.gtceu.electric_blast_furnace('terephthalaldehyde')
        .itemInputs('18x gtceu:terephthalic_acid_dust')
        .inputFluids('gtceu:hydrogen 2000')
        .outputFluids('gtceu:terephthalaldehyde 1000')
        .outputFluids('minecraft:water 2000')
        .blastFurnaceTemp(1200)
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])

    // SO3 + SCl2 -> SOCl2 + SO2
    event.recipes.gtceu.chemical_reactor('thionyl_chloride')
        .inputFluids('gtceu:sulfur_trioxide 1000')
        .inputFluids('gtceu:sulfur_dichloride 1000')
        .outputFluids('gtceu:thionyl_chloride 1000')
        .outputFluids('gtceu:sulfur_dioxide 1000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])

    // C8H6O2 + SOCl2 -> C8H4Cl2O2 + S + H2O
    event.recipes.gtceu.chemical_reactor('terephthaloyl_chloride')
        .inputFluids('gtceu:terephthalaldehyde 1000')
        .inputFluids('gtceu:thionyl_chloride 1000')
        .itemOutputs('16x gtceu:terephthaloyl_chloride_dust')
        .itemOutputs('1x gtceu:sulfur_dust')
        .outputFluids('minecraft:water 1000')
        .duration(300)
        .EUt(GTValues.VA[GTValues.HV])

    // ClC6H4NO2 + 2NH3 + 3H2 -> C6H8N2 + NH4Cl + 2H2O (reduction + ammonolysis)
    event.recipes.gtceu.chemical_reactor('crude_para_phenylenediamine')
        .inputFluids('gtceu:nitrochlorobenzene 1000')
        .inputFluids('gtceu:ammonia 2000')
        .inputFluids('gtceu:hydrogen 3000')
        .outputFluids('gtceu:crude_para_phenylenediamine 1000')
        .itemOutputs('5x gtceu:ammonium_chloride_dust')
        .duration(400)
        .EUt(GTValues.VA[GTValues.HV])

    // C6H8N2(crude) -> C6H8N2 + 2H2O (dehydration purification)
    event.recipes.gtceu.chemical_dehydrator('para_phenylenediamine')
        .inputFluids('gtceu:crude_para_phenylenediamine 1000')
        .itemOutputs('14x gtceu:para_phenylenediamine_dust')
        .outputFluids('minecraft:water 2000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    // 2 C3H6O -> 2 C2H2O + 2 CH4 (pyrolysis, CS2 catalyst)
    event.recipes.gtceu.roaster('ketene')
        .inputFluids('gtceu:acetone 2000')
        .inputFluids('gtceu:carbon_disulfide 500')
        .outputFluids('gtceu:ketene 2000')
        .outputFluids('gtceu:methane 2000')
        .duration(300)
        .EUt(GTValues.VA[GTValues.HV])

    // 2 C2H2O -> C4H4O2 (ketene dimerization under vacuum)
    event.recipes.gtceu.vacuum_bubbler('di_ketene')
        .inputFluids('gtceu:ketene 2000')
        .outputFluids('gtceu:di_ketene 1000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    // C4H4O2 + H2 -> C4H6O2 (asymmetric hydrogenation, BINAP/Ru catalyst)
    event.recipes.gtceu.chemical_reactor('beta_butyrolactone')
        .inputFluids('gtceu:di_ketene 1000')
        .inputFluids('gtceu:hydrogen 1000')
        .notConsumableFluid('gtceu:binap 100')
        .chancedInput('gtceu:tiny_ruthenium_dust', 5000, 0)
        .outputFluids('gtceu:beta_butyrolactone 1000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.EV])

    // CH3OH + NH3 -> CH5N + H2O
    event.recipes.gtceu.chemical_reactor('methylamine')
        .inputFluids('gtceu:methanol 1000')
        .inputFluids('gtceu:ammonia 1000')
        .outputFluids('gtceu:methylamine 1000')
        .outputFluids('minecraft:water 1000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])

    // C4H6O2 + CH5N -> C5H9NO + H2O (lactam ring formation)
    event.recipes.gtceu.chemical_reactor('n_methyl_2_pyrrolidone')
        .inputFluids('gtceu:beta_butyrolactone 1000')
        .inputFluids('gtceu:methylamine 1000')
        .outputFluids('gtceu:n_methyl_2_pyrrolidone 1000')
        .outputFluids('minecraft:water 1000')
        .duration(240)
        .EUt(GTValues.VA[GTValues.HV])

    // C10H8 + H2SO4 + 3NaOH + HCl -> C10H8O + NaCl + Na2SO3 + 3H2O (sulfonation + alkali fusion)
    event.recipes.gtceu.leaching_plant('two_naphthol')
        .itemInputs('9x gtceu:sodium_hydroxide_dust')
        .inputFluids('gtceu:naphthalene 1000')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .inputFluids('gtceu:hydrochloric_acid 1000')
        .itemOutputs('2x gtceu:salt_dust')
        .itemOutputs('6x gtceu:sodium_sulfite_dust')
        .outputFluids('gtceu:two_naphthol 1000')
        .outputFluids('minecraft:water 3000')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])

    // 2C10H8O + 2FeCl3 -> C20H14O2 + 2FeCl2 + 2HCl (oxidative coupling — low yield, unreacted naphthol recycled)
    event.recipes.gtceu.gravity_float_crucible('binol')
        .inputFluids('gtceu:iron_iii_chloride 2000')
        .inputFluids('gtceu:two_naphthol 2000')
        .outputFluids('gtceu:binol 1000')
        .chancedFluidOutput('gtceu:two_naphthol 500', 7500, 0)
        .outputFluids('gtceu:iron_ii_chloride 2000')
        .outputFluids('gtceu:hydrochloric_acid 2000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.EV])

    // PCl3 + 2C18H15P -> 3C12H10ClP
    event.recipes.gtceu.chemical_reactor('chlorodiphenylphosphine')
        .inputFluids('cosmiccore:triphenylphosphine 2000')
        .inputFluids('gtceu:phosphorus_trichloride 1000')
        .outputFluids('gtceu:chlorodiphenylphosphine 3000')
        .duration(300)
        .EUt(GTValues.VA[GTValues.IV])

    // 2C4H10 + 2Li -> 2C4H9Li + H2
    event.recipes.gtceu.chemical_reactor('butyllithium')
        .inputFluids('gtceu:butane 2000')
        .itemInputs('2x gtceu:lithium_dust')
        .outputFluids('gtceu:butyllithium 2000')
        .outputFluids('gtceu:hydrogen 1000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    // C20H14O2 + C18H15P + C4H9Li + C12H10ClP -> rac-C44H32P2 + 2C5H6 + 2H2O + LiCl (produces racemic mixture)
    event.recipes.gtceu.industrial_chemvat('racemic_binap')
        .inputFluids('gtceu:binol 1000')
        .inputFluids('cosmiccore:triphenylphosphine 1000')
        .inputFluids('gtceu:butyllithium 1000')
        .inputFluids('gtceu:chlorodiphenylphosphine 1000')
        .itemOutputs('2x gtceu:lithium_chloride_dust')
        .outputFluids('gtceu:racemic_binap 1000')
        .outputFluids('gtceu:cyclopentadiene 2000')
        .outputFluids('minecraft:water 2000')
        .duration(800)
        .EUt(GTValues.VA[GTValues.IV])

    // rac-C44H32P2 -> (R)-C44H32P2 (chiral resolution via crystallization — 60% yield, remainder recycled)
    event.recipes.gtceu.centrifuge('binap_chiral_resolution')
        .inputFluids('gtceu:racemic_binap 1000')
        .outputFluids('gtceu:binap 600')
        .chancedFluidOutput('gtceu:racemic_binap 400', 8000, 0)
        .duration(400)
        .EUt(GTValues.VA[GTValues.IV])

    // C8H4Cl2O2 + C6H8N2 -> C14H10N2O2 + 2HCl (condensation polymerization, NMP solvent)
    event.recipes.gtceu.polymerizer('kevlar')
        .itemInputs('16x gtceu:terephthaloyl_chloride_dust')
        .itemInputs('14x gtceu:para_phenylenediamine_dust')
        .inputFluids('gtceu:n_methyl_2_pyrrolidone 100')
        .outputFluids('gtceu:kevlar 1000')
        .outputFluids('gtceu:hydrochloric_acid 2000')
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])

    // Kevlar fluid -> Kevlar fiber (wet spinning)
    event.recipes.gtceu.spooling_machine('kevlar_fiber')
        .inputFluids('gtceu:kevlar 144')
        .itemOutputs('gtceu:kevlar_ingot')
        .duration(200)
        .EUt(GTValues.VA[GTValues.IV])

})
