ServerEvents.recipes(event => {

    // C4H6 (g) + Cl2 (g) -> C4H6Cl2 (l)
    event.recipes.gtceu.chemical_reactor('1_4_dichlorobuta')
        .inputFluids('gtceu:butadiene 1000')
        .inputFluids('gtceu:chlorine 2000')
        .outputFluids('gtceu:1_4_dichlorobutadiene 1000')
        .duration(300)
        .EUt(GTValues.VA[GTValues.IV])

    // C4H6Cl2 (l) -> C4H6Cl2 (l)
    event.recipes.gtceu.chemical_reactor('3_4_dichlorobuta')
        .inputFluids('gtceu:1_4_dichlorobutadiene 1000')
        .notConsumable('12x gtceu:copper_foil')
        .outputFluids('gtceu:3_4_dichlorobutadiene 1000')
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV])

    // C4H6Cl2 (l) + NaOH (s) -> C4H5Cl (l) + NaCl (aq) + H2O (l)
    event.recipes.gtceu.chemical_reactor('chloroprene')
        .inputFluids('gtceu:3_4_dichlorobutadiene 1000')
        .itemInputs('3x gtceu:sodium_hydroxide_dust')
        .outputFluids('gtceu:chloroprene 1000')
        .itemOutputs('2x gtceu:salt_dust')
        .outputFluids('minecraft:water 1000')
        .duration(900)
        .EUt(GTValues.VA[GTValues.HV])

    // C2H4 (g) + Cl2 (g) -> C2H4Cl2 (l)
    event.recipes.gtceu.chemical_reactor('ethylene_dichloride')
        .inputFluids('gtceu:ethylene 1000')
        .inputFluids('gtceu:chlorine 2000')
        .notConsumableFluid('gtceu:iron_iii_chloride 4000')
        .outputFluids('gtceu:ethylene_dichloride 1000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.HV])

    // C2H4Cl2 (l) + 2NH3 (g) -> C2H4(NH2)2 (l)
    event.recipes.gtceu.chemical_reactor('ethylenediamine')
        .inputFluids('gtceu:ethylene_dichloride 1000')
        .inputFluids('gtceu:ammonia 2000')
        .outputFluids('gtceu:ethylenediamine 1000')
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV])

    // C (s) + 2S (s) -> CS2 (l)
    event.recipes.gtceu.electric_blast_furnace('carbon_disulfide')
        .itemInputs('gtceu:coke_dust', '2x gtceu:sulfur_dust')
        .outputFluids('gtceu:carbon_disulfide 1000')
        .blastFurnaceTemp(1200)
        .duration(450)
        .EUt(GTValues.VH[GTValues.MV])

    // C2H8N2 (l) + CS2 (l) -> C3H6N2S (s) + H2S (g)
    event.recipes.gtceu.chemical_reactor('ethylene_thiourea')
        .inputFluids('gtceu:ethylenediamine 1000')
        .inputFluids('gtceu:carbon_disulfide 1000')
        .itemOutputs('12x gtceu:ethylene_thiourea_dust')
        .outputFluids('gtceu:hydrogen_sulfide 1000')
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.mixer('neoprene')
        .inputFluids('gtceu:chloroprene 1000')
        .itemInputs('gtceu:sulfur_dust', '12x gtceu:ethylene_thiourea_dust')
        .outputFluids('gtceu:neoprene 1728')
        .duration(650)
        .EUt(GTValues.VA[GTValues.IV])

})