ServerEvents.recipes(event => {
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_cooperite' })
    event.remove({ id: 'gtceu:chemical_bath/bathe_nickel_crushed_ore_to_purified_ore' })
    event.remove({ id: 'gtceu:macerator/macerate_nickel_refined_ore_to_dust' })
    event.remove({ id: 'gtceu:centrifuge/pgs_separation' })
    event.remove({ id: 'gtceu:electrolyzer/raw_platinum_separation' })
    event.remove({ id: 'gtceu:chemical_reactor/raw_palladium_separation' })
    event.remove({ id: 'gtceu:large_chemical_reactor/raw_palladium_separation' })
    event.remove({ id: 'gtceu:chemical_reactor/inert_metal_mixture_separation' })
    event.remove({ id: 'gtceu:large_chemical_reactor/inert_metal_mixture_separation' })
    event.remove({ id: 'gtceu:electrolyzer/rhodium_sulfate_separation' })
    event.remove({ id: 'gtceu:chemical_reactor/ruthenium_tetroxide_separation' })
    event.remove({ id: 'gtceu:large_chemical_reactor/ruthenium_tetroxide_separation' })
    event.remove({ id: 'gtceu:large_chemical_reactor/rarest_metal_mixture_separation' })
    event.remove({ id: 'gtceu:distillation_tower/acidic_osmium_solution_separation' })
    event.remove({ id: 'gtceu:chemical_reactor/osmium_tetroxide_separation' })
    event.remove({ id: 'gtceu:large_chemical_reactor/osmium_tetroxide_separation' })
    event.remove({ id: 'gtceu:centrifuge/iridium_metal_residue_separation' })
    event.remove({ id: 'gtceu:chemical_reactor/iridium_chloride_separation' })
    event.remove({ id: 'gtceu:large_chemical_reactor/iridium_chloride_separation' })
    event.remove({ id: 'cosmiccore:industrial_chemvat/iridium_chloride_separation' })
    event.remove({ id: 'create:crushing/platinum_ore' })
    event.remove({ id: 'create:crushing/raw_platinum' })
    event.remove({ id: 'create:crushing/raw_platinum_block' })
    event.remove({ id: 'embers:melting/ores/platinum_gold' })
    event.remove({ id: 'embers:melting/raw_materials/platinum_gold' })
    event.remove({ id: 'embers:melting/storage_blocks/raw_platinum_gold' })
    event.remove({ id: 'enderio:sag_milling/osmium_ore' })
    event.remove({ id: 'enderio:sag_milling/raw_osmium' })
    event.remove({ id: 'occultism:crushing/platinum_dust_from_ore' })
    event.remove({ id: 'occultism:crushing/platinum_dust_from_raw' })
    event.remove({ id: 'occultism:crushing/platinum_dust_from_raw_block' })
    event.remove({ id: 'occultism:crushing/osmium_dust_from_ore' })
    event.remove({ id: 'occultism:crushing/osmium_dust_from_raw' })
    event.remove({ id: 'occultism:crushing/osmium_dust_from_raw_block' })
    event.remove({ id: 'occultism:crushing/iridium_dust_from_ore' })
    event.remove({ id: 'occultism:crushing/iridium_dust_from_raw' })
    event.remove({ id: 'occultism:crushing/iridium_dust_from_raw_block' })
    // NH3(g) + HCl(aq) -> NH4Cl(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/ammonium_chloride')
        .inputFluids('1000x gtceu:ammonia', '1000x gtceu:hydrochloric_acid')
        .itemOutputs('2x gtceu:ammonium_chloride_dust')
        .duration(20)
        .EUt(GTValues.V[GTValues.MV], 2)
    // NaC2H3O2(s) + HCl(aq) -> NaCl(s) + C2H4O2(l)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/acetic_acid_reprocessing')
        .itemInputs('8x gtceu:sodium_acetate_dust')
        .inputFluids('1000x gtceu:hydrochloric_acid')
        .itemOutputs('2x gtceu:salt_dust')
        .outputFluids('1000x gtceu:acetic_acid')
        .duration(60)
        .EUt(GTValues.V[GTValues.HV], 2)
    // ZnSO4(s) -> Zn(s) + SO2(g) + O2(g)
    event.recipes.gtceu.electrolyzer('frontiers:chains/platinum/zinc_sulfate_reprocessing')
        .notConsumableItem('gtceu:zinc_plate')
        .itemInputs('6x gtceu:zinc_sulfate_dust')
        .notConsumableFluid('1000x gtceu:sulfuric_acid')
        .itemOutputs('gtceu:zinc_dust')
        .outputFluids('1000x gtceu:sulfur_dioxide', '2000x gtceu:oxygen')
        .duration(60)
        .EUt(GTValues.V[GTValues.HV], 2)

    // CH4(g) + 3 O2(g) -> 2 H2O2(l) + CO2(g)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/hydrogen_peroxide')
        .inputFluids('1000x gtceu:methane', '6000x gtceu:oxygen')
        .outputFluids('2000x gtceu:hydrogen_peroxide', '1000x gtceu:carbon_dioxide')
        .circuit(7)
        .duration(160)
        .EUt(GTValues.V[GTValues.HV], 2)
    // H2O2(l) + 2 NH3(g) -> N2H4(l) + 2 H2O(l)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/hydrazine')
        .inputFluids('1000x gtceu:hydrogen_peroxide', '2000x gtceu:ammonia')
        .outputFluids('1000x gtceu:hydrazine', '2000x minecraft:water')
        .duration(320)
        .EUt(GTValues.V[GTValues.MV], 4)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/platinum/poor_yield_cooperite')
        .itemInputs('6x gtceu:cooperite_dust')
        .itemOutputs('4x gtceu:platinum_nugget')
        .circuit(2)
        .blastFurnaceTemp(2700)
        .duration(600)
        .EUt(GTValues.V[GTValues.HV], 16)
    // Pt3PdNiS(s) + O2(g) -> Pt3PdNi(s) + SO2(g)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/platinum/cooperite_roasting')
        .itemInputs('6x gtceu:cooperite_dust')
        .inputFluids('2000x gtceu:oxygen')
        .itemOutputs('5x gtceu:roasted_cooperite_dust')
        .outputFluids('1000x gtceu:sulfur_dioxide')
        .circuit(1)
        .blastFurnaceTemp(2700)
        .duration(1200)
        .EUt(GTValues.V[GTValues.MV], 1)
    // Pt3PdNi(s) + 4 CO(g) -> Pt3Pd(s) + Ni(CO)4(l)
    event.recipes.gtceu.chemical_bath('frontiers:chains/platinum/cooperite_nickel_removal')
        .itemInputs('5x gtceu:roasted_cooperite_dust')
        .inputFluids('4000x gtceu:carbon_monoxide')
        .itemOutputs('4x gtceu:nickel_depleted_cooperite_dust')
        .outputFluids('1000x gtceu:nickel_carbonyl')
        .duration(200)
        .EUt(GTValues.V[GTValues.MV], 4)
    // Ni(CO)4(l) -> Ni(s) + 4 CO(g)
    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/platinum/nickel_carbonyl_decomposition')
        .inputFluids('1000x gtceu:nickel_carbonyl')
        .itemOutputs('gtceu:nickel_dust')
        .outputFluids('4000x gtceu:carbon_monoxide')
        .duration(200)
        .EUt(GTValues.V[GTValues.MV], 8)
    // Pt3Pd(s) + 22 HCl(aq) + 14 HNO3(aq) -> 3 H2PtCl6(aq) + H2PdCl4(aq) + 14 H2O(l) + 14 NO2(g)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/cooperite_solution')
        .itemInputs('4x gtceu:nickel_depleted_cooperite_dust')
        .inputFluids('22000x gtceu:hydrochloric_acid', '14000x gtceu:nitric_acid')
        .outputFluids('6000x gtceu:cooperite_solution', '14000x gtceu:nitrogen_dioxide')
        .duration(400)
        .EUt(GTValues.V[GTValues.MV], 4)
    // H2PtCl6(aq) + 2 NH3(g) -> (NH4)2PtCl6(s)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/ammonium_hexachloroplatinate')
        .inputFluids('2000x gtceu:ammonia', '2000x gtceu:cooperite_solution')
        .itemOutputs('9x gtceu:ammonium_hexachloroplatinate_dust')
        .outputFluids('2000x gtceu:plat_depleted_cooperite_solution')
        .duration(100)
        .EUt(GTValues.V[GTValues.MV], 2)
    // (NH4)2PtCl6(s) + 2 H2(g) -> Pt(s) + 2 NH4Cl(s) + 4 HCl(aq)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/platinum_hydrogen_reduction')
        .itemInputs('9x gtceu:ammonium_hexachloroplatinate_dust')
        .inputFluids('4000x gtceu:hydrogen')
        .itemOutputs('gtceu:platinum_dust', '4x gtceu:ammonium_chloride_dust')
        .outputFluids('4000x gtceu:hydrochloric_acid')
        .circuit(1)
        .duration(240)
        .EUt(GTValues.V[GTValues.EV], 2)
    // (NH4)2PtCl6(s) + N2H4(l) -> Pt(s) + 2 NH4Cl(s) + 4 HCl(aq) + N2(g)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/platinum_hydrazine_reduction')
        .itemInputs('9x gtceu:ammonium_hexachloroplatinate_dust')
        .inputFluids('1000x gtceu:hydrazine')
        .itemOutputs('gtceu:platinum_dust', '4x gtceu:ammonium_chloride_dust')
        .outputFluids('4000x gtceu:hydrochloric_acid', '2000x gtceu:nitrogen')
        .circuit(2)
        .duration(190)
        .EUt(GTValues.V[GTValues.HV], 2)
    // H2PdCl4(aq) + Cl2(g) + 2 NH4Cl(s) -> (NH4)2PdCl6(s) + 2 HCl(aq)
    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/platinum/ammonium_hexachloropalladate')
        .itemInputs('4x gtceu:ammonium_chloride_dust')
        .inputFluids('2000x gtceu:chlorine', '6000x gtceu:plat_depleted_cooperite_solution')
        .itemOutputs('gtceu:insoluble_plat_group_residue_dust', '9x gtceu:ammonium_hexachloropalladate_dust')
        .outputFluids('2000x gtceu:hydrochloric_acid')
        .duration(200)
        .EUt(GTValues.V[GTValues.MV], 8)
    // 3 (NH4)2PdCl6(s) + 20 NH3(g) -> 3 Pd(NH3)4Cl2(s) + 12 NH4Cl(s) + N2(g)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/tetraammine_palladium_chloride')
        .itemInputs('27x gtceu:ammonium_hexachloropalladate_dust')
        .inputFluids('20000x gtceu:ammonia')
        .itemOutputs('27x gtceu:tetraammine_palladium_chloride_dust', '24x gtceu:ammonium_chloride_dust')
        .outputFluids('2000x gtceu:nitrogen')
        .circuit(4)
        .duration(152)
        .EUt(GTValues.V[GTValues.MV], 2)
    // Pd(NH3)4Cl2(s) + 2 HCl(aq) -> Pd(NH3)2Cl2(s) + 2 NH4Cl(s)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/diamine_dichloropalladium')
        .itemInputs('9x gtceu:tetraammine_palladium_chloride_dust')
        .inputFluids('2000x gtceu:hydrochloric_acid')
        .itemOutputs('3x gtceu:diamine_dichloropalladium_dust', '4x gtceu:ammonium_chloride_dust')
        .circuit(3)
        .duration(152)
        .EUt(GTValues.V[GTValues.MV], 2)
    // 3 Pd(NH3)2Cl2(s) -> 3 Pd(s) + 4 NH4Cl(s) + 2 HCl(aq) + N2(g)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/palladium_thermal_reduction')
        .itemInputs('9x gtceu:diamine_dichloropalladium_dust')
        .itemOutputs('3x gtceu:palladium_dust', '8x gtceu:ammonium_chloride_dust')
        .outputFluids('2000x gtceu:hydrochloric_acid', '2000x gtceu:nitrogen')
        .circuit(1)
        .duration(480)
        .EUt(GTValues.V[GTValues.EV], 2)
    // 2 Pd(NH3)2Cl2(s) + N2H4(l) -> 2 Pd(s) + 4 NH4Cl(s) + N2(g)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/palladium_hydrazine_reduction')
        .itemInputs('6x gtceu:diamine_dichloropalladium_dust')
        .inputFluids('1000x gtceu:hydrazine')
        .itemOutputs('2x gtceu:palladium_dust', '8x gtceu:ammonium_chloride_dust')
        .outputFluids('2000x gtceu:nitrogen')
        .circuit(2)
        .duration(180)
        .EUt(GTValues.V[GTValues.HV], 2)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/platinum/rhodium_sulfate_extraction')
        .itemInputs('9x gtceu:insoluble_plat_group_residue_dust', '21x gtceu:sodium_bisulfate_dust')
        .inputFluids('7000x minecraft:water')
        .itemOutputs('8x gtceu:rhodium_depleted_plat_group_residue_dust')
        .outputFluids('1000x gtceu:rhodium_sulfate_solution')
        .blastFurnaceTemp(3600)
        .duration(128)
        .EUt(GTValues.V[GTValues.HV], 2)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/platinum/ruthenium_osmium_extraction')
        .itemInputs('gtceu:rhodium_depleted_plat_group_residue_dust', 'gtceu:sodium_peroxide_dust')
        .inputFluids('2250x minecraft:water')
        .itemOutputs('gtceu:iridium_rich_plat_group_residue_dust')
        .outputFluids('125x gtceu:sodium_ruthenate_perosomate')
        .blastFurnaceTemp(4500)
        .duration(120)
        .EUt(GTValues.V[GTValues.HV], 2)
    // Ir(s) + 2 BaO2(s) + 6 HCl(aq) -> H2IrCl6.2H2O(aq) + 2 BaO(s)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/platinum/chloroiridic_acid')
        .itemInputs('4x gtceu:iridium_rich_plat_group_residue_dust', '6x gtceu:barium_peroxide_dust')
        .inputFluids('6000x gtceu:hydrochloric_acid')
        .itemOutputs('4x gtceu:barium_oxide_dust')
        .outputFluids('1000x gtceu:chloroiridic_acid')
        .blastFurnaceTemp(4500)
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 2)
    // 2 Ba(s) + O2(g) -> 2 BaO(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/barium_oxide')
        .itemInputs('gtceu:barium_dust')
        .inputFluids('1000x gtceu:oxygen')
        .itemOutputs('2x gtceu:barium_oxide_dust')
        .circuit(3)
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 4)
    // 2 BaO(s) + O2(g) -> 2 BaO2(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/barium_peroxide')
        .itemInputs('2x gtceu:barium_oxide_dust')
        .inputFluids('1000x gtceu:oxygen')
        .itemOutputs('3x gtceu:barium_peroxide_dust')
        .circuit(4)
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 4)
    // H2IrCl6.2H2O(aq) + 2 NH4Cl(s) -> (NH4)2IrCl6(s) + 2 HCl(aq) + 2 H2O(l)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/ammonium_hexachloroiridate')
        .itemInputs('4x gtceu:ammonium_chloride_dust')
        .inputFluids('1000x gtceu:chloroiridic_acid')
        .itemOutputs('10x gtceu:ammonium_hexachloroiridate_dust')
        .outputFluids('2000x gtceu:hydrochloric_acid', '2000x minecraft:water')
        .duration(120)
        .EUt(GTValues.V[GTValues.EV], 2)
    // (NH4)2IrCl6(s) + 4 FeCl2(l) -> Ir(s) + 4 FeCl3(l) + 2 NH3(g) + 2 HCl(aq)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/iridium_reduction')
        .itemInputs('10x gtceu:ammonium_hexachloroiridate_dust')
        .inputFluids('4000x gtceu:iron_ii_chloride')
        .itemOutputs('gtceu:iridium_dust')
        .outputFluids('4000x gtceu:iron_iii_chloride', '2000x gtceu:ammonia', '2000x gtceu:hydrochloric_acid')
        .duration(80)
        .EUt(GTValues.V[GTValues.IV], 2)
    // Fe(s) + Cl2(g) -> FeCl2(l)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/iron_ii_chloride')
        .itemInputs('gtceu:iron_dust')
        .inputFluids('2000x gtceu:chlorine')
        .outputFluids('1000x gtceu:iron_ii_chloride')
        .circuit(4)
        .duration(80)
        .EUt(GTValues.V[GTValues.LV], 2)
    // Rh2(SO4)3(aq) + 3 Zn(s) -> 2 Rh(s) + 3 ZnSO4(s)
    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/platinum/crude_rhodium')
        .itemInputs('3x gtceu:zinc_dust')
        .inputFluids('1000x gtceu:rhodium_sulfate_solution')
        .itemOutputs('2x gtceu:crude_rhodium_dust', '18x gtceu:zinc_sulfate_dust')
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 4)
    // 2 Rh(s) + 6 NaCl(s) + 3 Cl2(g) -> 2 Na3RhCl6(s)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/sodium_hexachlororhodate')
        .itemInputs('gtceu:crude_rhodium_dust', '6x gtceu:salt_dust')
        .inputFluids('3000x gtceu:chlorine')
        .itemOutputs('10x gtceu:sodium_hexachlororhodate_dust')
        .duration(120)
        .EUt(GTValues.V[GTValues.HV], 2)

    // 4 Na3RhCl6(s) + 12 NaOH(s) + 3 N2H4(l) -> 4 Rh(s) + 24 NaCl(s) + 12 H2O(l) + 3 N2(g)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/rhodium_reduction')
        .itemInputs('20x gtceu:sodium_hexachlororhodate_dust', '18x gtceu:sodium_hydroxide_dust')
        .inputFluids('1500x gtceu:hydrazine')
        .itemOutputs('2x gtceu:rhodium_dust', '24x gtceu:salt_dust')
        .outputFluids('6000x minecraft:water', '3000x gtceu:nitrogen')
        .duration(720)
        .EUt(GTValues.V[GTValues.EV], 4)
        
    // Na4(RuO4)3(OsO4)4(H2O)6(aq) + 2 O(g) -> (RuO4)3(OsO4)4(NaOH)4(H2O)4(aq)
    event.recipes.gtceu.cracker('frontiers:chains/platinum/ruthenium_osmium_tetroxides')
        .inputFluids('250x gtceu:sodium_ruthenate_perosomate', '500x gtceu:oxygen')
        .outputFluids('250x gtceu:ruthenium_osmium_tetroxides')
        .circuit(1)
        .duration(125)
        .EUt(GTValues.V[GTValues.HV], 4)
    // (RuO4)3(OsO4)4(NaOH)4(H2O)4(aq) + 34 HCl(aq) -> (RuO4)3(OsO4)4(NaCl)4(HCl)30(H2O)8(aq)
    event.recipes.gtceu.mixer('frontiers:chains/platinum/chlororuthenic_osmium_solution')
        .inputFluids('250x gtceu:ruthenium_osmium_tetroxides', '8500x gtceu:hydrochloric_acid')
        .outputFluids('250x gtceu:chlororuthenic_acid_osmium_tetroxide_solution')
        .duration(125)
        .EUt(GTValues.V[GTValues.EV], 1)
    // (RuO4)3(OsO4)4(NaCl)4(HCl)30(H2O)8(aq) -> 4 (OsO4)(NaCl)(s) + 3 H2RuCl6.2H2O(aq) + 12 Cl(g) + 14 H2O(l)
    event.recipes.gtceu.distillation_tower('frontiers:chains/platinum/chlororuthenic_osmium_separation')
        .inputFluids('250x gtceu:chlororuthenic_acid_osmium_tetroxide_solution')
        .itemOutputs('7x gtceu:impure_osmium_tetroxide_dust')
        .outputFluids('750x gtceu:chlororuthenic_acid', '3000x gtceu:chlorine', '3500x minecraft:water')
        .duration(150)
        .EUt(GTValues.V[GTValues.EV], 2)
    // H2RuCl6.2H2O(aq) + 2 NH4Cl(s) -> (NH4)2RuCl6(s) + 2 HCl(aq) + 2 H2O(l)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/ammonium_hexachlororuthenate')
        .inputFluids('1000x gtceu:chlororuthenic_acid')
        .itemInputs('4x gtceu:ammonium_chloride_dust')
        .itemOutputs('9x gtceu:ammonium_hexachlororuthenate_dust')
        .outputFluids('2000x gtceu:hydrochloric_acid', '2000x minecraft:water')
        .duration(240)
        .EUt(GTValues.V[GTValues.EV], 2)
    // (NH4)2RuCl6(s) + 2 H2(g) -> Ru(s) + 2 NH3(g) + 6 HCl(aq)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/ruthenium_reduction')
        .inputFluids('4000x gtceu:hydrogen')
        .itemInputs('9x gtceu:ammonium_hexachlororuthenate_dust')
        .itemOutputs('gtceu:ruthenium_dust')
        .outputFluids('2000x gtceu:ammonia', '6000x gtceu:hydrochloric_acid')
        .duration(240)
        .EUt(GTValues.V[GTValues.IV], 2)
    // CH4(g) + 4 Cl2(g) -> CCl4(g) + 4 HCl(aq)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/carbon_tetrachloride')
        .inputFluids('1000x gtceu:methane', '8000x gtceu:chlorine')
        .outputFluids('1000x gtceu:carbon_tetrachloride', '4000x gtceu:hydrochloric_acid')
        .circuit(4)
        .duration(60)
        .EUt(GTValues.V[GTValues.HV], 2)
    // 4 Na(s) + O2(g) -> 2 Na2O(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/sodium_oxide')
        .inputFluids('1000x gtceu:oxygen')
        .itemInputs('2x gtceu:sodium_dust')
        .itemOutputs('3x gtceu:sodium_oxide_dust')
        .circuit(2)
        .duration(60)
        .EUt(GTValues.V[GTValues.MV], 2)
    // 2 Na2O(s) + O2(g) -> 2 Na2O2(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/platinum/sodium_peroxide')
        .inputFluids('1000x gtceu:oxygen')
        .itemInputs('3x gtceu:sodium_oxide_dust')
        .itemOutputs('4x gtceu:sodium_peroxide_dust')
        .circuit(3)
        .duration(60)
        .EUt(GTValues.V[GTValues.MV], 2)
    // 2 NaC2H3O2(s) -> 2 Na(s) + 4 C(s) + 3 H2(g) + 2 O2(g)
    event.recipes.gtceu.electrolyzer('frontiers:chains/platinum/sodium_acetate_decomposition')
        .itemInputs('8x gtceu:sodium_acetate_dust')
        .itemOutputs('2x gtceu:carbon_dust', 'gtceu:sodium_dust')
        .outputFluids('2000x gtceu:oxygen', '3000x gtceu:hydrogen')
        .duration(240)
        .EUt(GTValues.V[GTValues.MV], 4)
    // (OsO4)(NaCl)(s) -> OsO4(s) + NaCl(s)
    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/platinum/pure_osmium_tetroxide')
        .itemInputs('7x gtceu:impure_osmium_tetroxide_dust')
        .notConsumableFluid('1000x gtceu:carbon_tetrachloride')
        .itemOutputs('5x gtceu:osmium_tetroxide_dust', '2x gtceu:salt_dust')
        .duration(120)
        .EUt(GTValues.V[GTValues.EV], 2)
    // 2 OsO4(s) + 5 NaOH(s) + C2H6O(l) -> 2 Na2OsO2(OH)4(s) + NaC2H3O2(s)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/sodium_osmate')
        .itemInputs('10x gtceu:osmium_tetroxide_dust', '15x gtceu:sodium_hydroxide_dust')
        .inputFluids('1000x gtceu:ethanol')
        .itemOutputs('20x gtceu:sodium_osmate_dust', '8x gtceu:sodium_acetate_dust')
        .duration(240)
        .EUt(GTValues.V[GTValues.EV], 2)
    // Na2OsO2(OH)4(s) + 4 NH4Cl(s) -> (NH3)4(OsO2)Cl2(s) + 2 NaCl(s) + 4 H2O(l)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/tetraammine_osmyl_chloride')
        .itemInputs('10x gtceu:sodium_osmate_dust', '8x gtceu:ammonium_chloride_dust')
        .itemOutputs('9x gtceu:tetraammine_osmyl_chloride_dust', '4x gtceu:salt_dust')
        .outputFluids('4000x minecraft:water')
        .duration(120)
        .EUt(GTValues.V[GTValues.IV], 2)
    // (NH3)4(OsO2)Cl2(s) + 3 H2(g) -> Os(s) + 2 HCl(aq) + 4 NH3(g) + 2 H2O(l)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/platinum/osmium_reduction')
        .itemInputs('9x gtceu:tetraammine_osmyl_chloride_dust')
        .inputFluids('6000x gtceu:hydrogen')
        .itemOutputs('gtceu:osmium_dust')
        .outputFluids('2000x gtceu:hydrochloric_acid', '4000x gtceu:ammonia', '2000x minecraft:water')
        .duration(60)
        .EUt(GTValues.V[GTValues.LuV], 1)
})
