ServerEvents.recipes(event => {
    event.remove({id: 'gtceu:electrolyzer/decomposition_electrolyzing_tantalite'})
    event.recipes.gtceu.electrolyzer("tantalite_electro_bad")
        .itemInputs('36x gtceu:small_tantalite_dust')
        .itemOutputs('2x gtceu:tiny_tantalum_dust')
        .itemOutputs('1x gtceu:small_manganese_dust')
        .outputFluids('gtceu:oxygen 6000')
        .duration(432)
        .EUt(60)

    event.recipes.gtceu.electrolyzer("tantalite_electro")
        .itemInputs('9x gtceu:tantalite_dust')
        .chancedInput('1x gtceu:carbon_rod', 100, 0)
        .inputFluids('gtceu:salt 1000')
        .itemOutputs('2x gtceu:tantalum_dust')
        .itemOutputs('1x gtceu:manganese_dust')
        .outputFluids('gtceu:salt 990')
        .outputFluids('gtceu:oxygen 6000')
        .duration(156)
        .EUt(GTValues.VA[GTValues.HV])
})