ServerEvents.recipes(event => {
    //KeTbSO2 + 2H2SO4 + 5HCl -> (KeO4Cl2)(2H2O) + ((TbS2O)(2H2O)(SOHCl3)) 
    event.recipes.gtceu.chemical_reactor('trinium_metallic_decomp')
    .itemInputs('6x gtceu:trinium_metallic_dust')
    .inputFluids('gtceu:sulfuric_acid 2000')
    .inputFluids('gtceu:hydrochloric_acid 5000')
    .outputFluids('gtceu:trinium_calx_solution 8000')
    .outputFluids('gtceu:vitrolic_slurry 1000')
    .duration(300)
    .EUt(GTValues.VA[GTValues.ZPM]);
    //(KeO4Cl2)(2H2O) + 5H2 -> Ke +4H2O (VOIDED) + 2HCL (RETURNED)
    event.recipes.gtceu.chemical_dehydrator('trinium_calx_processing')
    .inputFluids('gtceu:trinium_calx_solution 8000')
    .inputFluids('gtceu:hydrogen 10000')
    .itemOutputs('2x gtceu:trinium_dust')
    .outputFluids('gtceu:hydrochloric_acid 2000')
    .duration(600)
    .EUt(GTValues.VA[GTValues.UV])

    //(TbS2O)(SOHCl3) -> TbS2O + SOHCl3
    event.recipes.gtceu.centrifuge('vitrolic_slurry_centrifuge')
    .inputFluids('gtceu:vitrolic_slurry 1000')
    .itemOutputs('gtceu:terbium_dust')
    .itemOutputs('3x gtceu:sulfur_dust')
    .outputFluids('gtceu:oxygen 2000')
    .outputFluids('gtceu:hydrochloric_acid 3000')
    .duration(500)
    .EUt(GTValues.VA[GTValues.LuV])
})