ServerEvents.recipes(event => {
    event.remove({ id: 'gtceu:electrolyzer/tungstic_acid_electrolysis' })
    event.remove({ id: 'gtceu:chemical_bath/tungstic_acid_from_tungstate' })
    event.remove({ id: 'gtceu:chemical_bath/tungstic_acid_from_scheelite' })
    event.remove({ id: 'occultism:crushing/tungsten_dust_from_ore' })
    event.remove({ id: 'occultism:crushing/tungsten_dust_from_raw' })
    event.remove({ id: 'occultism:crushing/tungsten_dust_from_raw_block' })
    event.recipes.gtceu.distillery('frontiers:chains/tungsten/ammonium_hydroxide_from_aerocloud')
        .inputFluids('2000x gtceu:ammonia_rich_aerocloud_solution')
        .outputFluids('1000x gtceu:ammonium_hydroxide')
        .circuit(1)
        .duration(30)
        .EUt(GTValues.V[GTValues.MV], 2)
    // NH3(g) + H2O(l) -> NH4OH(aq)
    event.recipes.gtceu.mixer('frontiers:chains/tungsten/ammonium_hydroxide')
        .inputFluids('1000x gtceu:ammonia', '1000x minecraft:water')
        .outputFluids('1000x gtceu:ammonium_hydroxide')
        .circuit(1)
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)
    // FeWO4(s) + MnWO4(s) + 4 NaOH(s) + 2 H2O(l) -> 2 Na2WO4.H2O(aq) + Fe(OH)2(s) + Mn(OH)2(s)
    event.recipes.gtceu.autoclave('frontiers:chains/tungsten/wolframite_to_impure_sodium_tungstate')
        .itemInputs('12x gtceu:wolframite_dust', '12x gtceu:sodium_hydroxide_dust')
        .inputFluids('2000x minecraft:water')
        .itemOutputs('5x gtceu:iron_hydroxide_dust', '5x gtceu:manganese_hydroxide_dust')
        .outputFluids('2000x gtceu:impure_sodium_tungstate_solution')
        .duration(300)
        .EUt(GTValues.V[GTValues.EV], 2)
    // CaWO4(s) + Na2CO3(s) + H2O(l) -> Na2WO4.H2O(aq) + CaCO3(s)
    event.recipes.gtceu.autoclave('frontiers:chains/tungsten/scheelite_to_impure_sodium_tungstate')
        .itemInputs('6x gtceu:scheelite_dust', '6x gtceu:soda_ash_dust')
        .inputFluids('1000x minecraft:water')
        .itemOutputs('5x gtceu:calcite_dust')
        .outputFluids('1000x gtceu:impure_sodium_tungstate_solution')
        .duration(200)
        .EUt(GTValues.V[GTValues.EV], 2)
    // Li2WO4(s) + 2 NaOH(s) + H2O(l) -> Na2WO4.H2O(aq) + 2 LiOH(s)
    event.recipes.gtceu.autoclave('frontiers:chains/tungsten/tungstate_to_impure_sodium_tungstate')
        .itemInputs('7x gtceu:tungstate_dust', '6x gtceu:sodium_hydroxide_dust')
        .inputFluids('1000x minecraft:water')
        .itemOutputs('6x gtceu:lithium_hydroxide_dust')
        .outputFluids('1000x gtceu:impure_sodium_tungstate_solution')
        .duration(200)
        .EUt(GTValues.V[GTValues.EV], 2)
    // Na2WO4.H2O(aq) + Mo(s) + 4 Na2S(s) + 6 H2O(l) -> Na2WO4.H2O(aq) + Na2MoS4(s) + 6 NaOH(s) + 3 H2(g)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/tungsten/sodium_tungstate_purification')
        .itemInputs('12x gtceu:sodium_sulfide_dust')
        .inputFluids('1000x gtceu:impure_sodium_tungstate_solution', '6000x minecraft:water')
        .itemOutputs('7x gtceu:sodium_molybdenum_sulfide_dust', '18x gtceu:sodium_hydroxide_dust')
        .outputFluids('1000x gtceu:sodium_tungstate_solution', '6000x gtceu:hydrogen')
        .duration(100)
        .EUt(GTValues.V[GTValues.EV], 2)
    // 12 Na2WO4.H2O(aq) + 10 (C8H17)3N(l) + 6 H2O(l) -> [(C8H17)3NH]10H2W12O42(l) + 24 NaOH(s)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/tungsten/trioctylammonium_isopolytungstate')
        .inputFluids('6000x gtceu:sodium_tungstate_solution', '5000x gtceu:trioctylamine', '9000x minecraft:water')
        .itemOutputs('36x gtceu:sodium_hydroxide_dust')
        .outputFluids('500x gtceu:trioctylammonium_isopolytungstate')
        .duration(900)
        .EUt(GTValues.V[GTValues.HV], 4)
    // [(C8H17)3NH]10H2W12O42(l) + 10 NH4OH(aq) -> (NH4)10H2W12O42.4H2O(s) + 10 (C8H17)3N(l) + 6 H2O(l)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/tungsten/ammonium_paratungstate')
        .inputFluids('500x gtceu:trioctylammonium_isopolytungstate', '5000x gtceu:ammonium_hydroxide')
        .itemOutputs('2x gtceu:ammonium_paratungstate_dust')
        .outputFluids('5000x gtceu:trioctylamine', '3000x minecraft:water')
        .duration(275)
        .EUt(GTValues.V[GTValues.EV], 2)
    // (NH4)10H2W12O42.4H2O(s) + 2 H2O(l) -> 12 H2WO4(s) + 10 NH3(g)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/tungsten/tungstic_acid')
        .itemInputs('gtceu:ammonium_paratungstate_dust')
        .inputFluids('500x minecraft:water')
        .itemOutputs('21x gtceu:tungstic_acid_dust')
        .outputFluids('2500x gtceu:ammonia')
        .blastFurnaceTemp(3600)
        .duration(250)
        .EUt(GTValues.V[GTValues.EV], 1)
    // H2WO4(s) -> WO3(s) + H2O(l)
    event.recipes.cosmiccore.chemical_dehydrator('frontiers:chains/tungsten/tungsten_trioxide')
        .itemInputs('7x gtceu:tungstic_acid_dust')
        .itemOutputs('4x gtceu:tungsten_trioxide_dust')
        .outputFluids('1000x minecraft:water')
        .duration(250)
        .EUt(GTValues.V[GTValues.EV], 4)
    // WO3(s) + 3 H2(g) -> W(s) + 3 H2O(g)
    event.recipes.gtceu.electric_blast_furnace('frontiers:chains/tungsten/tungsten_reduction')
        .itemInputs('4x gtceu:tungsten_trioxide_dust')
        .inputFluids('6000x gtceu:hydrogen')
        .itemOutputs('gtceu:tungsten_dust')
        .outputFluids('3000x gtceu:steam')
        .blastFurnaceTemp(3700)
        .duration(250)
        .EUt(GTValues.V[GTValues.EV], 1)
    // Na2MoS4(s) + H2SO4(aq) -> MoS3(s) + Na2SO4(s) + H2S(g)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/tungsten/molybdenum_trisulfide')
        .itemInputs('7x gtceu:sodium_molybdenum_sulfide_dust')
        .inputFluids('1000x gtceu:sulfuric_acid')
        .itemOutputs('4x gtceu:molybdenum_trisulfide_dust', '7x gtceu:sodium_sulfate_dust')
        .outputFluids('1000x gtceu:hydrogen_sulfide')
        .duration(60)
        .EUt(GTValues.V[GTValues.HV], 2)
    // MoS3(s) -> Mo(s) + 3 S(s)
    event.recipes.gtceu.electrolyzer('frontiers:chains/tungsten/molybdenum_trisulfide_decomposition')
        .itemInputs('4x gtceu:molybdenum_trisulfide_dust')
        .itemOutputs('gtceu:molybdenum_dust', '3x gtceu:sulfur_dust')
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)
    // 2 LiOH(s) -> 2 Li(s) + H2(g) + O2(g)
    event.recipes.gtceu.electrolyzer('frontiers:chains/tungsten/lithium_hydroxide_recovery')
        .itemInputs('3x gtceu:lithium_hydroxide_dust')
        .itemOutputs('gtceu:lithium_dust')
        .outputFluids('1000x gtceu:oxygen', '1000x gtceu:hydrogen')
        .duration(150)
        .EUt(GTValues.V[GTValues.MV], 2)
    // 2 Al(s) + 6 C2H4(g) + 3 H2(g) -> 2 Al(C2H5)3(l)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/tungsten/triethylaluminium')
        .itemInputs('gtceu:aluminium_dust')
        .inputFluids('3000x gtceu:hydrogen', '3000x gtceu:ethylene')
        .outputFluids('1000x gtceu:triethylaluminium')
        .duration(70)
        .EUt(GTValues.V[GTValues.HV], 2)
    // Al(C2H5)3(l) + 9 C2H4(g) -> Al(C8H17)3(l)
    event.recipes.gtceu.large_chemical_reactor('frontiers:chains/tungsten/trioctylaluminium')
        .inputFluids('1000x gtceu:triethylaluminium', '9000x gtceu:ethylene')
        .outputFluids('1000x gtceu:trioctylaluminium')
        .duration(60)
        .EUt(GTValues.V[GTValues.HV], 2)
    // 2 Al(C8H17)3(l) + 3 O2(g) + 6 H2O(l) -> 6 C8H18O(l) + 2 Al(OH)3(s)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/tungsten/octanol')
        .inputFluids('1000x gtceu:trioctylaluminium', '3000x gtceu:oxygen', '3000x minecraft:water')
        .itemOutputs('7x gtceu:aluminium_hydroxide_dust')
        .outputFluids('3000x gtceu:one_dash_octanol')
        .duration(30)
        .EUt(GTValues.V[GTValues.HV], 2)
    // 3 C8H18O(l) + NH3(g) -> (C8H17)3N(l) + 3 H2O(l)
    event.recipes.gtceu.chemical_reactor('frontiers:chains/tungsten/trioctylamine')
        .inputFluids('3000x gtceu:one_dash_octanol', '1000x gtceu:ammonia')
        .notConsumableItem('32x gtceu:nickel_dust')
        .outputFluids('1000x gtceu:trioctylamine', '3000x minecraft:water')
        .duration(60)
        .EUt(GTValues.V[GTValues.EV], 2)
    event.recipes.gtceu.macerator('frontiers:chains/tungsten/finely_ground_wolframite')
        .itemInputs('gtceu:wolframite_dust')
        .itemOutputs('gtceu:finely_ground_wolframite_dust')
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)
    event.recipes.gtceu.macerator('frontiers:chains/tungsten/finely_ground_scheelite')
        .itemInputs('gtceu:scheelite_dust')
        .itemOutputs('gtceu:finely_ground_scheelite_dust')
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)
    event.recipes.gtceu.macerator('frontiers:chains/tungsten/finely_ground_tungstate')
        .itemInputs('gtceu:tungstate_dust')
        .itemOutputs('gtceu:finely_ground_tungstate_dust')
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)
    // FeWO4(s) + MnWO4(s) + 4 HCl(aq) -> 2 H2WO4(s) + FeCl2(l) + MnCl2(l)
    event.recipes.cosmiccore.industrial_chemvat('frontiers:chains/tungsten/optimized_wolframite')
        .itemInputs('12x gtceu:finely_ground_wolframite_dust')
        .inputFluids('4000x gtceu:hydrochloric_acid')
        .itemOutputs('14x gtceu:tungstic_acid_dust')
        .outputFluids('1000x gtceu:iron_ii_chloride', '1000x gtceu:manganese_ii_chloride')
        .stationResearch(b => b.researchStack('gtceu:ultradense_tungsten_plate').CWUt(16).EUt(GTValues.V[GTValues.ZPM], 1))
        .duration(120)
        .EUt(GTValues.V[GTValues.IV], 2)
    // CaWO4(s) + 2 HCl(aq) -> H2WO4(s) + CaCl2(s)
    event.recipes.cosmiccore.industrial_chemvat('frontiers:chains/tungsten/optimized_scheelite')
        .itemInputs('6x gtceu:finely_ground_scheelite_dust')
        .inputFluids('2000x gtceu:hydrochloric_acid')
        .itemOutputs('7x gtceu:tungstic_acid_dust', '3x gtceu:calcium_chloride_dust')
        .stationResearch(b => b.researchStack('gtceu:ultradense_tungsten_plate').CWUt(16).EUt(GTValues.V[GTValues.ZPM], 1))
        .duration(120)
        .EUt(GTValues.V[GTValues.IV], 2)
    // Li2WO4(s) + 2 HCl(aq) -> H2WO4(s) + 2 LiCl(s)
    event.recipes.cosmiccore.industrial_chemvat('frontiers:chains/tungsten/optimized_tungstate')
        .itemInputs('7x gtceu:finely_ground_tungstate_dust')
        .inputFluids('2000x gtceu:hydrochloric_acid')
        .itemOutputs('7x gtceu:tungstic_acid_dust', '4x gtceu:lithium_chloride_dust')
        .stationResearch(b => b.researchStack('gtceu:ultradense_tungsten_plate').CWUt(16).EUt(GTValues.V[GTValues.ZPM], 1))
        .duration(120)
        .EUt(GTValues.V[GTValues.IV], 2)
    // H2WO4(s) + 3 H2(g) -> W(s) + 4 H2O(g)
    event.recipes.cosmiccore.industrial_chemvat('frontiers:chains/tungsten/optimized_tungsten_reduction')
        .itemInputs('7x gtceu:tungstic_acid_dust')
        .inputFluids('6000x gtceu:hydrogen')
        .itemOutputs('gtceu:tungsten_dust')
        .outputFluids('4000x gtceu:steam')
        .stationResearch(b => b.researchStack('gtceu:ultradense_tungsten_plate').CWUt(16).EUt(GTValues.V[GTValues.ZPM], 1))
        .duration(60)
        .EUt(GTValues.V[GTValues.IV], 2)
})
