ServerEvents.recipes(event => {

    // H2 + Br2 -> 2 HBr
    event.recipes.gtceu.chemical_reactor('hydrobromic_acid')
        .inputFluids('gtceu:hydrogen 1000')
        .inputFluids('gtceu:bromine 1000')
        .outputFluids('gtceu:hydrobromic_acid 2000')
        .duration(60)
        .EUt(GTValues.VA[GTValues.EV])

    // 2 C6H5OH + 2 KOH + 2 CO2 + H2SO4 -> 2 C7H6O3 + K2SO4 + 2 H2O
    event.recipes.gtceu.large_chemical_reactor('hydroxybenzoic_acid')
        .inputFluids('gtceu:phenol 2000')
        .inputFluids('gtceu:carbon_dioxide 2000')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .itemInputs('6x gtceu:potassium_hydroxide_dust')
        .outputFluids('gtceu:hydroxybenzoic_acid 2000')
        .itemOutputs('7x gtceu:potassium_sulfate_dust')
        .outputFluids('minecraft:water 2000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.EV])

    // C10H8 + 3 KOH + H2SO4 + SO2 -> C10H7OK + K2S2O5 + 3 H2O
    event.recipes.gtceu.chemical_reactor('potassium_naphthoxide')
        .inputFluids('gtceu:naphthalene 1000')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .inputFluids('gtceu:sulfur_dioxide 1000')
        .itemInputs('9x gtceu:potassium_hydroxide_dust')
        .outputFluids('gtceu:potassium_naphthoxide 1000')
        .itemOutputs('9x gtceu:potassium_metabisulfite_dust')
        .outputFluids('minecraft:water 3000')
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])

    // 2 C10H7OK + 2 CO2 + H2SO4 -> 2 C11H8O3 + K2SO4 (Pd/Sn/HBr/H2 catalysts)
    event.recipes.gtceu.large_chemical_reactor('hydroxynaphtoic_acid')
        .inputFluids('gtceu:potassium_naphthoxide 2000')
        .inputFluids('gtceu:carbon_dioxide 2000')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .notConsumable('gtceu:palladium_dust')
        .notConsumable('gtceu:tin_dust')
        .notConsumable('gtceu:white_lamp')
        .notConsumableFluid('gtceu:hydrobromic_acid 1000')
        .notConsumableFluid('gtceu:hydrogen 1000')
        .outputFluids('gtceu:hydroxynaphtoic_acid 2000')
        .itemOutputs('7x gtceu:potassium_sulfate_dust')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])

    // C7H6O3 + C11H8O3 -> C18H12O5 + H2O (condensation polymerization)
    event.recipes.gtceu.polymerizer('vectran')
        .inputFluids('gtceu:hydroxybenzoic_acid 1000')
        .inputFluids('gtceu:hydroxynaphtoic_acid 1000')
        .outputFluids('gtceu:vectran 1000')
        .outputFluids('minecraft:water 1000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])

})
