ServerEvents.recipes(event => {
    event.recipes.gtceu.distillation_tower('frontiers:petrochem/aromatic_oil_fractionation')
        .inputFluids('4000x cosmiccore:aromatic_oil')
        .outputFluids(['1250x gtceu:benzene', '1150x gtceu:toluene', '1000x gtceu:mixed_xylenes', '600x gtceu:ethylbenzene'])
        .duration(120)
        .EUt(240)

    event.recipes.gtceu.large_chemical_reactor('frontiers:petrochem/mixed_xylenes_phthalic_acid')
        .itemInputs('gtceu:tiny_potassium_dichromate_dust')
        .inputFluids(['1000x gtceu:mixed_xylenes', '2000x gtceu:oxygen'])
        .outputFluids(['1000x gtceu:phthalic_acid', '2000x minecraft:water'])
        .circuit(4)
        .duration(100)
        .EUt(1920)

    event.recipes.gtceu.large_chemical_reactor('frontiers:petrochem/mixed_xylenes_phthalic_acid_bulk')
        .itemInputs('gtceu:potassium_dichromate_dust')
        .inputFluids(['9000x gtceu:mixed_xylenes', '18000x gtceu:oxygen'])
        .outputFluids(['9000x gtceu:phthalic_acid', '18000x minecraft:water'])
        .circuit(9)
        .duration(450)
        .EUt(1920)

    event.recipes.cosmiccore.catalytic_reforming('frontiers:petrochem/toluene_disproportionation')
        .itemInputs('16x cosmiccore:purple_zeolite_catalyst')
        .inputFluids('4000x gtceu:toluene')
        .itemOutputs(['15x cosmiccore:purple_zeolite_catalyst', 'cosmiccore:coked_purple_zeolite_catalyst'])
        .outputFluids(['2000x gtceu:benzene', '2000x gtceu:mixed_xylenes'])
        .duration(200)
        .EUt(480)
})
