ServerEvents.recipes(event => {
    event.recipes.gtceu.autoclave('frontiers:blue_hydro_catalyst')
        .itemInputs('8x cosmiccore:yellow_hydro_catalyst')
        .inputFluids('1000x gtceu:hydrogen')
        .itemOutputs('8x cosmiccore:blue_hydro_catalyst')
        .outputFluids('1000x gtceu:hydrogen_sulfide')
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.fluid_catalytic_cracking('frontiers:petrochem/purple_zeolite_catalyst_regeneration')
        .itemInputs('16x cosmiccore:coked_purple_zeolite_catalyst')
        .inputFluids('4000x gtceu:oxygen')
        .itemOutputs('16x cosmiccore:purple_zeolite_catalyst')
        .outputFluids('4000x gtceu:carbon_dioxide')
        .duration(100)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.gtceu.electric_blast_furnace('frontiers:orange_recovery_catalyst')
        .itemInputs('8x cosmiccore:depleted_orange_recovery_catalyst')
        .inputFluids('1000x gtceu:oxygen')
        .itemOutputs('8x cosmiccore:orange_recovery_catalyst')
        .outputFluids('1000x gtceu:carbon_dioxide')
        .blastFurnaceTemp(1200)
        .duration(240)
        .EUt(GTValues.V[GTValues.HV], 2)
})
