ServerEvents.recipes(event => {
    event.recipes.cosmiccore.fluid_catalytic_cracking('frontiers:petrochem/gas_oil_fcc')
        .itemInputs('16x cosmiccore:purple_zeolite_catalyst')
        .inputFluids('4000x gtceu:gas_oils')
        .itemOutputs('16x cosmiccore:coked_purple_zeolite_catalyst')
        .outputFluids(['600x gtceu:refinery_gas', '2200x cosmiccore:cracked_gasoline', '900x cosmiccore:light_cycle_oil', '300x cosmiccore:slurry_oils'])
        .duration(160)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.fluid_catalytic_cracking('frontiers:petrochem/vacuum_gas_oil_fcc')
        .itemInputs('16x cosmiccore:purple_zeolite_catalyst')
        .inputFluids('4000x cosmiccore:vacuum_gas_oils')
        .itemOutputs('16x cosmiccore:coked_purple_zeolite_catalyst')
        .outputFluids(['400x gtceu:refinery_gas', '1800x cosmiccore:cracked_gasoline', '1100x cosmiccore:light_cycle_oil', '700x cosmiccore:slurry_oils'])
        .duration(140)
        .EUt(GTValues.V[GTValues.EV], 2)

    event.recipes.cosmiccore.hydrocracking('frontiers:petrochem/gas_oil_hydrocracking')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x gtceu:gas_oils', '4000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['800x gtceu:refinery_gas', '1200x gtceu:light_naphtha', '800x cosmiccore:heavy_naphtha', '1200x gtceu:middle_fraction_distillates'])
        .duration(180)
        .EUt(GTValues.V[GTValues.EV], 2)

    event.recipes.cosmiccore.hydrocracking('frontiers:petrochem/vacuum_gas_oil_hydrocracking')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x cosmiccore:vacuum_gas_oils', '6000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['500x gtceu:refinery_gas', '1300x gtceu:light_naphtha', '800x cosmiccore:heavy_naphtha', '1400x gtceu:middle_fraction_distillates', '500x gtceu:hydrogen_sulfide'])
        .duration(280)
        .EUt(GTValues.V[GTValues.EV], 8)

    event.recipes.cosmiccore.catalytic_reforming('frontiers:petrochem/heavy_naphtha_catalytic_reforming')
        .itemInputs('16x cosmiccore:orange_recovery_catalyst')
        .inputFluids('4000x cosmiccore:heavy_naphtha')
        .itemOutputs(['15x cosmiccore:orange_recovery_catalyst', 'cosmiccore:depleted_orange_recovery_catalyst'])
        .outputFluids(['3050x cosmiccore:high_octane_reformate', '600x cosmiccore:aromatic_oil', '150x gtceu:hydrogen', '200x gtceu:refinery_gas'])
        .duration(180)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.hydrocracking('frontiers:petrochem/middle_distillate_hydrocracking')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['8000x gtceu:middle_fraction_distillates', '3000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['3200x gtceu:light_naphtha', '1600x gtceu:refinery_gas', '1200x gtceu:ethane', '1200x gtceu:propane', '800x gtceu:butane'])
        .duration(240)
        .EUt(GTValues.V[GTValues.EV], 2)

    event.recipes.cosmiccore.fluid_catalytic_cracking('frontiers:petrochem/middle_distillate_catalytic_cracking')
        .itemInputs('16x cosmiccore:purple_zeolite_catalyst')
        .inputFluids('8000x gtceu:middle_fraction_distillates')
        .itemOutputs('16x cosmiccore:coked_purple_zeolite_catalyst')
        .outputFluids(['2400x cosmiccore:cracked_gasoline', '2800x cosmiccore:olefin_gases', '1600x cosmiccore:light_cycle_oil', '1200x cosmiccore:slurry_oils'])
        .duration(180)
        .EUt(GTValues.V[GTValues.HV], 4)
})
