ServerEvents.recipes(event => {
    event.recipes.gtceu.pyrolyse_oven('frontiers:coke_gem')
        .itemInputs('16x minecraft:coal')
        .itemOutputs('16x gtceu:coke_gem')
        .outputFluids('8000x cosmiccore:hot_coking_vapors')
        .duration(320)
        .EUt(GTValues.V[GTValues.MV], 4)

    event.recipes.cosmiccore.fractional_condenser('frontiers:petrochem/hot_coking_vapor_condensation')
        .inputFluids('8000x cosmiccore:hot_coking_vapors')
        .outputFluids(['4400x gtceu:raw_coking_gas', '2400x gtceu:coal_tar', '1200x cosmiccore:ammonia_rich_liquor'])
        .duration(120)
        .EUt(GTValues.V[GTValues.MV], 4)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/raw_coking_gas_aromatic_wash')
        .inputFluids('4400x gtceu:raw_coking_gas')
        .outputFluids(['4000x gtceu:sour_refinery_gas', '400x cosmiccore:aromatic_oil'])
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:light_tar_oils/from_coal_tar')
        .inputFluids('2400x gtceu:coal_tar')
        .outputFluids(['600x cosmiccore:light_tar_oils', '400x cosmiccore:phenolic_oils', '900x cosmiccore:naphthalene_oils', '500x cosmiccore:tar_pitch'])
        .duration(80)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/ammonia_rich_liquor_separation')
        .inputFluids('1200x cosmiccore:ammonia_rich_liquor')
        .outputFluids(['200x gtceu:ammonia', '1000x cosmiccore:sour_process_water'])
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:naphthalene')
        .inputFluids('900x cosmiccore:naphthalene_oils')
        .outputFluids(['600x gtceu:naphthalene', '300x cosmiccore:tar_pitch'])
        .duration(60)
        .EUt(GTValues.V[GTValues.MV], 2)
})
