ServerEvents.recipes(event => {
    event.recipes.gtceu.distillery('frontiers:petrochem/light_oil_middle_distillate_recovery')
        .inputFluids('8000x gtceu:light_oil')
        .outputFluids('5200x gtceu:middle_fraction_distillates')
        .circuit(1)
        .duration(80)
        .EUt(24)

    event.recipes.gtceu.distillery('frontiers:petrochem/oil_middle_distillate_recovery')
        .inputFluids('4000x gtceu:oil')
        .outputFluids('2000x gtceu:middle_fraction_distillates')
        .circuit(1)
        .duration(80)
        .EUt(24)

    event.recipes.gtceu.distillery('frontiers:petrochem/oil_gas_oil_recovery')
        .inputFluids('2000x gtceu:oil')
        .outputFluids('600x gtceu:gas_oils')
        .circuit(2)
        .duration(180)
        .EUt(24)

    event.recipes.gtceu.distillery('frontiers:petrochem/heavy_oil_gas_oil_recovery')
        .inputFluids('1000x gtceu:heavy_oil')
        .outputFluids('700x gtceu:gas_oils')
        .circuit(2)
        .duration(160)
        .EUt(60)

    event.recipes.gtceu.distillation_tower('frontiers:petrochem/light_oil_atmospheric_fractionation')
        .inputFluids('8000x gtceu:light_oil')
        .outputFluids(['2400x gtceu:sour_refinery_gas', '2400x gtceu:sour_naphtha', '2000x gtceu:sour_middle_fraction_distillates', '800x gtceu:sour_gas_oils', '400x cosmiccore:atmospheric_residue'])
        .disableDistilleryRecipes(true)
        .duration(160)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.distillation_tower('frontiers:petrochem/oil_atmospheric_fractionation')
        .inputFluids('8000x gtceu:oil')
        .outputFluids(['1200x gtceu:sour_refinery_gas', '2000x gtceu:sour_naphtha', '2400x gtceu:sour_middle_fraction_distillates', '1600x gtceu:sour_gas_oils', '800x cosmiccore:atmospheric_residue'])
        .disableDistilleryRecipes(true)
        .duration(200)
        .EUt(240)

    event.recipes.gtceu.distillation_tower('frontiers:petrochem/heavy_oil_atmospheric_fractionation')
        .inputFluids('8000x gtceu:heavy_oil')
        .outputFluids(['400x gtceu:sour_refinery_gas', '800x gtceu:sour_naphtha', '1200x gtceu:sour_middle_fraction_distillates', '2800x gtceu:sour_gas_oils', '2800x cosmiccore:atmospheric_residue'])
        .disableDistilleryRecipes(true)
        .duration(240)
        .EUt(360)

    event.recipes.cosmiccore.vacuum_distillation('frontiers:petrochem/atmospheric_residue_vacuum_distillation')
        .inputFluids('8000x cosmiccore:atmospheric_residue')
        .outputFluids(['4400x cosmiccore:vacuum_gas_oils', '1200x cosmiccore:waxy_distillates', '2400x cosmiccore:vacuum_residuals'])
        .circuit(20)
        .duration(250)
        .EUt(320)
})
