ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_reactor('frontiers:petrochem/ethylene_oxide_synthesis')
        .notConsumableItem('gtceu:silver_dust')
        .inputFluids(['1000x gtceu:ethylene', '1000x gtceu:oxygen'])
        .outputFluids('1000x gtceu:ethylene_oxide')
        .circuit(1)
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('frontiers:petrochem/ethanolamine_synthesis')
        .inputFluids(['1000x gtceu:ethylene_oxide', '1000x gtceu:ammonia'])
        .outputFluids('1000x gtceu:ethanolamine')
        .circuit(2)
        .duration(160)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.mixer('frontiers:petrochem/lean_amine_solution_makeup')
        .inputFluids(['1000x gtceu:ethanolamine', '4000x gtceu:distilled_water'])
        .outputFluids('5000x cosmiccore:lean_amine_solution')
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.centrifuge('frontiers:petrochem/simple_sour_process_water_stripping')
        .inputFluids('4000x cosmiccore:sour_process_water')
        .outputFluids(['4000x gtceu:distilled_water', '400x gtceu:hydrogen_sulfide'])
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.large_chemical_reactor('frontiers:petrochem/sour_refinery_gas_amine_scrubbing')
        .inputFluids(['4000x gtceu:sour_refinery_gas', '2000x cosmiccore:lean_amine_solution'])
        .outputFluids(['3800x gtceu:refinery_gas', '2000x cosmiccore:rich_amine_solution', '200x cosmiccore:sour_process_water'])
        .duration(160)
        .EUt(240)

    event.recipes.gtceu.distillation_tower('frontiers:petrochem/rich_amine_solution_regeneration')
        .inputFluids(['4000x cosmiccore:rich_amine_solution', '1000x gtceu:steam'])
        .outputFluids(['3600x cosmiccore:lean_amine_solution', '800x cosmiccore:acidic_gases', '600x cosmiccore:sour_process_water'])
        .duration(200)
        .EUt(240)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/deep_sour_process_water_stripping')
        .inputFluids(['4000x cosmiccore:sour_process_water', '1000x gtceu:steam'])
        .outputFluids(['4000x gtceu:distilled_water', '400x gtceu:hydrogen_sulfide', '200x gtceu:ammonia', '400x cosmiccore:acidic_gases'])
        .circuit(2)
        .duration(160)
        .EUt(240)

    event.recipes.gtceu.large_chemical_reactor('frontiers:petrochem/acidic_gas_sulfur_recovery')
        .inputFluids(['4000x cosmiccore:acidic_gases', '1000x gtceu:oxygen'])
        .itemOutputs('2x gtceu:sulfur_dust')
        .outputFluids(['2500x cosmiccore:tail_gas', '2000x gtceu:distilled_water'])
        .duration(240)
        .EUt(360)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/tail_gas_recovery')
        .inputFluids('4000x cosmiccore:tail_gas')
        .outputFluids(['2000x gtceu:refinery_gas', '1000x gtceu:hydrogen', '1000x cosmiccore:acidic_gases'])
        .circuit(3)
        .duration(120)
        .EUt(320)

    event.recipes.gtceu.large_chemical_reactor('frontiers:petrochem/hydrogen_sulfide_claus_recovery')
        .inputFluids(['4000x gtceu:hydrogen_sulfide', '2000x gtceu:oxygen'])
        .itemOutputs('4x gtceu:sulfur_dust')
        .outputFluids('4000x gtceu:distilled_water')
        .duration(40)
        .EUt(360)
})
