ServerEvents.recipes(event => {
    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/sour_naphtha_hydrotreating')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x gtceu:sour_naphtha', '1000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['2400x gtceu:light_naphtha', '1600x cosmiccore:heavy_naphtha', '500x gtceu:hydrogen_sulfide'])
        .duration(120)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/sour_middle_distillate_hydrotreating')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x gtceu:sour_middle_fraction_distillates', '1000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['4000x gtceu:middle_fraction_distillates', '500x gtceu:hydrogen_sulfide'])
        .duration(130)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/sour_gas_oil_hydrotreating')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x gtceu:sour_gas_oils', '1500x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['4000x gtceu:gas_oils', '750x gtceu:hydrogen_sulfide'])
        .duration(150)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/cracked_naphtha_hydrotreating')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x cosmiccore:cracked_naphtha', '1500x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['4000x gtceu:light_naphtha', '250x gtceu:hydrogen_sulfide'])
        .duration(180)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/cracked_gasoline_hydrotreating')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x cosmiccore:cracked_gasoline', '1000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['4000x gtceu:raw_gasoline', '250x gtceu:hydrogen_sulfide'])
        .duration(200)
        .EUt(GTValues.V[GTValues.HV], 4)

    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/light_cycle_oil_hydrotreating')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x cosmiccore:light_cycle_oil', '2000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['4000x gtceu:middle_fraction_distillates', '500x gtceu:hydrogen_sulfide'])
        .duration(220)
        .EUt(GTValues.V[GTValues.HV], 8)

    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/waxy_distillate_hydrofinishing')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x cosmiccore:waxy_distillates', '1000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids(['4000x gtceu:lubricant', '500x gtceu:hydrogen_sulfide'])
        .circuit(21)
        .duration(180)
        .EUt(GTValues.V[GTValues.HV], 2)
})
