ServerEvents.recipes(event => {
    event.recipes.cosmiccore.fractional_condenser('frontiers:petrochem/refinery_gas_condensation')
        .inputFluids('8000x gtceu:refinery_gas')
        .outputFluids('8000x cosmiccore:condensed_refinery_gas')
        .duration(100)
        .EUt(480)

    event.recipes.gtceu.distillation_tower('frontiers:petrochem/condensed_refinery_gas_fractionation')
        .inputFluids('8000x cosmiccore:condensed_refinery_gas')
        .outputFluids(['6000x gtceu:methane', '800x gtceu:ethane', '560x gtceu:propane', '480x gtceu:butane', '160x gtceu:helium'])
        .duration(120)
        .EUt(240)

    event.recipes.gtceu.distillation_tower('frontiers:petrochem/olefin_gas_fractionation')
        .inputFluids('8000x cosmiccore:olefin_gases')
        .outputFluids(['3200x gtceu:ethylene', '2000x gtceu:propene', '800x gtceu:butadiene', '600x gtceu:ethane', '600x gtceu:propane', '400x gtceu:butene', '400x gtceu:butane'])
        .disableDistilleryRecipes(true)
        .duration(180)
        .EUt(480)

    event.recipes.gtceu.chemical_reactor('frontiers:petrochem/preserved_ethanol_ethylene_route')
        .inputFluids(['1000x gtceu:sulfuric_acid', '1000x gtceu:ethanol'])
        .outputFluids(['1000x gtceu:ethylene', '1000x gtceu:diluted_sulfuric_acid'])
        .duration(1200)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.cosmiccore.catalytic_reforming('frontiers:petrochem/ethane_catalytic_dehydrogenation')
        .itemInputs('16x cosmiccore:orange_recovery_catalyst')
        .inputFluids('4000x gtceu:ethane')
        .itemOutputs(['15x cosmiccore:orange_recovery_catalyst', 'cosmiccore:depleted_orange_recovery_catalyst'])
        .outputFluids(['4000x gtceu:ethylene', '8000x gtceu:hydrogen'])
        .duration(240)
        .EUt(480)

    event.recipes.cosmiccore.hydrotreating('frontiers:petrochem/ethylene_catalytic_hydrogenation')
        .itemInputs('16x cosmiccore:blue_hydro_catalyst')
        .inputFluids(['4000x gtceu:ethylene', '8000x gtceu:hydrogen'])
        .itemOutputs(['15x cosmiccore:blue_hydro_catalyst', 'cosmiccore:yellow_hydro_catalyst'])
        .outputFluids('4000x gtceu:ethane')
        .duration(280)
        .EUt(480)

    event.recipes.cosmiccore.catalytic_reforming('frontiers:petrochem/propane_catalytic_dehydrogenation')
        .itemInputs('16x cosmiccore:orange_recovery_catalyst')
        .inputFluids('4000x gtceu:propane')
        .itemOutputs(['15x cosmiccore:orange_recovery_catalyst', 'cosmiccore:depleted_orange_recovery_catalyst'])
        .outputFluids(['4000x gtceu:propene', '8000x gtceu:hydrogen'])
        .duration(280)
        .EUt(480)
})
