ServerEvents.recipes(event => {
    event.recipes.gtceu.vacuum_freezer('frontiers:petrochem/waxy_distillate_dewaxing')
        .inputFluids('4000x cosmiccore:waxy_distillates')
        .itemOutputs('8x cosmiccore:bitumen_wax')
        .outputFluids('3000x gtceu:lubricant')
        .circuit(21)
        .duration(240)
        .EUt(120)

    event.recipes.cosmiccore.delayed_coking('frontiers:petrochem/atmospheric_residue_delayed_coking')
        .inputFluids('4000x cosmiccore:atmospheric_residue')
        .itemOutputs('8x cosmiccore:petroleum_coke_dust')
        .outputFluids(['500x gtceu:refinery_gas', '1000x cosmiccore:cracked_naphtha', '600x cosmiccore:light_cycle_oil', '900x cosmiccore:slurry_oils'])
        .circuit(22)
        .duration(200)
        .EUt(320)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/vacuum_residue_solvent_deasphalting')
        .inputFluids(['4000x cosmiccore:vacuum_residuals', '1000x gtceu:propane'])
        .outputFluids(['1600x cosmiccore:vacuum_gas_oils', '2400x cosmiccore:bitumen', '1000x gtceu:propane'])
        .circuit(23)
        .duration(200)
        .EUt(360)

    event.recipes.cosmiccore.delayed_coking('frontiers:petrochem/vacuum_residue_delayed_coking')
        .inputFluids('4000x cosmiccore:vacuum_residuals')
        .itemOutputs('12x cosmiccore:petroleum_coke_dust')
        .outputFluids(['400x gtceu:refinery_gas', '1200x cosmiccore:cracked_naphtha', '800x cosmiccore:light_cycle_oil', '600x cosmiccore:slurry_oils'])
        .circuit(23)
        .duration(240)
        .EUt(840)

    event.recipes.gtceu.large_chemical_reactor('frontiers:petrochem/vacuum_residue_gasification')
        .inputFluids(['4000x cosmiccore:vacuum_residuals', '4000x gtceu:steam', '2000x gtceu:oxygen'])
        .outputFluids(['9000x cosmiccore:syngas', '1000x gtceu:carbon_dioxide'])
        .circuit(23)
        .duration(260)
        .EUt(840)

    event.recipes.cosmiccore.large_roaster('frontiers:petrochem/petroleum_coke_calcination')
        .itemInputs('16x cosmiccore:petroleum_coke_dust')
        .itemOutputs('16x cosmiccore:calcined_petroleum_coke_dust')
        .outputFluids('1000x gtceu:refinery_gas')
        .circuit(24)
        .duration(240)
        .EUt(480)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/syngas_fractionation')
        .inputFluids(['8000x cosmiccore:syngas', '2000x gtceu:steam'])
        .outputFluids(['6000x gtceu:hydrogen', '3000x gtceu:carbon_monoxide', '1000x gtceu:carbon_dioxide'])
        .circuit(24)
        .duration(200)
        .EUt(320)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/slurry_oil_recovery_wash')
        .inputFluids(['4000x cosmiccore:slurry_oils', '2000x minecraft:water'])
        .outputFluids(['2000x cosmiccore:heavy_pyrolysis_oils', '3000x cosmiccore:oil_rich_wastewater', '1000x cosmiccore:oily_sludge'])
        .duration(140)
        .EUt(240)
})
