ServerEvents.recipes(event => {
    event.recipes.cosmiccore.steam_cracking_furnace('frontiers:petrochem/refinery_gas_steam_cracking')
        .inputFluids(['4000x gtceu:refinery_gas', '25x minecraft:water'])
        .outputFluids('4000x cosmiccore:hot_light_effluents')
        .circuit(1)
        .duration(80)
        .EUt(240)

    event.recipes.cosmiccore.steam_cracking_furnace('frontiers:petrochem/light_naphtha_steam_cracking')
        .inputFluids(['4000x gtceu:light_naphtha', '25x minecraft:water'])
        .outputFluids('4000x cosmiccore:hot_naphtha_effluents')
        .circuit(2)
        .duration(100)
        .EUt(360)

    event.recipes.cosmiccore.steam_cracking_furnace('frontiers:petrochem/gas_oil_steam_cracking')
        .inputFluids(['4000x gtceu:gas_oils', '25x minecraft:water'])
        .outputFluids('4000x cosmiccore:hot_gas_oil_effluents')
        .circuit(3)
        .duration(140)
        .EUt(480)

    event.recipes.cosmiccore.steam_cracking_furnace('frontiers:petrochem/heavy_pyrolysis_oil_recracking')
        .inputFluids(['4000x cosmiccore:heavy_pyrolysis_oils', '25x minecraft:water'])
        .outputFluids('4000x cosmiccore:hot_gas_oil_effluents')
        .circuit(4)
        .duration(160)
        .EUt(480)

    event.recipes.cosmiccore.fractional_condenser('frontiers:petrochem/hot_light_effluent_condensation')
        .inputFluids('4000x cosmiccore:hot_light_effluents')
        .outputFluids(['600x gtceu:refinery_gas', '3000x cosmiccore:olefin_gases', '200x cosmiccore:cracked_naphtha', '100x cosmiccore:aromatic_oil', '100x cosmiccore:heavy_pyrolysis_oils'])
        .duration(100)
        .EUt(120)

    event.recipes.cosmiccore.fractional_condenser('frontiers:petrochem/hot_naphtha_effluent_condensation')
        .inputFluids('4000x cosmiccore:hot_naphtha_effluents')
        .itemOutputs('gtceu:carbon_dust')
        .outputFluids(['400x gtceu:refinery_gas', '2000x cosmiccore:olefin_gases', '800x cosmiccore:cracked_naphtha', '600x cosmiccore:aromatic_oil', '200x cosmiccore:heavy_pyrolysis_oils'])
        .duration(140)
        .EUt(240)

    event.recipes.cosmiccore.fractional_condenser('frontiers:petrochem/hot_gas_oil_effluent_condensation')
        .inputFluids('4000x cosmiccore:hot_gas_oil_effluents')
        .itemOutputs('3x gtceu:carbon_dust')
        .outputFluids(['200x gtceu:refinery_gas', '1200x cosmiccore:olefin_gases', '800x cosmiccore:cracked_naphtha', '600x cosmiccore:aromatic_oil', '1200x cosmiccore:heavy_pyrolysis_oils'])
        .duration(160)
        .EUt(360)
})
