ServerEvents.recipes(event => {
    event.recipes.gtceu.pyrolyse_oven('frontiers:charcoal/from_logs')
        .itemInputs('8x #minecraft:logs_that_burn')
        .inputFluids('500x gtceu:nitrogen')
        .itemOutputs('10x minecraft:charcoal')
        .outputFluids('2000x cosmiccore:hot_pyrolysis_vapors')
        .duration(160)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.pyrolyse_oven('frontiers:charcoal/from_wood_dust')
        .itemInputs('48x gtceu:wood_dust')
        .inputFluids('500x gtceu:nitrogen')
        .itemOutputs('10x minecraft:charcoal')
        .outputFluids('2000x cosmiccore:hot_pyrolysis_vapors')
        .duration(160)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.extractor('frontiers:hot_pyrolysis_vapors')
        .itemInputs('8x minecraft:charcoal')
        .outputFluids('1000x cosmiccore:hot_pyrolysis_vapors')
        .duration(80)
        .EUt(GTValues.V[GTValues.LV], 2)

    event.recipes.gtceu.distillery('frontiers:crude_benzene')
        .inputFluids('2000x cosmiccore:hot_pyrolysis_vapors')
        .outputFluids('200x cosmiccore:crude_benzene')
        .circuit(1)
        .duration(40)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.cosmiccore.fractional_condenser('frontiers:petrochem/hot_pyrolysis_vapor_condensation')
        .inputFluids('4000x cosmiccore:hot_pyrolysis_vapors')
        .outputFluids(['1000x gtceu:wood_gas', '1600x gtceu:wood_vinegar', '1400x gtceu:wood_tar'])
        .duration(120)
        .EUt(GTValues.V[GTValues.MV], 4)

    event.recipes.cosmiccore.phase_separator('frontiers:petrochem/wood_gas_fractionation')
        .inputFluids('1000x gtceu:wood_gas')
        .outputFluids(['490x gtceu:carbon_dioxide', '340x gtceu:carbon_monoxide', '130x gtceu:methane', '20x gtceu:ethylene', '20x gtceu:hydrogen'])
        .duration(40)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:wood_spirit')
        .inputFluids('1600x gtceu:wood_vinegar')
        .outputFluids(['560x cosmiccore:wood_spirit', '1040x cosmiccore:acidic_wood_liquor'])
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:methanol')
        .inputFluids('560x cosmiccore:wood_spirit')
        .outputFluids(['420x gtceu:methanol', '80x gtceu:acetone', '40x gtceu:ethanol', '20x gtceu:methyl_acetate'])
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:water')
        .inputFluids('1040x cosmiccore:acidic_wood_liquor')
        .outputFluids(['800x minecraft:water', '240x gtceu:acetic_acid'])
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:light_tar_oils/from_wood_tar')
        .inputFluids('1400x gtceu:wood_tar')
        .outputFluids(['840x cosmiccore:light_tar_oils', '210x cosmiccore:phenolic_oils', '210x gtceu:creosote', '140x cosmiccore:tar_pitch'])
        .duration(80)
        .EUt(GTValues.V[GTValues.HV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:benzene/from_light_tar_oils')
        .inputFluids('840x cosmiccore:light_tar_oils')
        .outputFluids(['315x gtceu:benzene', '90x gtceu:toluene', '435x gtceu:mixed_xylenes'])
        .duration(80)
        .EUt(GTValues.V[GTValues.MV], 2)

    event.recipes.gtceu.distillation_tower('frontiers:phenol')
        .inputFluids('210x cosmiccore:phenolic_oils')
        .outputFluids(['140x gtceu:phenol', '70x gtceu:creosote'])
        .duration(60)
        .EUt(GTValues.V[GTValues.MV], 2)
})
