name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number of the release'
        required: true
        type: string  
      version_type:
        description: 'The type of version to release (alpha | beta | release)'
        default: 'beta'
        required: true
        type: string

permissions:
  contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y jq zip

            - name: Prepare server pack
              run: |
                serverdir=Cosmic.Frontiers.Server.${{ github.event.inputs.version }}
                mkdir -p $serverdir

                # copy overrides
                cp -r overrides $serverdir/

                # Extract blacklisted IDs as a pattern
                pattern=$(jq -r '.[].id' server-mod-blacklist.json | paste -sd'|' -)
                # Remove lines containing any blacklisted project ID
                grep -Ev "/projects/($pattern)" modlist.html > $serverdir/modlist.html
                
                # Extract blacklisted projectIDs into a jq array
                BLACKLIST=$(jq '[.[].id]' server-mod-blacklist.json)
                # Filter manifest.json files array
                jq --argjson blacklist "$BLACKLIST" '.files |= map(select(.projectID as $id | ($blacklist | index($id) | not)))' manifest.json > $serverdir/manifest.json

            - name: Prepare client and server zip
              run: |
                zip -r Cosmic.Frontiers.Server.${{ github.event.inputs.version }}.zip Cosmic.Frontiers.Server.${{ github.event.inputs.version }}/
                zip -r Cosmic.Frontiers.${{ github.event.inputs.version }}.zip manifest.json modlist.html overrides
            
            - name: Action test
              uses: henkelmax/build-modpack-server-action@v1.0.0
              with:
                modpack-path: ./Cosmic.Frontiers.${{ github.event.inputs.version }}.zip
                output-path: ./Cosmic.Frontiers.GeneratedServer.${{ github.event.inputs.version }}.zip
            
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                path: |
                  Cosmic.Frontiers.GeneratedServer.${{ github.event.inputs.version }}.zip
                  Cosmic.Frontiers.Server.${{ github.event.inputs.version }}.zip
                  Cosmic.Frontiers.${{ github.event.inputs.version }}.zip