name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Install Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.x'
#
#      - name: Install Python dependencies
#        run: pip install -r scripts/requirements.txt
#
#      - name: Run release script
#        env:
#          RELEASE_VERSION: ${{ github.event.inputs.version }}
#          RELEASE_PRERELEASE: ${{ github.event.inputs.prerelease }}
#          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
#        run: |
#          python scripts/release.py

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: "COMMIT"
          ignorePreReleases: true
          fetchViaCommits: true
          failOnError: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Cosmic Frontier ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
          body: ${{ steps.build_changelog.outputs.changelog }}
#          files: |
#            Cosmic.Frontier.${{ github.event.inputs.version }}.zip
#            Cosmic.Frontier.Server.${{ github.event.inputs.version }}.zip
